<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
echo "<title>Help & Support | Food Delivery</title>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">";
echo "<style>";
echo ":root { --bg:#f8fafc; --text:#1a202c; --panel:#ffffff; --ring:#e2e8f0 }";
echo ".dark :root, .dark { --bg:#0f172a; --text:#e5e7eb; --panel:#0b1220; --ring:#1f2937 }";
echo "body { font-family: 'Poppins', sans-serif; background: var(--bg); margin: 0; color: var(--text); }";
echo "header { background: var(--panel); padding: 15px 30px; box-shadow: 0 2px 4px rgba(0,0,0,.06); display: flex; justify-content: space-between; align-items: center; }";
echo "header .logo { display: flex; align-items: center; gap: 10px; font-weight: 800; color: #1e293b; font-size: 1.2rem; }";
echo "header .logo img { height: 32px; width: 32px; }";
echo ".nav-right { display: flex; gap: 20px; align-items: center; font-weight: 600; }";
echo ".nav-right a { color: #475569; text-decoration: none; }";
echo ".nav-right a:hover { color: #f97316; }";
echo "";
echo ".container { max-width: 1200px; margin: 24px auto; padding: 0 16px; display: flex; gap: 20px; }";
echo ".sidebar { width: 250px; background: var(--panel); border: 1px solid var(--ring); border-radius: 12px; padding: 16px; box-shadow: 0 2px 6px rgba(0,0,0,.06); }";
echo ".sidebar h2 { font-size: 1.2rem; margin-bottom: 16px; color: var(--text); }";
echo ".sidebar ul { list-style: none; padding: 0; }";
echo ".sidebar ul li { margin-bottom: 10px; }";
echo ".sidebar ul li a { color: #64748b; text-decoration: none; font-weight: 500; }";
echo ".sidebar ul li a:hover { color: #f97316; }";
echo ".sidebar ul li.active a { color: #f97316; font-weight: 600; }";
echo "";
echo ".main-content { flex: 1; background: var(--panel); border: 1px solid var(--ring); border-radius: 12px; padding: 16px; box-shadow: 0 2px 6px rgba(0,0,0,.06); }";
echo ".main-content h1 { font-size: 1.5rem; margin-bottom: 16px; color: var(--text); }";
echo ".faq-section { margin-bottom: 20px; }";
echo ".faq-section h2 { font-size: 1.2rem; margin-bottom: 12px; color: #1e293b; }";
echo ".faq-item { border-bottom: 1px solid #e2e8f0; padding: 12px 0; }";
echo ".faq-item:last-child { border-bottom: none; }";
echo ".faq-item .q { font-weight: 700; margin-bottom: 6px; cursor: pointer; position: relative; }";
echo ".faq-item .q::after { content: '▼'; position: absolute; right: 0; transition: transform 0.3s; }";
echo ".faq-item.open .q::after { transform: rotate(180deg); }";
echo ".faq-item .a { color: #64748b; display: none; margin-top: 6px; }";
echo ".faq-item.open .a { display: block; }";
echo "";
echo ".back { display: inline-flex; align-items: center; gap: 8px; margin-bottom: 14px; color: #f97316; text-decoration: none; font-weight: 600; }";
echo "";
echo "/* Chatbot Styles */";
echo ".chatbot-container { position: fixed; bottom: 20px; right: 20px; z-index: 1000; }";
echo ".chatbot-toggle { width: 60px; height: 60px; border-radius: 50%; background: #f97316; color: white; border: none; cursor: pointer; box-shadow: 0 4px 12px rgba(0,0,0,0.3); display: flex; align-items: center; justify-content: center; font-size: 24px; transition: all 0.3s ease; }";
echo ".chatbot-toggle:hover { transform: scale(1.1); background: #ea580c; }";
echo ".chatbot-window { position: absolute; bottom: 80px; right: 0; width: 350px; height: 500px; background: white; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.2); display: none; flex-direction: column; overflow: hidden; }";
echo ".chatbot-header { background: #f97316; color: white; padding: 16px; display: flex; justify-content: space-between; align-items: center; }";
echo ".chatbot-header h3 { margin: 0; font-size: 16px; }";
echo ".chatbot-close { background: none; border: none; color: white; font-size: 20px; cursor: pointer; }";
echo ".chatbot-messages { flex: 1; padding: 16px; overflow-y: auto; display: flex; flex-direction: column; gap: 12px; }";
echo ".message { max-width: 80%; padding: 12px; border-radius: 12px; word-wrap: break-word; }";
echo ".message.user { background: #f97316; color: white; align-self: flex-end; margin-left: auto; }";
echo ".message.bot { background: #f1f5f9; color: #1e293b; align-self: flex-start; }";
echo ".chatbot-input { padding: 16px; border-top: 1px solid #e2e8f0; display: flex; gap: 8px; }";
echo ".chatbot-input input { flex: 1; padding: 12px; border: 1px solid #e2e8f0; border-radius: 8px; outline: none; }";
echo ".chatbot-input button { padding: 12px 16px; background: #f97316; color: white; border: none; border-radius: 8px; cursor: pointer; }";
echo ".chatbot-input button:hover { background: #ea580c; }";
echo "";
echo "/* Call Button Styles */";
echo ".call-button { position: fixed; bottom: 20px; left: 20px; z-index: 1000; }";
echo ".call-btn { width: 60px; height: 60px; border-radius: 50%; background: #10b981; color: white; border: none; cursor: pointer; box-shadow: 0 4px 12px rgba(0,0,0,0.3); display: flex; align-items: center; justify-content: center; font-size: 24px; transition: all 0.3s ease; }";
echo ".call-btn:hover { transform: scale(1.1); background: #059669; }";
echo ".call-modal { position: fixed; inset: 0; background: rgba(0,0,0,0.5); display: none; align-items: center; justify-content: center; z-index: 2000; }";
echo ".call-modal-content { background: white; padding: 24px; border-radius: 12px; text-align: center; max-width: 400px; width: 90%; }";
echo ".call-modal h3 { margin: 0 0 16px 0; color: #1e293b; }";
echo ".call-modal p { color: #64748b; margin-bottom: 20px; }";
echo ".call-modal-buttons { display: flex; gap: 12px; justify-content: center; }";
echo ".call-modal button { padding: 12px 24px; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; }";
echo ".call-confirm { background: #10b981; color: white; }";
echo ".call-cancel { background: #e2e8f0; color: #64748b; }";
echo "</style>";
echo "</head>";
echo "<body>";
echo "<button id=\"dmBtn\" style=\"position:fixed;top:12px;right:12px;z-index:50;background:#f97316;color:#fff;border:none;border-radius:9999px;width:40px;height:40px;cursor:pointer\">🌓</button>";
echo "<header>";
echo "<a class=\"logo\" href=\"swiggyhome.php\">";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/2838/2838912.png\" alt=\"logo\"/>";
echo "SWIGGY";
echo "</a>";
echo "<nav class=\"nav-right\">";
echo "<a href=\"swiggyhome.php\">Home</a>";
echo "<a href=\"offers.php\">Offers</a>";
echo "<a href=\"help.php\">Help</a>";
echo "<a href=\"payment.php\">Cart</a>";
echo "<a href=\"my acc.php\">User</a>";
echo "</nav>";
echo "</header>";
echo "";
echo "<main class=\"container\">";
echo "";
echo "<div class=\"sidebar\">";
echo "<h2>Help & Support</h2>";
echo "<ul>";
echo "<li class=\"active\"><a href=\"#customer-faq\">Customer Help</a></li>";
echo "<li><a href=\"#partner-onboarding\">Partner Onboarding</a></li>";
echo "<li><a href=\"#legal\">Legal</a></li>";
echo "<li><a href=\"#faqs\">FAQs</a></li>";
echo "<li><a href=\"#instamart-onboarding\">Instamart Onboarding</a></li>";
echo "<li><a href=\"#irctc-faq\">IRCTC FAQ</a></li>";
echo "</ul>";
echo "</div>";
echo "";
echo "<div class=\"main-content\">";
echo "<h1>Help & Support</h1>";
echo "<div id=\"customer-faq\" class=\"faq-section\">";
echo "<h2>Customer Help</h2>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I place my first order?</div>";
echo "<div class=\"a\">It's easy! Just search for your favorite restaurant, add items to your cart, and checkout. We'll have your food delivered in 25-30 minutes.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I track my order?</div>";
echo "<div class=\"a\">Once you place an order, you can track it in real-time. We'll show you when your food is being prepared, picked up, and delivered.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What payment methods do you accept?</div>";
echo "<div class=\"a\">We accept credit/debit cards, UPI, net banking, and cash on delivery. Choose whatever works best for you!</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">Can I schedule an order for later?</div>";
echo "<div class=\"a\">Yes! You can schedule your order up to 7 days in advance. Just select \"Schedule Order\" during checkout and pick your preferred time.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I customize my food order?</div>";
echo "<div class=\"a\">Use our quick customization buttons like \"No Onion\", \"Extra Spicy\", or \"Extra Cheese\". You can also add special instructions in the delivery notes.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What if my order is delayed?</div>";
echo "<div class=\"a\">We'll keep you updated if there are any delays. You can always contact our support team or chat with your delivery partner for real-time updates.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I cancel my order?</div>";
echo "<div class=\"a\">You can cancel your order before it's prepared. Just go to your order tracking page and click \"Cancel Order\" if it's still possible.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What if I'm not satisfied with my order?</div>";
echo "<div class=\"a\">We want you to be happy! Contact our support team and we'll work with you to make it right, including refunds if needed.</div>";
echo "</div>";
echo "</div>";
echo "<div id=\"partner-onboarding\" class=\"faq-section\" style=\"display:none;\">";
echo "<h2>Partner Onboarding</h2>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">I want to partner my restaurant with Swiggy</div>";
echo "<div class=\"a\">To partner with Swiggy, visit our <a href=\"https://www.swiggy.com/partner-with-us\">partner onboarding page</a> and fill out the application form with your restaurant details.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What are the mandatory documents needed to list my restaurant on Swiggy?</div>";
echo "<div class=\"a\">You need a valid FSSAI license, PAN card, GST registration, and proof of address. Additional documents may be required based on your location.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I update my restaurant menu on Swiggy?</div>";
echo "<div class=\"a\">Log into your partner dashboard and navigate to the menu section to add or update items.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What is the commission rate for partnering with Swiggy?</div>";
echo "<div class=\"a\">Commission rates vary by location and order volume; contact your account manager for details.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How can I cancel my partnership with Swiggy?</div>";
echo "<div class=\"a\">Submit a cancellation request via the partner dashboard or email <a href=\"mailto:support@swiggy.com\">support@swiggy.com</a>.</div>";
echo "</div>";
echo "</div>";
echo "<div id=\"legal\" class=\"faq-section\" style=\"display:none;\">";
echo "<h2>Legal</h2>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">I want to opt-out from Google Reserve</div>";
echo "<div class=\"a\">Contact our support team at <a href=\"mailto:support@swiggy.com\">support@swiggy.com</a> with your restaurant ID and request details.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What are the terms and conditions for partnering?</div>";
echo "<div class=\"a\">Review the full terms on our <a href=\"https://www.swiggy.com/legal\">legal page</a> before signing up.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How is my data protected on Swiggy?</div>";
echo "<div class=\"a\">We use encryption and comply with GDPR and local data protection laws to secure your information.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What should I do if I receive a legal notice?</div>";
echo "<div class=\"a\">Notify our legal team immediately at <a href=\"mailto:legal@swiggy.com\">legal@swiggy.com</a> with all details.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">Are there any penalties for late deliveries?</div>";
echo "<div class=\"a\">Penalties may apply; refer to your partnership agreement for specific terms.</div>";
echo "</div>";
echo "</div>";
echo "<div id=\"faqs\" class=\"faq-section\" style=\"display:none;\">";
echo "<h2>FAQs</h2>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">After I submit all documents, how long will it take for my restaurant to go live on Swiggy?</div>";
echo "<div class=\"a\">Processing typically takes 7-10 business days after all documents are verified.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What should I do if my order is delayed?</div>";
echo "<div class=\"a\">Contact customer support at <a href=\"mailto:support@swiggy.com\">support@swiggy.com</a> with your order ID.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How can I check my earnings as a partner?</div>";
echo "<div class=\"a\">Log into the partner dashboard to view your earnings report.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What happens if a customer cancels an order?</div>";
echo "<div class=\"a\">You will be notified, and no commission will be charged for canceled orders.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I report an issue with the app?</div>";
echo "<div class=\"a\">Use the 'Report a Problem' option in the app or email <a href=\"mailto:support@swiggy.com\">support@swiggy.com</a>.</div>";
echo "</div>";
echo "</div>";
echo "<div id=\"instamart-onboarding\" class=\"faq-section\" style=\"display:none;\">";
echo "<h2>Instamart Onboarding</h2>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What is this one-time Onboarding fee? Do I have to pay for it while registering?</div>";
echo "<div class=\"a\">The one-time onboarding fee is optional and covers additional support services. It’s not mandatory during registration.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I set up my Instamart store?</div>";
echo "<div class=\"a\">Follow the setup guide in the Instamart partner portal after approval.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What are the eligibility criteria for Instamart?</div>";
echo "<div class=\"a\">You need a valid trade license and a minimum stock inventory; contact support for details.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How are Instamart deliveries handled?</div>";
echo "<div class=\"a\">Swiggy handles deliveries; you only need to prepare and pack the orders.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">Can I update my Instamart inventory online?</div>";
echo "<div class=\"a\">Yes, use the partner dashboard to update your inventory in real-time.</div>";
echo "</div>";
echo "</div>";
echo "<div id=\"irctc-faq\" class=\"faq-section\" style=\"display:none;\">";
echo "<h2>IRCTC FAQ</h2>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">Who should I contact if I need help or support in getting onboarded?</div>";
echo "<div class=\"a\">Reach out to our support team at <a href=\"mailto:support@swiggy.com\">support@swiggy.com</a> or call +91 98765 43210.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What is the process for IRCTC integration?</div>";
echo "<div class=\"a\">Submit your IRCTC credentials via the partner dashboard for integration.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">Are there additional fees for IRCTC services?</div>";
echo "<div class=\"a\">No additional fees apply; it’s included in the partnership plan.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">How do I troubleshoot IRCTC order issues?</div>";
echo "<div class=\"a\">Check the order status in the dashboard or contact support for assistance.</div>";
echo "</div>";
echo "<div class=\"faq-item\">";
echo "<div class=\"q\">What are the benefits of IRCTC integration?</div>";
echo "<div class=\"a\">It allows seamless order placement for train passengers, increasing your reach.</div>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</main>";
echo "";
echo "<!-- AI Chatbot -->";
echo "<div class=\"chatbot-container\">";
echo "<button class=\"chatbot-toggle\" id=\"chatbotToggle\">";
echo "<i class=\"fas fa-robot\"></i>";
echo "</button>";
echo "<div class=\"chatbot-window\" id=\"chatbotWindow\">";
echo "<div class=\"chatbot-header\">";
echo "<h3>AI Assistant</h3>";
echo "<button class=\"chatbot-close\" id=\"chatbotClose\">×</button>";
echo "</div>";
echo "<div class=\"chatbot-messages\" id=\"chatbotMessages\">";
echo "<div class=\"message bot\">";
echo "Hi! I'm here to help you with your food delivery needs. You can ask me about:";
echo "<br>• Your order status";
echo "<br>• Delivery problems";
echo "<br>• Payment issues";
echo "<br>• Finding restaurants";
echo "<br>• Scheduling orders";
echo "<br>• Customizing your food";
echo "<br>• Anything else!";
echo "</div>";
echo "</div>";
echo "<div class=\"chatbot-input\">";
echo "<input type=\"text\" id=\"chatbotInput\" placeholder=\"Type your message...\">";
echo "<button id=\"chatbotSend\">Send</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Call Delivery Person Button -->";
echo "<div class=\"call-button\">";
echo "<button class=\"call-btn\" id=\"callBtn\">";
echo "<i class=\"fas fa-phone\"></i>";
echo "</button>";
echo "</div>";
echo "";
echo "<!-- Call Modal -->";
echo "<div class=\"call-modal\" id=\"callModal\">";
echo "<div class=\"call-modal-content\">";
echo "<h3>Call Delivery Person</h3>";
echo "<p>Would you like to call your delivery person for assistance?</p>";
echo "<div class=\"call-modal-buttons\">";
echo "<button class=\"call-confirm\" id=\"callConfirm\">Call Now</button>";
echo "<button class=\"call-cancel\" id=\"callCancel\">Cancel</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<script>";
echo "// dark mode";
echo "(function(){";
echo "const saved = localStorage.getItem('theme');";
echo "if(saved === 'dark') document.documentElement.classList.add('dark');";
echo "document.getElementById('dmBtn').addEventListener('click', ()=>{";
echo "document.documentElement.classList.toggle('dark');";
echo "localStorage.setItem('theme', document.documentElement.classList.contains('dark') ? 'dark':'light');";
echo "});";
echo "})();";
echo "(function(){";
echo "const navUser = document.querySelector('.nav-right a[href=\"my acc.php\"]');";
echo "const savedName = localStorage.getItem('userName');";
echo "if (navUser && savedName && savedName.trim()) {";
echo "navUser.textContent = savedName;";
echo "}";
echo "";
echo "// FAQ toggle functionality";
echo "document.querySelectorAll('.faq-item .q').forEach(item => {";
echo "item.addEventListener('click', function() {";
echo "const parent = this.parentElement;";
echo "parent.classList.toggle('open');";
echo "});";
echo "});";
echo "";
echo "// Sidebar navigation";
echo "document.querySelectorAll('.sidebar ul li a').forEach(link => {";
echo "link.addEventListener('click', function(e) {";
echo "e.preventDefault();";
echo "const sectionId = this.getAttribute('href').substring(1);";
echo "document.querySelectorAll('.faq-section').forEach(section => section.style.display = 'none');";
echo "document.getElementById(sectionId).style.display = 'block';";
echo "document.querySelectorAll('.sidebar ul li').forEach(li => li.classList.remove('active'));";
echo "this.parentElement.classList.add('active');";
echo "});";
echo "});";
echo "";
echo "// Load default section";
echo "document.getElementById('customer-faq').style.display = 'block';";
echo "})();";
echo "";
echo "// AI Chatbot functionality";
echo "(function() {";
echo "const chatbotToggle = document.getElementById('chatbotToggle');";
echo "const chatbotWindow = document.getElementById('chatbotWindow');";
echo "const chatbotClose = document.getElementById('chatbotClose');";
echo "const chatbotMessages = document.getElementById('chatbotMessages');";
echo "const chatbotInput = document.getElementById('chatbotInput');";
echo "const chatbotSend = document.getElementById('chatbotSend');";
echo "";
echo "// AI responses based on keywords - using simple language";
echo "const aiResponses = {";
echo "'order': 'I can help you with your order! Tell me your order number or what\\'s going wrong, and I\\'ll help you sort it out.',";
echo "'delivery': 'Having trouble with delivery? I can help you track where your food is or connect you with your delivery person. What\\'s happening?',";
echo "'payment': 'Need help with payment? I can help you with payment issues or getting a refund. What payment method are you using?',";
echo "'refund': 'Want a refund? No problem! Give me your order details and why you need a refund. We\\'ll process it within 3-5 business days.',";
echo "'cancel': 'Want to cancel your order? You can cancel it before it\\'s prepared. Go to your order tracking page and click \"Cancel Order\" if it\\'s still possible.',";
echo "'track': 'Want to track your order? Go to your order tracking page or give me your order number and I\\'ll help you find it.',";
echo "'restaurant': 'Looking for restaurants? I can help you find great places to eat, check their menus, or tell you about restaurants near you.',";
echo "'schedule': 'Want to schedule an order? You can book your food up to 7 days in advance! Just select \"Schedule Order\" during checkout.',";
echo "'customize': 'Want to customize your food? Use our quick buttons like \"No Onion\" or \"Extra Spicy\", or add special instructions in the delivery notes.',";
echo "'help': 'I\\'m here to help! Ask me about orders, deliveries, payments, restaurants, or anything else. What do you need?',";
echo "'default': 'I\\'m here to help! Tell me what\\'s going on and I\\'ll do my best to help you out. You can ask about orders, deliveries, payments, or anything else.'";
echo "};";
echo "";
echo "function getAIResponse(userMessage) {";
echo "const message = userMessage.toLowerCase();";
echo "";
echo "for (const [keyword, response] of Object.entries(aiResponses)) {";
echo "if (keyword !== 'default' && message.includes(keyword)) {";
echo "return response;";
echo "}";
echo "}";
echo "return aiResponses.default;";
echo "}";
echo "";
echo "function addMessage(content, isUser = false) {";
echo "const messageDiv = document.createElement('div');";
echo "messageDiv.className = `message ${isUser ? 'user' : 'bot'}`;";
echo "messageDiv.textContent = content;";
echo "chatbotMessages.appendChild(messageDiv);";
echo "chatbotMessages.scrollTop = chatbotMessages.scrollHeight;";
echo "}";
echo "";
echo "function sendMessage() {";
echo "const message = chatbotInput.value.trim();";
echo "if (!message) return;";
echo "";
echo "addMessage(message, true);";
echo "chatbotInput.value = '';";
echo "";
echo "// Simulate AI thinking delay";
echo "setTimeout(() => {";
echo "const response = getAIResponse(message);";
echo "addMessage(response);";
echo "}, 1000);";
echo "}";
echo "";
echo "// Event listeners";
echo "chatbotToggle.addEventListener('click', () => {";
echo "chatbotWindow.style.display = chatbotWindow.style.display === 'flex' ? 'none' : 'flex';";
echo "});";
echo "";
echo "chatbotClose.addEventListener('click', () => {";
echo "chatbotWindow.style.display = 'none';";
echo "});";
echo "";
echo "chatbotSend.addEventListener('click', sendMessage);";
echo "";
echo "chatbotInput.addEventListener('keypress', (e) => {";
echo "if (e.key === 'Enter') {";
echo "sendMessage();";
echo "}";
echo "});";
echo "";
echo "// Close chatbot when clicking outside";
echo "document.addEventListener('click', (e) => {";
echo "if (!e.target.closest('.chatbot-container')) {";
echo "chatbotWindow.style.display = 'none';";
echo "}";
echo "});";
echo "})();";
echo "";
echo "// Call functionality";
echo "(function() {";
echo "const callBtn = document.getElementById('callBtn');";
echo "const callModal = document.getElementById('callModal');";
echo "const callConfirm = document.getElementById('callConfirm');";
echo "const callCancel = document.getElementById('callCancel');";
echo "";
echo "callBtn.addEventListener('click', () => {";
echo "callModal.style.display = 'flex';";
echo "});";
echo "";
echo "callConfirm.addEventListener('click', () => {";
echo "// Simulate calling delivery person";
echo "alert('Calling delivery person...\\n\\nIn a real app, this would initiate a call to the delivery person\\'s phone number.');";
echo "callModal.style.display = 'none';";
echo "});";
echo "";
echo "callCancel.addEventListener('click', () => {";
echo "callModal.style.display = 'none';";
echo "});";
echo "";
echo "// Close modal when clicking outside";
echo "callModal.addEventListener('click', (e) => {";
echo "if (e.target === callModal) {";
echo "callModal.style.display = 'none';";
echo "}";
echo "});";
echo "})();";
echo "</script>";
echo "</body>";
echo "</html>";
?>