<?php
echo "<!doctype html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"utf-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />";
echo "<title>Swiggy — Restaurants in Kottayam</title>";
echo "<script src=\"https://cdn.tailwindcss.com\"></script>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">";
echo "<style>";
echo ".card-img {";
echo "aspect-ratio: 16/10;";
echo "object-fit: cover;";
echo "}";
echo ".chip { @apply inline-flex items-center px-3 py-2 border rounded-full text-sm; }";
echo "";
echo "/* Orange filter chips */";
echo ".chip.orange-filter {";
echo "background-color: #fb923c;";
echo "color: white;";
echo "border-color: #ea580c;";
echo "}";
echo "";
echo "/* Dark mode styles */";
echo ".dark-mode {";
echo "--bg-primary: #1f2937;";
echo "--bg-secondary: #374151;";
echo "--text-primary: #f3f4f6;";
echo "--text-secondary: #e5e7eb;";
echo "--border-color: #4b5563;";
echo "}";
echo "";
echo "body.dark-mode {";
echo "background-color: var(--bg-primary);";
echo "color: var(--text-primary);";
echo "}";
echo "";
echo "body.dark-mode header {";
echo "background-color: var(--bg-secondary);";
echo "}";
echo "";
echo "body.dark-mode .border,";
echo "body.dark-mode .border-t,";
echo "body.dark-mode .border-gray-200 {";
echo "border-color: var(--border-color);";
echo "}";
echo "";
echo "body.dark-mode .bg-white {";
echo "background-color: var(--bg-secondary);";
echo "}";
echo "";
echo "body.dark-mode .bg-gray-50 {";
echo "background-color: var(--bg-primary);";
echo "}";
echo "";
echo "body.dark-mode .text-gray-800 {";
echo "color: var(--text-primary);";
echo "}";
echo "";
echo "body.dark-mode .text-gray-600 {";
echo "color: var(--text-secondary);";
echo "}";
echo "";
echo "body.dark-mode .text-gray-500 {";
echo "color: var(--text-secondary);";
echo "opacity: 0.8;";
echo "}";
echo "";
echo "body.dark-mode .hover\\:bg-gray-100:hover {";
echo "background-color: var(--bg-primary);";
echo "}";
echo "";
echo "body.dark-mode input {";
echo "background-color: var(--bg-secondary);";
echo "color: var(--text-primary);";
echo "border-color: var(--border-color);";
echo "}";
echo "";
echo "body.dark-mode .shadow-sm {";
echo "box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.3);";
echo "}";
echo "";
echo "/* Voice search animation */";
echo "@keyframes pulse {";
echo "0% { transform: scale(1); }";
echo "50% { transform: scale(1.1); }";
echo "100% { transform: scale(1); }";
echo "}";
echo "";
echo ".listening {";
echo "animation: pulse 1s infinite;";
echo "color: #ea580c !important;";
echo "}";
echo "";
echo "/* Improved boxes for cities and cuisines */";
echo ".category-box {";
echo "transition: all 0.3s ease;";
echo "border-radius: 12px;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".category-box:hover {";
echo "transform: translateY(-5px);";
echo "box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);";
echo "}";
echo "";
echo ".category-header {";
echo "border-top-left-radius: 12px;";
echo "border-top-right-radius: 12px;";
echo "background: linear-gradient(135deg, #ea580c, #f97316) !important;";
echo "}";
echo "";
echo "/* Improved search bar */";
echo ".search-container {";
echo "position: relative;";
echo "}";
echo "";
echo ".voice-search-btn {";
echo "position: absolute;";
echo "right: 85px;";
echo "top: 50%;";
echo "transform: translateY(-50%);";
echo "background: transparent;";
echo "border: none;";
echo "color: #6b7280;";
echo "cursor: pointer;";
echo "padding: 8px;";
echo "border-radius: 50%;";
echo "transition: all 0.2s ease;";
echo "}";
echo "";
echo ".voice-search-btn:hover {";
echo "color: #ea580c;";
echo "background-color: #f3f4f6;";
echo "}";
echo "";
echo "/* Filter Modal Styles */";
echo ".filter-modal {";
echo "position: fixed;";
echo "top: 0;";
echo "left: 0;";
echo "right: 0;";
echo "bottom: 0;";
echo "background-color: rgba(0, 0, 0, 0.5);";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 50;";
echo "}";
echo "";
echo ".filter-content {";
echo "background-color: white;";
echo "border-radius: 12px;";
echo "width: 90%;";
echo "max-width: 400px;";
echo "max-height: 80vh;";
echo "overflow-y: auto;";
echo "box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);";
echo "}";
echo "";
echo ".dark-mode .filter-content {";
echo "background-color: var(--bg-secondary);";
echo "color: var(--text-primary);";
echo "}";
echo "";
echo ".filter-section {";
echo "border-bottom: 1px solid #e5e7eb;";
echo "padding: 16px;";
echo "}";
echo "";
echo ".filter-section:last-child {";
echo "border-bottom: none;";
echo "}";
echo "";
echo ".filter-option {";
echo "display: flex;";
echo "align-items: center;";
echo "padding: 8px 0;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".filter-option input {";
echo "margin-right: 12px;";
echo "}";
echo "";
echo ".active-filter {";
echo "background-color: #ffedd5;";
echo "border-color: #ea580c;";
echo "}";
echo "";
echo ".dark-mode .active-filter {";
echo "background-color: #7c2d12;";
echo "}";
echo "</style>";
echo "</head>";
echo "<body class=\"bg-white text-gray-800\">";
echo "<!-- Dark Mode Toggle Button -->";
echo "<button id=\"darkModeToggle\" class=\"fixed top-20 right-5 z-40 bg-orange-500 text-white p-3 rounded-full shadow-lg hover:bg-orange-600 transition\">";
echo "🌙";
echo "</button>";
echo "";
echo "<!-- Header -->";
echo "<header class=\"sticky top-0 bg-white shadow-sm z-30\">";
echo "<div class=\"max-w-7xl mx-auto px-4 py-3 flex items-center justify-between\">";
echo "<div class=\"flex items-center gap-4\">";
echo "<a href=\"swiggyhome.html\" class=\"flex items-center gap-2\">";
echo "<div class=\"w-8 h-8 bg-orange-500 rounded-full flex items-center justify-center text-white font-bold\">S</div>";
echo "<span class=\"font-semibold\">Swiggy</span>";
echo "</a>";
echo "<nav class=\"hidden md:flex gap-3 text-sm text-gray-600\">";
echo "<a href=\"swiggyhome.html\" class=\"hover:text-orange-500\">Home</a>";
echo "<a href=\"offers.html\" class=\"hover:text-orange-500\">Offers</a>";
echo "<a href=\"help.html\" class=\"hover:text-orange-500\">Help</a>";
echo "</nav>";
echo "</div>";
echo "<div class=\"flex-1 px-4\">";
echo "<div class=\"max-w-xl mx-auto search-container\">";
echo "<div class=\"relative\">";
echo "<input type=\"search\" id=\"searchInput\" placeholder=\"Search for restaurants, dishes or cuisines\" class=\"w-full border rounded-full px-4 py-3 pl-4 pr-24 shadow-sm\" />";
echo "<button id=\"voiceSearchBtn\" class=\"voice-search-btn\">";
echo "<i class=\"fas fa-microphone\"></i>";
echo "</button>";
echo "<button class=\"absolute right-1 top-1/2 -translate-y-1/2 bg-orange-500 text-white px-3 py-2 rounded-full text-sm\">Search</button>";
echo "</div>";
echo "<div id=\"voiceStatus\" class=\"text-xs text-orange-500 mt-1 text-center hidden\">";
echo "<i class=\"fas fa-circle mr-1\"></i> Listening...";
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class=\"flex items-center gap-4\">";
echo "<a href=\"help.html\" class=\"flex items-center gap-2 px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition text-sm\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "<span class=\"hidden md:inline\">Help</span>";
echo "</a>";
echo "<a href=\"payment.html\" class=\"text-sm hidden md:inline-block\">Cart</a>";
echo "<button id=\"signInBtn\" class=\"text-sm hidden md:inline-block text-orange-600 hover:text-orange-500\">Login</button>";
echo "<div class=\"relative\">";
echo "<button id=\"profileBtn\" class=\"flex items-center gap-2 rounded-md p-2 hover:bg-gray-100\">";
echo "<div class=\"w-8 h-8 rounded-full bg-gray-200\"></div>";
echo "<span id=\"userNameLabel\" class=\"hidden md:inline\">User</span>";
echo "</button>";
echo "<div id=\"profileMenu\" class=\"hidden absolute right-0 mt-2 w-40 bg-white border rounded shadow-lg\">";
echo "<a class=\"block px-4 py-2 hover:bg-gray-50\" href=\"my acc.html\">Profile</a>";
echo "<a class=\"block px-4 py-2 hover:bg-gray-50\" href=\"my acc.html\">Orders</a>";
echo "<a class=\"block px-4 py-2 hover:bg-gray-50\" href=\"my acc.html\">Favourites</a>";
echo "<button id=\"logoutBtn\" class=\"w-full text-left block px-4 py-2 hover:bg-gray-50\">Logout</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</header>";
echo "";
echo "<!-- Page intro & filters -->";
echo "<main class=\"max-w-7xl mx-auto px-4 py-8\">";
echo "<h1 class=\"text-2xl font-bold mb-3\">Restaurants with online food delivery in Kottayam</h1>";
echo "";
echo "<div class=\"flex flex-wrap gap-3 mb-6\">";
echo "<button id=\"filterBtn\" class=\"chip orange-filter\">Filter</button>";
echo "<button id=\"sortBtn\" class=\"chip orange-filter\">Sort By</button>";
echo "<button class=\"chip orange-filter filter-chip\" data-filter=\"fast-delivery\">Fast Delivery</button>";
echo "<button class=\"chip orange-filter filter-chip\" data-filter=\"new\">New on Swiggy</button>";
echo "<button class=\"chip orange-filter filter-chip\" data-filter=\"rating\">Ratings 4.0+</button>";
echo "<button class=\"chip orange-filter filter-chip\" data-filter=\"veg\">Pure Veg</button>";
echo "<button class=\"chip orange-filter filter-chip\" data-filter=\"offers\">Offers</button>";
echo "<button class=\"chip orange-filter filter-chip\" data-filter=\"price-mid\">Rs. 300 - Rs. 600</button>";
echo "<button class=\"chip orange-filter filter-chip\" data-filter=\"price-low\">Less than Rs. 300</button>";
echo "</div>";
echo "";
echo "<!-- Restaurants grid -->";
echo "<section class=\"grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6\" id=\"restaurantsGrid\">";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"kfc\" data-rating=\"4.3\" data-delivery-time=\"25\" data-price=\"400\" data-veg=\"false\" data-offers=\"true\" data-new=\"false\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://b.zmtcdn.com/data/pictures/chains/9/65279/93776f3249312397e2c2ba274b4812ec.jpg?fit=around|960:500&crop=960:500;*,*\" alt=\"KFC\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">50% OFF UPTO ₹80</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">KFC</h3>";
echo "<p class=\"text-sm text-gray-500\">Burgers, Fast Food, Rolls & Wraps — Kanjirappally</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.3</span>";
echo "<span class=\"text-gray-500\">25-30 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"porch_grill\" data-rating=\"4.6\" data-delivery-time=\"35\" data-price=\"350\" data-veg=\"false\" data-offers=\"true\" data-new=\"true\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JpbGwlMjBmb29kfGVufDB8fDB8fHww&w=1000&q=80\" alt=\"Porch Grill\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">₹50 OFF ABOVE ₹249</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Porch Grill</h3>";
echo "<p class=\"text-sm text-gray-500\">Arabian, Grill, Biryani, Barbecue — Cheppumpara</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.6</span>";
echo "<span class=\"text-gray-500\">35-40 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"cutiepie_cakes\" data-rating=\"4.6\" data-delivery-time=\"25\" data-price=\"200\" data-veg=\"true\" data-offers=\"true\" data-new=\"false\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8NHx8fGVufDB8fHx8fA%3D%3D&w=1000&q=80\" alt=\"Cutiepie Cakes\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">₹100 OFF ABOVE ₹199</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Cutiepie Cakes</h3>";
echo "<p class=\"text-sm text-gray-500\">Ice Cream Cakes, Cafe — Kanjirappally</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.6</span>";
echo "<span class=\"text-gray-500\">25-30 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"lazza_ice_cream\" data-rating=\"4.7\" data-delivery-time=\"25\" data-price=\"375\" data-veg=\"true\" data-offers=\"true\" data-new=\"true\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.unsplash.com/photo-1563805042-7684c019e1cb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGljZSUyMGNyZWFtfGVufDB8fDB8fHww&w=1000&q=80\" alt=\"Lazza Ice Cream\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">ITEMS AT ₹375</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Lazza Ice Cream</h3>";
echo "<p class=\"text-sm text-gray-500\">Ice Cream, Desserts, Cafe — Kanjirappally</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.7</span>";
echo "<span class=\"text-gray-500\">25-30 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"apple_bee\" data-rating=\"4.3\" data-delivery-time=\"45\" data-price=\"500\" data-veg=\"false\" data-offers=\"true\" data-new=\"false\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80\" alt=\"Apple Bee Restaurant\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">20% OFF UPTO ₹50</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Apple Bee Restaurant</h3>";
echo "<p class=\"text-sm text-gray-500\">Chinese, Tandoor, Arabian — Kottayam Kumily Road</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.3</span>";
echo "<span class=\"text-gray-500\">45-55 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"kottaram\" data-rating=\"4.3\" data-delivery-time=\"35\" data-price=\"250\" data-veg=\"false\" data-offers=\"true\" data-new=\"false\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80\" alt=\"Kottaram Family Restaurant\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">ITEMS AT ₹79</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Kottaram Family Restaurant</h3>";
echo "<p class=\"text-sm text-gray-500\">Kerala, Biryani, Arabian — Kollam Theni Highway</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.3</span>";
echo "<span class=\"text-gray-500\">35-40 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"cafe_cocoon\" data-rating=\"4.4\" data-delivery-time=\"50\" data-price=\"450\" data-veg=\"false\" data-offers=\"true\" data-new=\"false\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cmVzdGF1cmFudHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80\" alt=\"Cafe Cocoon\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">ITEMS AT ₹149</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Cafe Cocoon</h3>";
echo "<p class=\"text-sm text-gray-500\">Continental, Arabian, Kebabs — Cheppumpara</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.4</span>";
echo "<span class=\"text-gray-500\">50-60 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"funfee\" data-rating=\"4.3\" data-delivery-time=\"60\" data-price=\"300\" data-veg=\"true\" data-offers=\"true\" data-new=\"true\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.unsplash.com/photo-1571091718767-18b5b1457add?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGJ1cmdlcnxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80\" alt=\"Funfee\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">FLAT 30% OFF</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Funfee</h3>";
echo "<p class=\"text-sm text-gray-500\">Burgers, Desserts — Town Center</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.3</span>";
echo "<span class=\"text-gray-500\">60-70 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"cafe_fargozi\">";
echo "<div class=\"relative\">";
echo "<img src=\"Ajfaan Kuzhimanthi.png\" alt=\"Cafe Fargozi\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">₹60 OFF ABOVE ₹199</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Cafe Fargozi</h3>";
echo "<p class=\"text-sm text-gray-500\">Shawarma, Lebanese — Downtown</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.7</span>";
echo "<span class=\"text-gray-500\">35-40 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"nanuha\">";
echo "<div class=\"relative\">";
echo "<img src=\"Garlic Naan.webp\" alt=\"Nanuha Restaurant\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">BESTSELLER</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Nanuha Restaurant</h3>";
echo "<p class=\"text-sm text-gray-500\">South Indian, Dosa — City Center</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.5</span>";
echo "<span class=\"text-gray-500\">40-50 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"tass_bakery\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://images.localista.com.au/eatingout/131371_lrg.jpg\" alt=\"Tass Bakery\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">NEW</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Tass Bakery</h3>";
echo "<p class=\"text-sm text-gray-500\">Cakes, Bakery — Kanjirapally</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.5</span>";
echo "<span class=\"text-gray-500\">40-50 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "";
echo "<article class=\"border rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition restaurant-card cursor-pointer\" data-restaurant-id=\"spice_haven\">";
echo "<div class=\"relative\">";
echo "<img src=\"https://content3.jdmagicbox.com/v2/comp/goa/p1/0832px832.x832.250408204709.d7p1/catalogue/spice-haven-morjim-goa-goan-restaurants-o6xqxi81fy.jpg\" alt=\"Spice Haven\" class=\"w-full card-img\"/>";
echo "<span class=\"absolute top-3 left-3 bg-black/60 text-white text-xs px-2 py-1 rounded\">₹75 OFF ABOVE ₹299</span>";
echo "</div>";
echo "<div class=\"p-4\">";
echo "<h3 class=\"font-semibold\">Spice Haven</h3>";
echo "<p class=\"text-sm text-gray-500\">North Indian, Tandoor — City Center</p>";
echo "<div class=\"mt-3 flex items-center justify-between text-sm\">";
echo "<span>⭐ 4.4</span>";
echo "<span class=\"text-gray-500\">30-35 mins</span>";
echo "</div>";
echo "</div>";
echo "</article>";
echo "</section>";
echo "";
echo "<!-- City links - Improved UI -->";
echo "<section class=\"mt-12\">";
echo "<h2 class=\"text-lg font-semibold mb-4\">Best Places to Eat Across Cities</h2>";
echo "<div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">";
echo "<div class=\"category-box bg-white border rounded-xl shadow-sm overflow-hidden\">";
echo "<div class=\"category-header py-3 px-4 border-b\">";
echo "<h3 class=\"font-semibold text-white\"><i class=\"fas fa-city mr-2\"></i>Metro Cities</h3>";
echo "</div>";
echo "<div class=\"p-4 grid grid-cols-2 gap-2\">";
echo "<button class=\"chip border-gray-200 text-xs\">Bangalore</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Mumbai</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Delhi</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Hyderabad</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"category-box bg-white border rounded-xl shadow-sm overflow-hidden\">";
echo "<div class=\"category-header py-3 px-4 border-b\">";
echo "<h3 class=\"font-semibold text-white\"><i class=\"fas fa-utensils mr-2\"></i>Food Capitals</h3>";
echo "</div>";
echo "<div class=\"p-4 grid grid-cols-2 gap-2\">";
echo "<button class=\"chip border-gray-200 text-xs\">Chennai</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Kolkata</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Pune</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Jaipur</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"category-box bg-white border rounded-xl shadow-sm overflow-hidden\">";
echo "<div class=\"category-header py-3 px-4 border-b\">";
echo "<h3 class=\"font-semibold text-white\"><i class=\"fas fa-map-marker-alt mr-2\"></i>Other Cities</h3>";
echo "</div>";
echo "<div class=\"p-4 grid grid-cols-2 gap-2\">";
echo "<button class=\"chip border-gray-200 text-xs\">Chandigarh</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Ahmedabad</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Nagpur</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Kochi</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</section>";
echo "";
echo "<!-- Cuisine links - Improved UI -->";
echo "<section class=\"mt-8\">";
echo "<h2 class=\"text-lg font-semibold mb-4\">Best Cuisines Near Me</h2>";
echo "<div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">";
echo "<div class=\"category-box bg-white border rounded-xl shadow-sm overflow-hidden\">";
echo "<div class=\"category-header py-3 px-4 border-b\">";
echo "<h3 class=\"font-semibold text-white\"><i class=\"fas fa-flag mr-2\"></i>Indian Cuisines</h3>";
echo "</div>";
echo "<div class=\"p-4 grid grid-cols-2 gap-2\">";
echo "<button class=\"chip border-gray-200 text-xs\">North Indian</button>";
echo "<button class=\"chip border-gray-200 text-xs\">South Indian</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Punjabi</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Bengali</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"category-box bg-white border rounded-xl shadow-sm overflow-hidden\">";
echo "<div class=\"category-header py-3 px-4 border-b\">";
echo "<h3 class=\"font-semibold text-white\"><i class=\"fas fa-globe-asia mr-2\"></i>Asian Cuisines</h3>";
echo "</div>";
echo "<div class=\"p-4 grid grid-cols-2 gap-2\">";
echo "<button class=\"chip border-gray-200 text-xs\">Chinese</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Korean</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Thai</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Japanese</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"category-box bg-white border rounded-xl shadow-sm overflow-hidden\">";
echo "<div class=\"category-header py-3 px-4 border-b\">";
echo "<h3 class=\"font-semibold text-white\"><i class=\"fas fa-globe-europe mr-2\"></i>International</h3>";
echo "</div>";
echo "<div class=\"p-4 grid grid-cols-2 gap-2\">";
echo "<button class=\"chip border-gray-200 text-xs\">Italian</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Mexican</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Continental</button>";
echo "<button class=\"chip border-gray-200 text-xs\">Mediterranean</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</section>";
echo "</main>";
echo "";
echo "<!-- Filter Modal -->";
echo "<div id=\"filterModal\" class=\"filter-modal hidden\">";
echo "<div class=\"filter-content\">";
echo "<div class=\"filter-section\">";
echo "<h3 class=\"font-semibold text-lg mb-3\">Filters</h3>";
echo "<div class=\"space-y-2\">";
echo "<div class=\"filter-option\">";
echo "<input type=\"checkbox\" id=\"deliveryTime\" class=\"filter-checkbox\" data-filter=\"fast-delivery\">";
echo "<label for=\"deliveryTime\">Fast Delivery</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"checkbox\" id=\"newRestaurants\" class=\"filter-checkbox\" data-filter=\"new\">";
echo "<label for=\"newRestaurants\">New on Swiggy</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"checkbox\" id=\"highRating\" class=\"filter-checkbox\" data-filter=\"rating\">";
echo "<label for=\"highRating\">Ratings 4.0+</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"checkbox\" id=\"pureVeg\" class=\"filter-checkbox\" data-filter=\"veg\">";
echo "<label for=\"pureVeg\">Pure Veg</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"checkbox\" id=\"offersAvailable\" class=\"filter-checkbox\" data-filter=\"offers\">";
echo "<label for=\"offersAvailable\">Offers</label>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"filter-section\">";
echo "<h3 class=\"font-semibold text-lg mb-3\">Price Range</h3>";
echo "<div class=\"space-y-2\">";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"priceLow\" name=\"price\" class=\"filter-radio\" data-filter=\"price-low\">";
echo "<label for=\"priceLow\">Less than Rs. 300</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"priceMid\" name=\"price\" class=\"filter-radio\" data-filter=\"price-mid\">";
echo "<label for=\"priceMid\">Rs. 300 - Rs. 600</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"priceHigh\" name=\"price\" class=\"filter-radio\" data-filter=\"price-high\">";
echo "<label for=\"priceHigh\">Above Rs. 600</label>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"filter-section flex justify-between\">";
echo "<button id=\"clearFilters\" class=\"px-4 py-2 border rounded-md hover:bg-gray-50\">Clear All</button>";
echo "<button id=\"applyFilters\" class=\"px-4 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700\">Apply</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Sort Modal -->";
echo "<div id=\"sortModal\" class=\"filter-modal hidden\">";
echo "<div class=\"filter-content\">";
echo "<div class=\"filter-section\">";
echo "<h3 class=\"font-semibold text-lg mb-3\">Sort By</h3>";
echo "<div class=\"space-y-2\">";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"relevance\" name=\"sort\" class=\"sort-radio\" value=\"relevance\" checked>";
echo "<label for=\"relevance\">Relevance (Default)</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"deliveryTimeSort\" name=\"sort\" class=\"sort-radio\" value=\"delivery-time\">";
echo "<label for=\"deliveryTimeSort\">Delivery Time</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"ratingSort\" name=\"sort\" class=\"sort-radio\" value=\"rating\">";
echo "<label for=\"ratingSort\">Rating</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"costLow\" name=\"sort\" class=\"sort-radio\" value=\"cost-low\">";
echo "<label for=\"costLow\">Cost: Low to High</label>";
echo "</div>";
echo "<div class=\"filter-option\">";
echo "<input type=\"radio\" id=\"costHigh\" name=\"sort\" class=\"sort-radio\" value=\"cost-high\">";
echo "<label for=\"costHigh\">Cost: High to Low</label>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"filter-section flex justify-end\">";
echo "<button id=\"applySort\" class=\"px-4 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700\">Apply</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<script>";
echo "// Attach click handlers to restaurant cards to navigate to individual pages";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "document.querySelectorAll('.restaurant-card').forEach(function(card){";
echo "var id = card.getAttribute('data-restaurant-id');";
echo "if(!id) return;";
echo "// build filename like kfc.html or porch_grill.html";
echo "var filename = id + '.html';";
echo "card.addEventListener('click', function(){";
echo "window.location.href = filename;";
echo "});";
echo "// also make Enter key activate when focused";
echo "card.setAttribute('tabindex', '0');";
echo "card.addEventListener('keydown', function(e){";
echo "if(e.key === 'Enter') window.location.href = filename;";
echo "});";
echo "});";
echo "});";
echo "</script>";
echo "";
echo "<!-- Footer -->";
echo "<footer class=\"bg-gray-50 border-t mt-12\">";
echo "<div class=\"max-w-7xl mx-auto px-4 py-10 grid grid-cols-1 md:grid-cols-4 gap-6\">";
echo "<div>";
echo "<div class=\"flex items-center gap-2 mb-3\">";
echo "<div class=\"w-8 h-8 bg-orange-500 rounded-full text-white flex items-center justify-center\">S</div>";
echo "<span class=\"font-semibold\">Swiggy</span>";
echo "</div>";
echo "<p class=\"text-sm text-gray-600\">© 2025 Swiggy Limited</p>";
echo "</div>";
echo "<div>";
echo "<h4 class=\"font-semibold mb-2\">Company</h4>";
echo "<ul class=\"text-sm text-gray-600 space-y-1\">";
echo "<li>About Us</li>";
echo "<li>Swiggy Corporate</li>";
echo "<li>Careers</li>";
echo "<li>Team</li>";
echo "<li>Swiggy One</li>";
echo "<li>Swiggy Instamart</li>";
echo "</ul>";
echo "</div>";
echo "<div>";
echo "<h4 class=\"font-semibold mb-2\">Contact Us</h4>";
echo "<ul class=\"text-sm text-gray-600 space-y-1\">";
echo "<li>Help & Support</li>";
echo "<li>Partner with us</li>";
echo "<li>Ride with us</li>";
echo "</ul>";
echo "</div>";
echo "<div>";
echo "<h4 class=\"font-semibold mb-2\">Available in</h4>";
echo "<p class=\"text-sm text-gray-600\">Bangalore, Gurgaon, Hyderabad, Delhi, Mumbai, Pune + 67 cities</p>";
echo "</div>";
echo "</div>";
echo "</footer>";
echo "";
echo "<!-- Scroll to Top Button -->";
echo "<button id=\"scrollTopBtn\" class=\"fixed bottom-5 right-5 bg-orange-500 text-white p-3 rounded-full shadow-lg hidden hover:bg-orange-600 transition\">";
echo "↑";
echo "</button>";
echo "";
echo "<!-- Login Modal (Phone + OTP + Registration) -->";
echo "<div id=\"loginModal\" class=\"fixed inset-0 bg-black/50 hidden items-center justify-center z-50\">";
echo "<div class=\"bg-white rounded-xl w-11/12 max-w-sm p-6 shadow-lg\">";
echo "<h2 id=\"loginTitle\" class=\"text-2xl font-bold mb-1\">Login</h2>";
echo "<p class=\"text-sm text-gray-600 mb-4\">or <a id=\"toggleFormLink\" href=\"#\" class=\"text-orange-600 font-semibold\">create an account</a></p>";
echo "";
echo "<!-- Phone step -->";
echo "<div id=\"phoneStep\">";
echo "<label class=\"block text-sm font-medium mb-1\">Phone number</label>";
echo "<input id=\"phoneInput\" type=\"tel\" inputmode=\"numeric\" pattern=\"\\\\d{10}\" class=\"w-full border rounded-md px-3 py-3\" placeholder=\"\" />";
echo "<button id=\"sendOtpBtn\" class=\"mt-4 w-full bg-orange-600 hover:bg-orange-700 text-white px-4 py-3 rounded-md\">LOGIN</button>";
echo "<p class=\"mt-3 text-xs text-gray-600\">By clicking on Login, I accept the <a href=\"#\" class=\"underline\">Terms & Conditions</a> & <a href=\"#\" class=\"underline\">Privacy Policy</a></p>";
echo "<button id=\"loginCancel\" class=\"mt-3 w-full border px-4 py-2 rounded-md hover:bg-gray-50\">Cancel</button>";
echo "</div>";
echo "";
echo "<!-- OTP step -->";
echo "<div id=\"otpStep\" class=\"hidden\">";
echo "<p class=\"text-sm text-gray-700\">We sent a 6-digit code to <span id=\"maskedPhone\" class=\"font-semibold\"></span></p>";
echo "<label class=\"block text-sm font-medium mb-1 mt-3\">Enter OTP</label>";
echo "<input id=\"otpInput\" type=\"text\" inputmode=\"numeric\" maxlength=\"6\" class=\"w-full border rounded-md px-3 py-3 tracking-widest text-center\" placeholder=\"______\" />";
echo "<button id=\"verifyOtpBtn\" class=\"mt-4 w-full bg-orange-600 hover:bg-orange-700 text-white px-4 py-3 rounded-md\">Verify & Continue</button>";
echo "<button id=\"changeNumberBtn\" class=\"mt-3 w-full border px-4 py-2 rounded-md hover:bg-gray-50\">Use a different number</button>";
echo "</div>";
echo "";
echo "<!-- Registration step -->";
echo "<div id=\"registerStep\" class=\"hidden\">";
echo "<div class=\"space-y-4\">";
echo "<div>";
echo "<label class=\"block text-sm font-medium mb-1\">Full Name</label>";
echo "<input id=\"nameInput\" type=\"text\" class=\"w-full border rounded-md px-3 py-3\" placeholder=\"Enter your full name\" />";
echo "</div>";
echo "<div>";
echo "<label class=\"block text-sm font-medium mb-1\">Email Address</label>";
echo "<input id=\"emailInput\" type=\"email\" class=\"w-full border rounded-md px-3 py-3\" placeholder=\"Enter your email\" />";
echo "</div>";
echo "<div>";
echo "<label class=\"block text-sm font-medium mb-1\">Phone number</label>";
echo "<input id=\"regPhoneInput\" type=\"tel\" inputmode=\"numeric\" pattern=\"\\\\d{10}\" class=\"w-full border rounded-md px-3 py-3\" placeholder=\"Enter 10-digit phone number\" />";
echo "</div>";
echo "</div>";
echo "<button id=\"createAccountBtn\" class=\"mt-4 w-full bg-orange-600 hover:bg-orange-700 text-white px-4 py-3 rounded-md\">CREATE ACCOUNT</button>";
echo "<p class=\"mt-3 text-xs text-gray-600\">By creating an account, I accept the <a href=\"#\" class=\"underline\">Terms & Conditions</a> & <a href=\"#\" class=\"underline\">Privacy Policy</a></p>";
echo "<button id=\"regCancel\" class=\"mt-3 w-full border px-4 py-2 rounded-md hover:bg-gray-50\">Cancel</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<script>";
echo "// Filter functionality";
echo "const filterBtn = document.getElementById('filterBtn');";
echo "const sortBtn = document.getElementById('sortBtn');";
echo "const filterModal = document.getElementById('filterModal');";
echo "const sortModal = document.getElementById('sortModal');";
echo "const applyFilters = document.getElementById('applyFilters');";
echo "const clearFilters = document.getElementById('clearFilters');";
echo "const applySort = document.getElementById('applySort');";
echo "const filterChips = document.querySelectorAll('.filter-chip');";
echo "const restaurantsGrid = document.getElementById('restaurantsGrid');";
echo "const restaurantCards = document.querySelectorAll('.restaurant-card');";
echo "";
echo "// Active filters";
echo "let activeFilters = {";
echo "'fast-delivery': false,";
echo "'new': false,";
echo "'rating': false,";
echo "'veg': false,";
echo "'offers': false,";
echo "'price-low': false,";
echo "'price-mid': false,";
echo "'price-high': false";
echo "};";
echo "";
echo "let currentSort = 'relevance';";
echo "";
echo "// Open filter modal";
echo "filterBtn.addEventListener('click', function() {";
echo "filterModal.classList.remove('hidden');";
echo "});";
echo "";
echo "// Open sort modal";
echo "sortBtn.addEventListener('click', function() {";
echo "sortModal.classList.remove('hidden');";
echo "});";
echo "";
echo "// Close modals when clicking outside";
echo "[filterModal, sortModal].forEach(modal => {";
echo "modal.addEventListener('click', function(e) {";
echo "if (e.target === modal) {";
echo "modal.classList.add('hidden');";
echo "}";
echo "});";
echo "});";
echo "";
echo "// Apply filters";
echo "applyFilters.addEventListener('click', function() {";
echo "// Update active filters from checkboxes";
echo "document.querySelectorAll('.filter-checkbox').forEach(checkbox => {";
echo "const filter = checkbox.getAttribute('data-filter');";
echo "activeFilters[filter] = checkbox.checked;";
echo "});";
echo "";
echo "// Update active filters from radio buttons";
echo "document.querySelectorAll('.filter-radio:checked').forEach(radio => {";
echo "const filter = radio.getAttribute('data-filter');";
echo "// Reset all price filters";
echo "Object.keys(activeFilters).forEach(key => {";
echo "if (key.startsWith('price-')) {";
echo "activeFilters[key] = false;";
echo "}";
echo "});";
echo "activeFilters[filter] = true;";
echo "});";
echo "";
echo "// Update chip appearance";
echo "updateFilterChips();";
echo "";
echo "// Apply filters to restaurants";
echo "applyRestaurantFilters();";
echo "";
echo "// Close modal";
echo "filterModal.classList.add('hidden');";
echo "});";
echo "";
echo "// Apply sorting";
echo "applySort.addEventListener('click', function() {";
echo "const selectedSort = document.querySelector('input[name=\"sort\"]:checked').value;";
echo "currentSort = selectedSort;";
echo "";
echo "// Apply sorting to restaurants";
echo "applyRestaurantSorting();";
echo "";
echo "// Close modal";
echo "sortModal.classList.add('hidden');";
echo "});";
echo "";
echo "// Clear all filters";
echo "clearFilters.addEventListener('click', function() {";
echo "// Reset all checkboxes";
echo "document.querySelectorAll('.filter-checkbox').forEach(checkbox => {";
echo "checkbox.checked = false;";
echo "});";
echo "";
echo "// Reset all radio buttons";
echo "document.querySelectorAll('.filter-radio').forEach(radio => {";
echo "radio.checked = false;";
echo "});";
echo "";
echo "// Reset active filters";
echo "Object.keys(activeFilters).forEach(key => {";
echo "activeFilters[key] = false;";
echo "});";
echo "";
echo "// Update chip appearance";
echo "updateFilterChips();";
echo "";
echo "// Reset restaurant display";
echo "restaurantCards.forEach(card => {";
echo "card.style.display = 'block';";
echo "});";
echo "});";
echo "";
echo "// Filter chip click handlers";
echo "filterChips.forEach(chip => {";
echo "chip.addEventListener('click', function() {";
echo "const filter = this.getAttribute('data-filter');";
echo "";
echo "// Toggle the filter";
echo "activeFilters[filter] = !activeFilters[filter];";
echo "";
echo "// Update chip appearance";
echo "updateFilterChips();";
echo "";
echo "// Apply filters to restaurants";
echo "applyRestaurantFilters();";
echo "});";
echo "});";
echo "";
echo "// Update filter chips appearance based on active filters";
echo "function updateFilterChips() {";
echo "filterChips.forEach(chip => {";
echo "const filter = chip.getAttribute('data-filter');";
echo "if (activeFilters[filter]) {";
echo "chip.classList.add('active-filter');";
echo "} else {";
echo "chip.classList.remove('active-filter');";
echo "}";
echo "});";
echo "}";
echo "";
echo "// Apply filters to restaurants";
echo "function applyRestaurantFilters() {";
echo "restaurantCards.forEach(card => {";
echo "let shouldShow = true;";
echo "";
echo "// Check each active filter";
echo "if (activeFilters['fast-delivery']) {";
echo "const deliveryTime = parseInt(card.getAttribute('data-delivery-time'));";
echo "if (deliveryTime > 30) shouldShow = false;";
echo "}";
echo "";
echo "if (activeFilters['new']) {";
echo "const isNew = card.getAttribute('data-new') === 'true';";
echo "if (!isNew) shouldShow = false;";
echo "}";
echo "";
echo "if (activeFilters['rating']) {";
echo "const rating = parseFloat(card.getAttribute('data-rating'));";
echo "if (rating < 4.0) shouldShow = false;";
echo "}";
echo "";
echo "if (activeFilters['veg']) {";
echo "const isVeg = card.getAttribute('data-veg') === 'true';";
echo "if (!isVeg) shouldShow = false;";
echo "}";
echo "";
echo "if (activeFilters['offers']) {";
echo "const hasOffers = card.getAttribute('data-offers') === 'true';";
echo "if (!hasOffers) shouldShow = false;";
echo "}";
echo "";
echo "if (activeFilters['price-low']) {";
echo "const price = parseInt(card.getAttribute('data-price'));";
echo "if (price >= 300) shouldShow = false;";
echo "}";
echo "";
echo "if (activeFilters['price-mid']) {";
echo "const price = parseInt(card.getAttribute('data-price'));";
echo "if (price < 300 || price > 600) shouldShow = false;";
echo "}";
echo "";
echo "if (activeFilters['price-high']) {";
echo "const price = parseInt(card.getAttribute('data-price'));";
echo "if (price <= 600) shouldShow = false;";
echo "}";
echo "";
echo "// Show or hide the card based on filters";
echo "card.style.display = shouldShow ? 'block' : 'none';";
echo "});";
echo "";
echo "// Apply sorting after filtering";
echo "applyRestaurantSorting();";
echo "}";
echo "";
echo "// Apply sorting to restaurants";
echo "function applyRestaurantSorting() {";
echo "const visibleCards = Array.from(restaurantCards).filter(card =>";
echo "card.style.display !== 'none'";
echo ");";
echo "";
echo "// Sort based on current sort option";
echo "visibleCards.sort((a, b) => {";
echo "switch(currentSort) {";
echo "case 'delivery-time':";
echo "return parseInt(a.getAttribute('data-delivery-time')) - parseInt(b.getAttribute('data-delivery-time'));";
echo "case 'rating':";
echo "return parseFloat(b.getAttribute('data-rating')) - parseFloat(a.getAttribute('data-rating'));";
echo "case 'cost-low':";
echo "return parseInt(a.getAttribute('data-price')) - parseInt(b.getAttribute('data-price'));";
echo "case 'cost-high':";
echo "return parseInt(b.getAttribute('data-price')) - parseInt(a.getAttribute('data-price'));";
echo "default: // relevance";
echo "return 0;";
echo "}";
echo "});";
echo "";
echo "// Reorder the grid";
echo "visibleCards.forEach(card => {";
echo "restaurantsGrid.appendChild(card);";
echo "});";
echo "}";
echo "";
echo "// Dark mode toggle functionality";
echo "const darkModeToggle = document.getElementById('darkModeToggle');";
echo "const prefersDarkScheme = window.matchMedia('(prefers-color-scheme: dark)');";
echo "";
echo "// Check for saved theme preference or use system preference";
echo "const currentTheme = localStorage.getItem('theme') ||";
echo "(prefersDarkScheme.matches ? 'dark' : 'light');";
echo "";
echo "// Apply the theme";
echo "if (currentTheme === 'dark') {";
echo "document.body.classList.add('dark-mode');";
echo "darkModeToggle.textContent = '☀️';";
echo "}";
echo "";
echo "// Toggle theme on button click";
echo "darkModeToggle.addEventListener('click', function() {";
echo "let theme = 'light';";
echo "if (!document.body.classList.contains('dark-mode')) {";
echo "document.body.classList.add('dark-mode');";
echo "darkModeToggle.textContent = '☀️';";
echo "theme = 'dark';";
echo "} else {";
echo "document.body.classList.remove('dark-mode');";
echo "darkModeToggle.textContent = '🌙';";
echo "theme = 'light';";
echo "}";
echo "localStorage.setItem('theme', theme);";
echo "});";
echo "";
echo "// Voice search functionality";
echo "const voiceSearchBtn = document.getElementById('voiceSearchBtn');";
echo "const voiceStatus = document.getElementById('voiceStatus');";
echo "const searchInput = document.getElementById('searchInput');";
echo "";
echo "// Check if browser supports speech recognition";
echo "const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;";
echo "let recognition = null;";
echo "";
echo "if (SpeechRecognition) {";
echo "recognition = new SpeechRecognition();";
echo "recognition.continuous = false;";
echo "recognition.lang = 'en-US';";
echo "";
echo "recognition.onstart = function() {";
echo "voiceSearchBtn.classList.add('listening');";
echo "voiceStatus.classList.remove('hidden');";
echo "};";
echo "";
echo "recognition.onresult = function(event) {";
echo "const transcript = event.results[0][0].transcript;";
echo "searchInput.value = transcript;";
echo "};";
echo "";
echo "recognition.onerror = function(event) {";
echo "console.error('Speech recognition error', event.error);";
echo "voiceStatus.classList.add('hidden');";
echo "voiceSearchBtn.classList.remove('listening');";
echo "};";
echo "";
echo "recognition.onend = function() {";
echo "voiceStatus.classList.add('hidden');";
echo "voiceSearchBtn.classList.remove('listening');";
echo "};";
echo "";
echo "voiceSearchBtn.addEventListener('click', function() {";
echo "if (voiceSearchBtn.classList.contains('listening')) {";
echo "recognition.stop();";
echo "} else {";
echo "try {";
echo "recognition.start();";
echo "} catch (err) {";
echo "console.error('Speech recognition start failed', err);";
echo "voiceStatus.textContent = 'Microphone not available';";
echo "voiceStatus.classList.remove('hidden');";
echo "setTimeout(() => {";
echo "voiceStatus.classList.add('hidden');";
echo "}, 3000);";
echo "}";
echo "}";
echo "});";
echo "} else {";
echo "// Browser doesn't support speech recognition";
echo "voiceSearchBtn.addEventListener('click', function() {";
echo "voiceStatus.textContent = 'Voice search not supported in your browser';";
echo "voiceStatus.classList.remove('hidden');";
echo "setTimeout(() => {";
echo "voiceStatus.classList.add('hidden');";
echo "}, 3000);";
echo "});";
echo "}";
echo "";
echo "// Profile menu toggle";
echo "document.getElementById('profileBtn').addEventListener('click', function(e){";
echo "e.stopPropagation();";
echo "document.getElementById('profileMenu').classList.toggle('hidden');";
echo "});";
echo "document.addEventListener('click', function(){";
echo "document.getElementById('profileMenu').classList.add('hidden');";
echo "});";
echo "";
echo "// Scroll-to-top button";
echo "const scrollBtn = document.getElementById('scrollTopBtn');";
echo "";
echo "window.onscroll = function() {";
echo "if (document.body.scrollTop > 200 || document.documentElement.scrollTop > 200) {";
echo "scrollBtn.classList.remove('hidden');";
echo "} else {";
echo "scrollBtn.classList.add('hidden');";
echo "}";
echo "};";
echo "";
echo "scrollBtn.addEventListener('click', function() {";
echo "window.scrollTo({ top: 0, behavior: 'smooth' });";
echo "});";
echo "";
echo "// Simple auth state using localStorage";
echo "const userNameLabel = document.getElementById('userNameLabel');";
echo "const signInBtn = document.getElementById('signInBtn');";
echo "const logoutBtn = document.getElementById('logoutBtn');";
echo "const loginModal = document.getElementById('loginModal');";
echo "const loginCancel = document.getElementById('loginCancel');";
echo "const phoneStep = document.getElementById('phoneStep');";
echo "const otpStep = document.getElementById('otpStep');";
echo "const phoneInput = document.getElementById('phoneInput');";
echo "const sendOtpBtn = document.getElementById('sendOtpBtn');";
echo "const otpInput = document.getElementById('otpInput');";
echo "const verifyOtpBtn = document.getElementById('verifyOtpBtn');";
echo "const changeNumberBtn = document.getElementById('changeNumberBtn');";
echo "const maskedPhone = document.getElementById('maskedPhone');";
echo "";
echo "function applyUserUI() {";
echo "const savedName = localStorage.getItem('userName');";
echo "if (savedName && savedName.trim()) {";
echo "userNameLabel.textContent = savedName;";
echo "if (signInBtn) signInBtn.classList.add('hidden');";
echo "} else {";
echo "userNameLabel.textContent = 'User';";
echo "if (signInBtn) signInBtn.classList.remove('hidden');";
echo "}";
echo "}";
echo "";
echo "applyUserUI();";
echo "";
echo "function openLogin() { loginModal.classList.remove('hidden'); loginModal.classList.add('flex'); }";
echo "function closeLogin() { loginModal.classList.add('hidden'); loginModal.classList.remove('flex'); }";
echo "";
echo "if (signInBtn) signInBtn.addEventListener('click', function(){";
echo "// reset";
echo "phoneInput.value = '';";
echo "otpInput.value = '';";
echo "phoneStep.classList.remove('hidden');";
echo "otpStep.classList.add('hidden');";
echo "openLogin();";
echo "});";
echo "loginCancel.addEventListener('click', closeLogin);";
echo "";
echo "// Fake OTP flow";
echo "let generatedOtp = '';";
echo "let currentPhone = '';";
echo "";
echo "sendOtpBtn.addEventListener('click', function(){";
echo "const phone = (phoneInput.value || '').trim();";
echo "if (!/^\\d{10}$/.test(phone)) { alert('Please enter a valid 10-digit phone number'); return; }";
echo "currentPhone = phone;";
echo "generatedOtp = Math.floor(100000 + Math.random() * 900000).toString();";
echo "// In real app, send this to server/SMS provider. For demo, show it in console.";
echo "console.log('Demo OTP:', generatedOtp);";
echo "maskedPhone.textContent = phone.replace(/^(\\d{2})(\\d{6})(\\d{2})$/, '$1******$3');";
echo "phoneStep.classList.add('hidden');";
echo "otpStep.classList.remove('hidden');";
echo "otpInput.focus();";
echo "});";
echo "";
echo "changeNumberBtn.addEventListener('click', function(){";
echo "otpStep.classList.add('hidden');";
echo "phoneStep.classList.remove('hidden');";
echo "phoneInput.focus();";
echo "});";
echo "";
echo "verifyOtpBtn.addEventListener('click', function(){";
echo "// Accept any OTP and log in as the demo user name";
echo "const displayName = 'juna elsa mathew';";
echo "localStorage.setItem('userName', displayName);";
echo "localStorage.setItem('userPhone', currentPhone);";
echo "closeLogin();";
echo "applyUserUI();";
echo "});";
echo "";
echo "logoutBtn.addEventListener('click', function(){";
echo "localStorage.removeItem('userName');";
echo "localStorage.removeItem('userEmail');";
echo "applyUserUI();";
echo "document.getElementById('profileMenu').classList.add('hidden');";
echo "});";
echo "";
echo "// Ensure any missing/broken restaurant images show a reliable fallback";
echo "(function attachImageFallbacks(){";
echo "const fallbackSrc = 'kfc.png'; // local, guaranteed to load";
echo "const images = document.querySelectorAll('.card-img');";
echo "images.forEach(function(image){";
echo "image.addEventListener('error', function(){";
echo "if (image.getAttribute('src') !== fallbackSrc) {";
echo "image.setAttribute('src', fallbackSrc);";
echo "}";
echo "}, { once: false });";
echo "});";
echo "})();";
echo "";
echo "// Navigate to restaurant details on card click";
echo "(function attachRestaurantClicks(){";
echo "const cards = document.querySelectorAll('.restaurant-card');";
echo "cards.forEach(function(card){";
echo "card.addEventListener('click', function(){";
echo "const id = card.getAttribute('data-restaurant-id');";
echo "const name = card.querySelector('h3')?.textContent || '';";
echo "const image = card.querySelector('img')?.getAttribute('src') || '';";
echo "localStorage.setItem('selectedRestaurant', JSON.stringify({ id, name, image }));";
echo "window.location.href = 'restaurant-details.html';";
echo "});";
echo "});";
echo "})();";
echo "</script>";
echo "</body>";
echo "</html>";
?>