<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"utf-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
echo "<title>KFC - Menu</title>";
echo "<script src=\"https://cdn.tailwindcss.com\"></script>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />";
echo "</head>";
echo "<body class=\"bg-gray-50\">";
echo "<header class=\"bg-white shadow-sm p-4 fixed top-0 w-full z-50\">";
echo "<div class=\"max-w-4xl mx-auto flex items-center justify-between\">";
echo "<a href=\"swiggyhome.php\" class=\"flex items-center gap-2\">";
echo "<div class=\"w-8 h-8 bg-orange-500 rounded-full flex items-center justify-center text-white font-bold\">S</div>";
echo "<span class=\"font-semibold\">Swiggy</span>";
echo "</a>";
echo "<h1 class=\"text-lg font-semibold\">KFC - Menu</h1>";
echo "<div class=\"flex items-center gap-4\">";
echo "<a href=\"help.php\" class=\"flex items-center gap-2 px-3 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition text-sm\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "<span class=\"hidden sm:inline\">Help</span>";
echo "</a>";
echo "<div class=\"relative\">";
echo "<button id=\"cartBtn\" class=\"flex items-center\">";
echo "<i class=\"fas fa-shopping-cart text-xl\"></i>";
echo "<span id=\"cartCount\" class=\"ml-2 bg-orange-600 text-white rounded-full px-2 py-1 text-sm\">0</span>";
echo "</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</header>";
echo "";
echo "<!-- Cart Sidebar -->";
echo "<div id=\"cartSidebar\" class=\"fixed right-0 top-0 h-full w-80 bg-white shadow-lg transform translate-x-full transition-transform duration-300 ease-in-out z-50\">";
echo "<div class=\"p-4 h-full overflow-y-auto\">";
echo "<div class=\"flex justify-between items-center mb-4\">";
echo "<h2 class=\"text-xl font-bold\">Your Cart</h2>";
echo "<button id=\"closeCart\" class=\"text-gray-500\"><i class=\"fas fa-times\"></i></button>";
echo "</div>";
echo "<div id=\"cartItems\" class=\"space-y-4 mb-6\"></div>";
echo "<div class=\"mt-auto border-t pt-4\">";
echo "<div class=\"flex justify-between mb-2\">";
echo "<span>Subtotal:</span>";
echo "<span id=\"cartTotal\">₹0</span>";
echo "</div>";
echo "<button id=\"checkoutBtn\" class=\"w-full bg-orange-600 text-white py-2 rounded-md\">Checkout</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<main class=\"max-w-4xl mx-auto pt-20 px-4 pb-8\">";
echo "<!-- Restaurant Details -->";
echo "<section class=\"bg-white rounded-2xl shadow-sm p-6 mb-6\">";
echo "<div class=\"flex gap-4 items-start mb-4\">";
echo "<img id=\"restHero\" src=\"https://b.zmtcdn.com/data/pictures/chains/9/65279/93776f3249312397e2c2ba274b4812ec.jpg?fit=around|960:500&crop=960:500;*,*\" alt=\"KFC\" class=\"w-32 h-24 object-cover rounded-lg\"/>";
echo "<div class=\"flex-1\">";
echo "<h2 id=\"restName\" class=\"text-2xl font-bold\">KFC</h2>";
echo "<p id=\"restCuisines\" class=\"text-sm text-gray-500\">Burgers, Fast Food, Rolls & Wraps</p>";
echo "<p id=\"restLocation\" class=\"text-sm text-gray-500\">Kanjirappally</p>";
echo "</div>";
echo "</div>";
echo "<div class=\"flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-4\">";
echo "<div class=\"flex gap-4 text-sm\">";
echo "<div class=\"text-center\">";
echo "<div class=\"font-bold text-green-600\" id=\"restRating\">⭐ 3.9</div>";
echo "<div class=\"text-gray-500\">Dining Ratings</div>";
echo "</div>";
echo "<div class=\"text-center\">";
echo "<div class=\"font-bold text-green-600\">⭐ 4.2</div>";
echo "<div class=\"text-gray-500\">Delivery Ratings (664)</div>";
echo "</div>";
echo "</div>";
echo "<div class=\"flex gap-2 text-sm\">";
echo "<span class=\"bg-green-100 text-green-800 px-2 py-1 rounded\">Open Now</span>";
echo "<span>8am - 11pm (Today)</span>";
echo "</div>";
echo "</div>";
echo "<div class=\"flex justify-between items-center text-sm mb-4\">";
echo "<div>";
echo "<div id=\"restCost\">₹400 for two</div>";
echo "<div id=\"restPhone\" class=\"text-gray-500\"><i class=\"fas fa-phone mr-1\"></i>+91 9876543210</div>";
echo "</div>";
echo "<div class=\"flex gap-4\">";
echo "<button id=\"restDirections\" class=\"text-blue-500 flex items-center\"><i class=\"fas fa-directions mr-1\"></i>Directions</button>";
echo "<button id=\"shareBtn\" class=\"text-gray-500 flex items-center\"><i class=\"fas fa-share mr-1\"></i>Share</button>";
echo "<button id=\"reviewsBtn\" class=\"text-gray-500 flex items-center\"><i class=\"fas fa-star mr-1\"></i>Reviews</button>";
echo "</div>";
echo "</div>";
echo "<div id=\"restOverview\" class=\"text-gray-600 text-sm\">KFC is an American fast food restaurant chain headquartered in Louisville, Kentucky.</div>";
echo "</section>";
echo "";
echo "<!-- Menu Items -->";
echo "<section class=\"bg-white rounded-2xl shadow-sm p-6\">";
echo "<h3 class=\"text-xl font-bold mb-6\">Menu</h3>";
echo "<div id=\"menuItems\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\"></div>";
echo "</section>";
echo "</main>";
echo "";
echo "<script>";
echo "const restBadge = 'KFC';";
echo "const menuItems = [";
echo "{ id: '1', name: 'Classic Chicken Zinger Burger', description: 'Crispy chicken fillet burger', price: 209, image: 'https://media.istockphoto.com/id/1421102783/photo/classic-zinger-burger-meal-isolated-on-wooden-board-side-view-on-grey-background-fastfood.jpg?s=612x612&w=0&k=20&c=JMuTyUYpnbIEgH6Qj6Iz7rY2KmBp6hOFrDsC_PM1rmY=' },";
echo "{ id: '2', name: 'Spicy Chicken Zinger Burger', description: 'Spicy version of zinger', price: 229, image: 'https://static.vecteezy.com/system/resources/previews/048/712/453/non_2x/zinger-burger-mania-a-guide-to-making-the-perfect-spicy-chicken-sandwich-free-png.png' },";
echo "{ id: '3', name: 'Chicken Krisper Burger', description: 'Crispy chicken patty', price: 114, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1467LfOUeWl6kDaOFjni_vFlHREz0ieoBRg&s' },";
echo "{ id: '4', name: 'Veg Krisper Burger', description: 'Vegetarian crispy burger', price: 79, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuHjOJk9Kt2XbtY86zqb3bMxsx-iXVLrAbMQ&s' },";
echo "{ id: '5', name: 'Chicken Bucket', description: '6 pieces fried chicken', price: 500, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvsBWoprlFxU4tJKAj_xv-bwi8fX3H7xEa5Q&s' },";
echo "{ id: '6', name: 'French Fries', description: 'Crispy seasoned fries', price: 60, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5Wn8kqLfBzqQ7gBGuNClgIudF4lz0NlMMNg&s' }";
echo "];";
echo "";
echo "function renderMenu() {";
echo "const menuItemsEl = document.getElementById('menuItems');";
echo "menuItemsEl.innerHTML = menuItems.map(item => `";
echo "<div class=\"border rounded-2xl p-4 bg-white shadow-sm\">";
echo "<img src=\"${item.image}\" alt=\"${item.name}\" class=\"w-full h-40 object-cover rounded-md\"/>";
echo "<h4 class=\"mt-3 font-semibold\">${item.name}</h4>";
echo "<p class=\"text-sm text-gray-500\">${item.description}</p>";
echo "<div class=\"mt-3 text-orange-500 font-semibold\">₹${item.price}</div>";
echo "<button onclick=\"addToCart('${item.id}')\" class=\"mt-3 w-full bg-orange-500 text-white px-4 py-2 rounded hover:bg-orange-600 transition\">Add to Cart</button>";
echo "</div>";
echo "`).join('');";
echo "}";
echo "";
echo "function addToCart(itemId) {";
echo "const item = menuItems.find(i => i.id === itemId);";
echo "if (item) {";
echo "let globalCart = [];";
echo "try {";
echo "globalCart = JSON.parse(localStorage.getItem('cart') || '[]');";
echo "} catch { globalCart = []; }";
echo "const existing = globalCart.find(c => c.id === itemId && c.badge === restBadge);";
echo "if (existing) {";
echo "existing.qty += 1;";
echo "} else {";
echo "globalCart.push({ ...item, title: item.name, qty: 1, badge: restBadge });";
echo "}";
echo "localStorage.setItem('cart', JSON.stringify(globalCart));";
echo "updateCartUI();";
echo "document.getElementById('cartSidebar').classList.remove('translate-x-full');";
echo "}";
echo "}";
echo "";
echo "function updateCartUI() {";
echo "let globalCart = [];";
echo "try {";
echo "globalCart = JSON.parse(localStorage.getItem('cart') || '[]');";
echo "} catch { globalCart = []; }";
echo "const restaurantCart = globalCart.filter(item => item.badge === restBadge);";
echo "const cartCount = document.getElementById('cartCount');";
echo "const cartItemsEl = document.getElementById('cartItems');";
echo "const cartTotalEl = document.getElementById('cartTotal');";
echo "const totalItems = restaurantCart.reduce((sum, item) => sum + item.qty, 0);";
echo "const totalPrice = restaurantCart.reduce((sum, item) => sum + (item.price * item.qty), 0);";
echo "";
echo "cartCount.textContent = totalItems;";
echo "cartTotalEl.textContent = `₹${totalPrice}`;";
echo "";
echo "cartItemsEl.innerHTML = restaurantCart.map(item => `";
echo "<div class=\"flex justify-between items-center p-2 border-b\">";
echo "<div class=\"flex items-center gap-2\">";
echo "<img src=\"${item.image}\" alt=\"${item.name}\" class=\"w-12 h-12 object-cover rounded\"/>";
echo "<div>";
echo "<div class=\"font-medium\">${item.title}</div>";
echo "<div class=\"text-sm text-gray-500\">₹${item.price} x ${item.qty}</div>";
echo "</div>";
echo "</div>";
echo "<button onclick=\"removeFromCart('${item.id}')\" class=\"text-red-500\"><i class=\"fas fa-trash\"></i></button>";
echo "</div>";
echo "`).join('');";
echo "}";
echo "";
echo "function removeFromCart(itemId) {";
echo "let globalCart = [];";
echo "try {";
echo "globalCart = JSON.parse(localStorage.getItem('cart') || '[]');";
echo "} catch { globalCart = []; }";
echo "const index = globalCart.findIndex(c => c.id === itemId && c.badge === restBadge);";
echo "if (index > -1) {";
echo "if (globalCart[index].qty > 1) {";
echo "globalCart[index].qty -= 1;";
echo "} else {";
echo "globalCart.splice(index, 1);";
echo "}";
echo "localStorage.setItem('cart', JSON.stringify(globalCart));";
echo "updateCartUI();";
echo "}";
echo "}";
echo "";
echo "// Event listeners";
echo "document.getElementById('cartBtn').addEventListener('click', () => {";
echo "document.getElementById('cartSidebar').classList.toggle('translate-x-full');";
echo "});";
echo "";
echo "document.getElementById('closeCart').addEventListener('click', () => {";
echo "document.getElementById('cartSidebar').classList.add('translate-x-full');";
echo "});";
echo "";
echo "document.getElementById('checkoutBtn').addEventListener('click', () => {";
echo "let globalCart = [];";
echo "try {";
echo "globalCart = JSON.parse(localStorage.getItem('cart') || '[]');";
echo "} catch { globalCart = []; }";
echo "const restaurantCart = globalCart.filter(item => item.badge === restBadge);";
echo "if (restaurantCart.length === 0) {";
echo "alert('Cart is empty');";
echo "return;";
echo "}";
echo "window.location.href = 'payment.php';";
echo "});";
echo "";
echo "document.getElementById('restDirections').addEventListener('click', () => {";
echo "window.open('https://maps.google.com/?q=KFC+Kanjirappally', '_blank');";
echo "});";
echo "";
echo "document.getElementById('restPhone').addEventListener('click', () => {";
echo "window.location.href = 'tel:+919876543210';";
echo "});";
echo "";
echo "document.getElementById('shareBtn').addEventListener('click', () => {";
echo "if (navigator.share) {";
echo "navigator.share({ title: 'KFC Menu', url: window.location.href });";
echo "} else {";
echo "alert('Share this page: ' + window.location.href);";
echo "}";
echo "});";
echo "";
echo "document.getElementById('reviewsBtn').addEventListener('click', () => {";
echo "alert('Reviews section - Coming soon!');";
echo "});";
echo "";
echo "// Initialize";
echo "document.addEventListener('DOMContentLoaded', () => {";
echo "renderMenu();";
echo "updateCartUI();";
echo "});";
echo "</script>";
echo "</body>";
echo "</html>";
?>