<?php
echo "<!doctype html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"utf-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
echo "<title>Login</title>";
echo "<script src=\"https://cdn.tailwindcss.com\"></script>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />";
echo "<style>";
echo ".card { max-width: 560px; }";
echo ".brand-illustration {";
echo "width: 140px; height: 140px; border-radius: 9999px;";
echo "display: flex; align-items: center; justify-content: center;";
echo "background: #fff7ed; /* orange-50 */";
echo "box-shadow: inset 0 0 0 10px #ffedd5; /* orange-100 ring */";
echo "}";
echo ".field:focus { outline: none; box-shadow: 0 0 0 3px rgba(249,115,22,.25); }";
echo ".form-toggle { color: #f97316; font-weight: 600; cursor: pointer; }";
echo ".form-toggle:hover { text-decoration: underline; }";
echo ".form-container { transition: all 0.3s ease; }";
echo ".hidden-form { display: none; }";
echo "</style>";
echo "<style>";
echo ":root { --bg:#ffffff; --text:#111827; --muted:#6b7280; --panel:#ffffff; --ring:#e5e7eb; }";
echo ".dark :root, .dark { --bg:#0f172a; --text:#e5e7eb; --muted:#94a3b8; --panel:#111827; --ring:#1f2937; }";
echo "body { background-color: var(--bg); color: var(--text); }";
echo ".dark .brand-illustration{ box-shadow: inset 0 0 0 10px #1f2937; background:#0b1220; }";
echo ".field{ background: var(--panel); color: var(--text); border-color: var(--ring); }";
echo "</style>";
echo "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">";
echo "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>";
echo "<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">";
echo "<style> body { font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, 'Helvetica Neue', Arial, 'Noto Sans', 'Apple Color Emoji', 'Segoe UI Emoji'; } </style>";
echo "<script>";
echo "function validatePhone(e){";
echo "const input = document.getElementById('phone');";
echo "const val = input.value.trim();";
echo "if(!/^\\d{10}$/.test(val)){";
echo "e.preventDefault();";
echo "alert('Please enter a valid 10-digit phone number');";
echo "input.focus();";
echo "return false;";
echo "}";
echo "}";
echo "";
echo "function validateRegistration(e){";
echo "const name = document.getElementById('name');";
echo "const email = document.getElementById('email');";
echo "const regPhone = document.getElementById('reg-phone');";
echo "";
echo "if(name.value.trim() === ''){";
echo "e.preventDefault();";
echo "alert('Please enter your name');";
echo "name.focus();";
echo "return false;";
echo "}";
echo "";
echo "if(email.value.trim() === '' || !email.value.includes('@')){";
echo "e.preventDefault();";
echo "alert('Please enter a valid email address');";
echo "email.focus();";
echo "return false;";
echo "}";
echo "";
echo "if(!/^\\d{10}$/.test(regPhone.value.trim())){";
echo "e.preventDefault();";
echo "alert('Please enter a valid 10-digit phone number');";
echo "regPhone.focus();";
echo "return false;";
echo "}";
echo "}";
echo "";
echo "function toggleForm() {";
echo "const loginForm = document.getElementById('login-form');";
echo "const registerForm = document.getElementById('register-form');";
echo "const title = document.getElementById('form-title');";
echo "const toggleText = document.getElementById('form-toggle-text');";
echo "";
echo "if (loginForm.classList.contains('hidden-form')) {";
echo "// Switch to login";
echo "loginForm.classList.remove('hidden-form');";
echo "registerForm.classList.add('hidden-form');";
echo "title.textContent = 'Login';";
echo "toggleText.innerHTML = 'or <span class=\"form-toggle\" onclick=\"toggleForm()\">create an account</span>';";
echo "} else {";
echo "// Switch to register";
echo "loginForm.classList.add('hidden-form');";
echo "registerForm.classList.remove('hidden-form');";
echo "title.textContent = 'Create Account';";
echo "toggleText.innerHTML = 'or <span class=\"form-toggle\" onclick=\"toggleForm()\">login to your account</span>';";
echo "}";
echo "}";
echo "</script>";
echo "</head>";
echo "<body class=\"min-h-screen bg-white md:bg-gray-50\">";
echo "<button id=\"dmBtn\" class=\"fixed top-4 right-4 z-50 bg-orange-500 text-white rounded-full w-10 h-10\">🌓</button>";
echo "<main class=\"min-h-screen flex items-start md:items-center justify-center p-6\">";
echo "<section class=\"card w-full bg-white md:rounded-2xl md:shadow-xl md:border border-gray-100 p-8 md:p-10\">";
echo "<!-- Close icon row (optional) -->";
echo "<div class=\"flex items-center justify-between\">";
echo "<div class=\"flex items-center gap-4\">";
echo "<a href=\"swiggyhome.php\" class=\"text-gray-400 hover:text-gray-600\" aria-label=\"Close\">";
echo "<i class=\"fa-solid fa-xmark text-2xl\"></i>";
echo "</a>";
echo "<a href=\"help.php\" class=\"flex items-center gap-2 px-3 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition text-sm\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "<span class=\"hidden sm:inline\">Help</span>";
echo "</a>";
echo "</div>";
echo "<div class=\"brand-illustration\">";
echo "<i class=\"fa-solid fa-burrito text-4xl text-orange-500\"></i>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Title -->";
echo "<h1 id=\"form-title\" class=\"mt-8 text-3xl font-bold tracking-tight\">Login</h1>";
echo "<p id=\"form-toggle-text\" class=\"mt-2 text-gray-600\">or <span class=\"form-toggle\" onclick=\"toggleForm()\">create an account</span></p>";
echo "";
echo "<!-- Divider underline -->";
echo "<div class=\"mt-6 h-[2px] w-10 bg-gray-900\"></div>";
echo "";
echo "<!-- Login form -->";
echo "<form id=\"login-form\" class=\"form-container mt-6\" onsubmit=\"validatePhone(event)\" action=\"#\" method=\"post\">";
echo "<label for=\"phone\" class=\"block text-sm text-gray-700 mb-2\">Phone number</label>";
echo "<input id=\"phone\" name=\"phone\" type=\"tel\" inputmode=\"numeric\" pattern=\"\\d{10}\"";
echo "placeholder=\"\"";
echo "class=\"field w-full border border-gray-300 rounded-md h-14 px-4 text-lg\" />";
echo "";
echo "<button type=\"submit\"";
echo "class=\"mt-6 w-full h-14 bg-orange-600 hover:bg-orange-700 text-white font-semibold rounded-md transition\">";
echo "LOGIN";
echo "</button>";
echo "";
echo "<p class=\"mt-4 text-sm text-gray-600\">";
echo "By clicking on Login, I accept the";
echo "<a href=\"#\" class=\"text-gray-800 underline\">Terms &amp; Conditions</a>";
echo "&amp;";
echo "<a href=\"#\" class=\"text-gray-800 underline\">Privacy Policy</a>";
echo "</p>";
echo "</form>";
echo "";
echo "<!-- Registration form -->";
echo "<form id=\"register-form\" class=\"form-container hidden-form mt-6\" onsubmit=\"validateRegistration(event)\" action=\"#\" method=\"post\">";
echo "<div class=\"space-y-4\">";
echo "<div>";
echo "<label for=\"name\" class=\"block text-sm text-gray-700 mb-2\">Full Name</label>";
echo "<input id=\"name\" name=\"name\" type=\"text\"";
echo "placeholder=\"\"";
echo "class=\"field w-full border border-gray-300 rounded-md h-14 px-4 text-lg\" />";
echo "</div>";
echo "";
echo "<div>";
echo "<label for=\"email\" class=\"block text-sm text-gray-700 mb-2\">Email Address</label>";
echo "<input id=\"email\" name=\"email\" type=\"email\"";
echo "placeholder=\"\"";
echo "class=\"field w-full border border-gray-300 rounded-md h-14 px-4 text-lg\" />";
echo "</div>";
echo "";
echo "<div>";
echo "<label for=\"reg-phone\" class=\"block text-sm text-gray-700 mb-2\">Phone number</label>";
echo "<input id=\"reg-phone\" name=\"reg-phone\" type=\"tel\" inputmode=\"numeric\" pattern=\"\\d{10}\"";
echo "placeholder=\"\"";
echo "class=\"field w-full border border-gray-300 rounded-md h-14 px-4 text-lg\" />";
echo "</div>";
echo "</div>";
echo "";
echo "<button type=\"submit\"";
echo "class=\"mt-6 w-full h-14 bg-orange-600 hover:bg-orange-700 text-white font-semibold rounded-md transition\">";
echo "CREATE ACCOUNT";
echo "</button>";
echo "";
echo "<p class=\"mt-4 text-sm text-gray-600\">";
echo "By clicking on Create Account, I accept the";
echo "<a href=\"#\" class=\"text-gray-800 underline\">Terms &amp; Conditions</a>";
echo "&amp;";
echo "<a href=\"#\" class=\"text-gray-800 underline\">Privacy Policy</a>";
echo "</p>";
echo "</form>";
echo "</section>";
echo "</main>";
echo "";
echo "<script>";
echo "(function(){";
echo "const saved = localStorage.getItem('theme');";
echo "if(saved === 'dark') document.documentElement.classList.add('dark');";
echo "const btn = document.getElementById('dmBtn');";
echo "btn.addEventListener('click', ()=>{";
echo "document.documentElement.classList.toggle('dark');";
echo "localStorage.setItem('theme', document.documentElement.classList.contains('dark') ? 'dark' : 'light');";
echo "});";
echo "})();";
echo "</script>";
echo "</body>";
echo "</html>";
?>