<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
echo "<title>Your Account | Food Delivery</title>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">";
echo "<style>";
echo ":root { --bg:#ffffff; --text:#1a202c; --panel:#ffffff; --ring:#e2e8f0; }";
echo ".dark :root, .dark { --bg:#0f172a; --text:#e5e7eb; --panel:#0b1220; --ring:#1f2937; }";
echo "body { background: var(--bg); color: var(--text); }";
echo "header, .sidebar, .main-content { background: var(--panel); }";
echo ".nav-item { border-color: var(--ring); }";
echo "/* Reset and base styles */";
echo "* {";
echo "box-sizing: border-box;";
echo "margin: 0;";
echo "padding: 0;";
echo "}";
echo "";
echo "body {";
echo "font-family: 'Poppins', sans-serif;";
echo "background-color: #f8fafc;";
echo "margin: 0;";
echo "padding: 0;";
echo "color: #1a202c;";
echo "line-height: 1.6;";
echo "}";
echo "";
echo "a {";
echo "text-decoration: none;";
echo "color: #f97316;";
echo "}";
echo "";
echo "/* Header */";
echo "header {";
echo "background: white;";
echo "padding: 15px 30px;";
echo "box-shadow: 0 2px 4px rgba(0, 0, 0, 0.06);";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "font-size: 1rem;";
echo "font-weight: 600;";
echo "letter-spacing: 0.05em;";
echo "}";
echo "";
echo "header .logo {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "font-weight: 800;";
echo "color: #1e293b;";
echo "font-size: 1.3rem;";
echo "user-select: none;";
echo "}";
echo "";
echo "header .logo img {";
echo "height: 36px;";
echo "width: 36px;";
echo "}";
echo "";
echo "header .nav-right {";
echo "display: flex;";
echo "gap: 25px;";
echo "align-items: center;";
echo "font-weight: 500;";
echo "}";
echo "";
echo "header .nav-right span {";
echo "cursor: pointer;";
echo "color: #475569;";
echo "transition: color 0.2s;";
echo "}";
echo "";
echo "header .nav-right span:hover {";
echo "color: #f97316;";
echo "}";
echo "";
echo ".help-btn {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 6px;";
echo "padding: 8px 12px;";
echo "background: #f97316;";
echo "color: white;";
echo "border-radius: 6px;";
echo "text-decoration: none;";
echo "font-weight: 600;";
echo "transition: all 0.3s ease;";
echo "}";
echo "";
echo ".help-btn:hover {";
echo "background: #ea580c;";
echo "color: white;";
echo "transform: translateY(-1px);";
echo "}";
echo "";
echo "/* Main container */";
echo ".container {";
echo "max-width: 1200px;";
echo "margin: 30px auto;";
echo "padding: 0 20px;";
echo "display: flex;";
echo "gap: 30px;";
echo "}";
echo "";
echo "/* Sidebar */";
echo ".sidebar {";
echo "flex: 1;";
echo "background: white;";
echo "border-radius: 12px;";
echo "box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);";
echo "padding: 25px;";
echo "height: fit-content;";
echo "}";
echo "";
echo ".profile-header {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 15px;";
echo "margin-bottom: 25px;";
echo "}";
echo "";
echo ".profile-avatar {";
echo "width: 60px;";
echo "height: 60px;";
echo "border-radius: 50%;";
echo "background: #f97316;";
echo "display: flex;";
echo "justify-content: center;";
echo "align-items: center;";
echo "color: white;";
echo "font-size: 1.5rem;";
echo "font-weight: 700;";
echo "position: relative;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".profile-avatar img {";
echo "width: 100%;";
echo "height: 100%;";
echo "object-fit: cover;";
echo "}";
echo "";
echo ".profile-info h2 {";
echo "font-size: 1.25rem;";
echo "margin-bottom: 5px;";
echo "}";
echo "";
echo ".profile-info p {";
echo "color: #64748b;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".nav-menu {";
echo "list-style: none;";
echo "}";
echo "";
echo ".nav-item {";
echo "padding: 15px 0;";
echo "border-bottom: 1px solid #e2e8f0;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 12px;";
echo "font-weight: 600;";
echo "color: #475569;";
echo "cursor: pointer;";
echo "transition: color 0.2s;";
echo "}";
echo "";
echo ".nav-item:hover {";
echo "color: #f97316;";
echo "}";
echo "";
echo ".nav-item.active {";
echo "color: #f97316;";
echo "}";
echo "";
echo ".nav-item i {";
echo "width: 20px;";
echo "text-align: center;";
echo "}";
echo "";
echo "/* Main content */";
echo ".main-content {";
echo "flex: 3;";
echo "background: white;";
echo "border-radius: 12px;";
echo "box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);";
echo "padding: 25px;";
echo "}";
echo "";
echo ".content-header {";
echo "margin-bottom: 25px;";
echo "}";
echo "";
echo ".content-header h1 {";
echo "font-size: 1.5rem;";
echo "color: #1e293b;";
echo "margin-bottom: 10px;";
echo "}";
echo "";
echo ".content-header p {";
echo "color: #64748b;";
echo "}";
echo "";
echo "/* Empty state */";
echo ".empty-state {";
echo "text-align: center;";
echo "padding: 40px 20px;";
echo "}";
echo "";
echo ".empty-icon {";
echo "width: 120px;";
echo "height: 120px;";
echo "margin: 0 auto 20px;";
echo "background: #f1f5f9;";
echo "border-radius: 50%;";
echo "display: flex;";
echo "justify-content: center;";
echo "align-items: center;";
echo "color: #cbd5e0;";
echo "}";
echo "";
echo ".empty-icon i {";
echo "font-size: 3rem;";
echo "}";
echo "";
echo ".empty-state h2 {";
echo "font-size: 1.5rem;";
echo "color: #475569;";
echo "margin-bottom: 15px;";
echo "}";
echo "";
echo ".empty-state p {";
echo "color: #64748b;";
echo "max-width: 500px;";
echo "margin: 0 auto 30px;";
echo "line-height: 1.6;";
echo "}";
echo "";
echo ".cta-button {";
echo "background: #f97316;";
echo "color: white;";
echo "border: none;";
echo "padding: 12px 24px;";
echo "border-radius: 8px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "transition: background 0.3s ease;";
echo "display: inline-flex;";
echo "align-items: center;";
echo "gap: 8px;";
echo "}";
echo "";
echo ".cta-button:hover {";
echo "background: #ea580c;";
echo "}";
echo "";
echo "/* Order cards */";
echo ".order-cards {";
echo "display: flex;";
echo "flex-direction: column;";
echo "gap: 20px;";
echo "}";
echo "";
echo ".order-card {";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 12px;";
echo "padding: 20px;";
echo "display: flex;";
echo "gap: 20px;";
echo "transition: box-shadow 0.3s ease;";
echo "}";
echo "";
echo ".order-card:hover {";
echo "box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);";
echo "}";
echo "";
echo ".order-image {";
echo "width: 100px;";
echo "height: 100px;";
echo "border-radius: 8px;";
echo "object-fit: cover;";
echo "}";
echo "";
echo ".order-details {";
echo "flex-grow: 1;";
echo "}";
echo "";
echo ".order-details h3 {";
echo "font-size: 1.1rem;";
echo "margin-bottom: 8px;";
echo "}";
echo "";
echo ".order-info {";
echo "color: #64748b;";
echo "font-size: 0.9rem;";
echo "margin-bottom: 12px;";
echo "}";
echo "";
echo ".order-price {";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".order-actions {";
echo "display: flex;";
echo "gap: 12px;";
echo "}";
echo "";
echo ".action-button {";
echo "padding: 8px 16px;";
echo "border-radius: 6px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".reorder-button {";
echo "background: #f97316;";
echo "color: white;";
echo "border: none;";
echo "}";
echo "";
echo ".help-button {";
echo "background: white;";
echo "color: #475569;";
echo "border: 1px solid #cbd5e0;";
echo "}";
echo "";
echo "/* Tracking styles */";
echo ".tracking-container {";
echo "margin-top: 20px;";
echo "}";
echo "";
echo ".tracking-steps {";
echo "display: flex;";
echo "justify-content: space-between;";
echo "position: relative;";
echo "margin: 30px 0;";
echo "}";
echo "";
echo ".tracking-steps::before {";
echo "content: '';";
echo "position: absolute;";
echo "top: 15px;";
echo "left: 0;";
echo "right: 0;";
echo "height: 2px;";
echo "background: #e2e8f0;";
echo "z-index: 1;";
echo "}";
echo "";
echo ".tracking-step {";
echo "display: flex;";
echo "flex-direction: column;";
echo "align-items: center;";
echo "position: relative;";
echo "z-index: 2;";
echo "}";
echo "";
echo ".step-icon {";
echo "width: 30px;";
echo "height: 30px;";
echo "border-radius: 50%;";
echo "background: white;";
echo "border: 2px solid #e2e8f0;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "margin-bottom: 8px;";
echo "color: #64748b;";
echo "}";
echo "";
echo ".step-active .step-icon {";
echo "background: #f97316;";
echo "border-color: #f97316;";
echo "color: white;";
echo "}";
echo "";
echo ".step-label {";
echo "font-size: 0.8rem;";
echo "color: #64748b;";
echo "text-align: center;";
echo "}";
echo "";
echo ".step-active .step-label {";
echo "color: #f97316;";
echo "font-weight: 600;";
echo "}";
echo "";
echo "/* Favorites grid */";
echo ".favorites-grid {";
echo "display: grid;";
echo "grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));";
echo "gap: 20px;";
echo "}";
echo "";
echo ".favorite-card {";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 12px;";
echo "overflow: hidden;";
echo "transition: transform 0.3s ease;";
echo "}";
echo "";
echo ".favorite-card:hover {";
echo "transform: translateY(-5px);";
echo "}";
echo "";
echo ".favorite-image {";
echo "width: 100%;";
echo "height: 140px;";
echo "object-fit: cover;";
echo "}";
echo "";
echo ".favorite-details {";
echo "padding: 15px;";
echo "}";
echo "";
echo ".favorite-details h3 {";
echo "font-size: 1rem;";
echo "margin-bottom: 5px;";
echo "}";
echo "";
echo ".favorite-details p {";
echo "color: #64748b;";
echo "font-size: 0.85rem;";
echo "margin-bottom: 10px;";
echo "}";
echo "";
echo ".favorite-price {";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "}";
echo "";
echo "/* Offers grid */";
echo ".offers-grid {";
echo "display: grid;";
echo "grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));";
echo "gap: 20px;";
echo "}";
echo "";
echo ".offer-card {";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 12px;";
echo "padding: 20px;";
echo "background: linear-gradient(135deg, #ffedd5, #fed7aa);";
echo "position: relative;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".offer-card::before {";
echo "content: '';";
echo "position: absolute;";
echo "top: -50px;";
echo "right: -50px;";
echo "width: 100px;";
echo "height: 100px;";
echo "background: rgba(249, 115, 22, 0.1);";
echo "border-radius: 50%;";
echo "}";
echo "";
echo ".offer-card h3 {";
echo "font-size: 1.1rem;";
echo "margin-bottom: 10px;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".offer-card p {";
echo "color: #475569;";
echo "font-size: 0.9rem;";
echo "margin-bottom: 15px;";
echo "}";
echo "";
echo ".offer-code {";
echo "display: inline-block;";
echo "background: white;";
echo "padding: 5px 10px;";
echo "border-radius: 4px;";
echo "font-weight: 700;";
echo "color: #f97316;";
echo "border: 1px dashed #f97316;";
echo "}";
echo "";
echo "/* Profile form */";
echo ".profile-form {";
echo "max-width: 500px;";
echo "}";
echo "";
echo ".form-group {";
echo "margin-bottom: 20px;";
echo "}";
echo "";
echo ".form-group label {";
echo "display: block;";
echo "margin-bottom: 8px;";
echo "font-weight: 600;";
echo "color: #374151;";
echo "}";
echo "";
echo ".form-group input, .form-group select {";
echo "width: 100%;";
echo "padding: 12px 15px;";
echo "border: 1px solid #d1d5db;";
echo "border-radius: 8px;";
echo "font-size: 1rem;";
echo "transition: border-color 0.3s;";
echo "}";
echo "";
echo ".form-group input:focus, .form-group select:focus {";
echo "outline: none;";
echo "border-color: #f97316;";
echo "box-shadow: 0 0 0 3px rgba(249, 115, 22, 0.1);";
echo "}";
echo "";
echo ".profile-picture-upload {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 20px;";
echo "margin-bottom: 20px;";
echo "}";
echo "";
echo ".profile-picture-preview {";
echo "width: 100px;";
echo "height: 100px;";
echo "border-radius: 50%;";
echo "overflow: hidden;";
echo "border: 2px solid #e2e8f0;";
echo "}";
echo "";
echo ".profile-picture-preview img {";
echo "width: 100%;";
echo "height: 100%;";
echo "object-fit: cover;";
echo "}";
echo "";
echo ".upload-button {";
echo "background: #f97316;";
echo "color: white;";
echo "border: none;";
echo "padding: 10px 20px;";
echo "border-radius: 8px;";
echo "cursor: pointer;";
echo "font-weight: 600;";
echo "}";
echo "";
echo ".save-button {";
echo "background: #f97316;";
echo "color: white;";
echo "border: none;";
echo "padding: 12px 30px;";
echo "border-radius: 8px;";
echo "cursor: pointer;";
echo "font-weight: 600;";
echo "font-size: 1rem;";
echo "margin-top: 10px;";
echo "}";
echo "";
echo "/* Responsive design */";
echo "@media (max-width: 900px) {";
echo ".container {";
echo "flex-direction: column;";
echo "}";
echo "";
echo ".sidebar {";
echo "width: 100%;";
echo "}";
echo "}";
echo "";
echo "@media (max-width: 600px) {";
echo "header {";
echo "padding: 15px 20px;";
echo "}";
echo "";
echo ".container {";
echo "padding: 0 15px;";
echo "}";
echo "";
echo ".order-card {";
echo "flex-direction: column;";
echo "}";
echo "";
echo ".order-image {";
echo "width: 100%;";
echo "height: 180px;";
echo "}";
echo "";
echo ".favorites-grid, .offers-grid {";
echo "grid-template-columns: 1fr;";
echo "}";
echo "}";
echo "</style>";
echo "</head>";
echo "<body>";
echo "<button id=\"dmBtn\" style=\"position:fixed;top:12px;right:12px;z-index:50;background:#f97316;color:#fff;border:none;border-radius:9999px;width:40px;height:40px;cursor:pointer\">🌓</button>";
echo "<header>";
echo "<div class=\"logo\">";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/2838/2838912.png\" alt=\"logo\"/>";
echo "<a href=\"swiggyhome.php\" style=\"color:#1e293b; text-decoration:none;\">FOOD DELIVERY</a>";
echo "</div>";
echo "<nav class=\"nav-right\">";
echo "<a href=\"help.php\" class=\"help-btn\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "Help";
echo "</a>";
echo "<a href=\"my acc.php\">User</a>";
echo "</nav>";
echo "</header>";
echo "";
echo "<div class=\"container\">";
echo "<!-- Sidebar -->";
echo "<aside class=\"sidebar\">";
echo "<div class=\"profile-header\">";
echo "<div class=\"profile-avatar\" id=\"profileAvatar\">";
echo "<span id=\"avatarInitials\">JEM</span>";
echo "</div>";
echo "<div class=\"profile-info\">";
echo "<h2 id=\"profileName\">User</h2>";
echo "<p id=\"profileContact\">8078998813 • junaelsamathew@gmail.com</p>";
echo "</div>";
echo "</div>";
echo "";
echo "<ul class=\"nav-menu\">";
echo "<li class=\"nav-item active\" data-section=\"orders\">";
echo "<i class=\"fas fa-clipboard-list\"></i>";
echo "<span>Orders</span>";
echo "</li>";
echo "<li class=\"nav-item\" data-section=\"track\">";
echo "<i class=\"fas fa-truck\"></i>";
echo "<span>Track Orders</span>";
echo "</li>";
echo "<li class=\"nav-item\" data-section=\"favorites\">";
echo "<i class=\"fas fa-heart\"></i>";
echo "<span>Favorites</span>";
echo "</li>";
echo "<li class=\"nav-item\" data-section=\"addresses\">";
echo "<i class=\"fas fa-map-marker-alt\"></i>";
echo "<span>Addresses</span>";
echo "</li>";
echo "<li class=\"nav-item\" data-section=\"payments\">";
echo "<i class=\"fas fa-wallet\"></i>";
echo "<span>Payments</span>";
echo "</li>";
echo "<li class=\"nav-item\" data-section=\"offers\">";
echo "<i class=\"fas fa-percent\"></i>";
echo "<span>Offers</span>";
echo "</li>";
echo "<li class=\"nav-item\" data-section=\"account\">";
echo "<i class=\"fas fa-user\"></i>";
echo "<span>Account Settings</span>";
echo "</li>";
echo "<li class=\"nav-item\" data-section=\"help\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "<span>Help & Support</span>";
echo "</li>";
echo "</ul>";
echo "</aside>";
echo "";
echo "<!-- Main content -->";
echo "<main class=\"main-content\">";
echo "<!-- Orders section -->";
echo "<section id=\"section-orders\">";
echo "<div class=\"content-header\">";
echo "<h1>Your Orders</h1>";
echo "<p>All your orders will be displayed on this page for easy access.</p>";
echo "</div>";
echo "<div id=\"orders-empty\" class=\"empty-state\" style=\"display:none\">";
echo "<div class=\"empty-icon\"><i class=\"fas fa-shopping-bag\"></i></div>";
echo "<h2>No Orders Yet</h2>";
echo "<p>You haven't placed any orders yet. When you do, they'll appear here.</p>";
echo "<a href=\"swiggyhome.php\" class=\"cta-button\"><i class=\"fas fa-utensils\"></i> Order now</a>";
echo "</div>";
echo "<div id=\"orders-list\" class=\"order-cards\"></div>";
echo "</section>";
echo "";
echo "<!-- Track orders section -->";
echo "<section id=\"section-track\" style=\"display:none\">";
echo "<div class=\"content-header\">";
echo "<h1>Track Orders</h1>";
echo "<p>View live status of your current orders.</p>";
echo "</div>";
echo "<div class=\"empty-state\" id=\"track-empty\" style=\"display:none\">";
echo "<div class=\"empty-icon\"><i class=\"fas fa-truck\"></i></div>";
echo "<h2>No Active Deliveries</h2>";
echo "<p>Place an order to track its delivery in real time.</p>";
echo "</div>";
echo "<div id=\"track-list\" class=\"order-cards\"></div>";
echo "</section>";
echo "";
echo "<!-- Favorites -->";
echo "<section id=\"section-favorites\" style=\"display:none\">";
echo "<div class=\"content-header\">";
echo "<h1>Favorites</h1>";
echo "<p>Your saved restaurants and dishes.</p>";
echo "</div>";
echo "<div id=\"favorites-empty\" class=\"empty-state\" style=\"display:none\">";
echo "<div class=\"empty-icon\"><i class=\"fas fa-heart\"></i></div>";
echo "<h2>No Favorites Yet</h2>";
echo "<p>Tap the heart icon on a restaurant to add it here.</p>";
echo "</div>";
echo "<div id=\"favorites-list\" class=\"favorites-grid\"></div>";
echo "</section>";
echo "";
echo "<!-- Addresses -->";
echo "<section id=\"section-addresses\" style=\"display:none\">";
echo "<div class=\"content-header\"><h1>Addresses</h1><p>Manage your delivery addresses.</p></div>";
echo "<div class=\"empty-state\"><div class=\"empty-icon\"><i class=\"fas fa-map-marker-alt\"></i></div><h2>No Addresses</h2><p>Add an address during checkout or here.</p></div>";
echo "</section>";
echo "";
echo "<!-- Payments -->";
echo "<section id=\"section-payments\" style=\"display:none\">";
echo "<div class=\"content-header\"><h1>Payments</h1><p>Saved payment methods and transactions.</p></div>";
echo "<div class=\"empty-state\"><div class=\"empty-icon\"><i class=\"fas fa-wallet\"></i></div><h2>No Saved Methods</h2><p>Add a card or UPI during checkout.</p></div>";
echo "</section>";
echo "";
echo "<!-- Offers -->";
echo "<section id=\"section-offers\" style=\"display:none\">";
echo "<div class=\"content-header\"><h1>Offers</h1><p>Available coupons and promotions.</p></div>";
echo "<div id=\"offers-list\" class=\"offers-grid\"></div>";
echo "</section>";
echo "";
echo "<!-- Account Settings -->";
echo "<section id=\"section-account\" style=\"display:none\">";
echo "<div class=\"content-header\"><h1>Account Settings</h1><p>Update your profile information.</p></div>";
echo "<div class=\"profile-form\">";
echo "<div class=\"profile-picture-upload\">";
echo "<div class=\"profile-picture-preview\">";
echo "<img id=\"profilePicture\" src=\"\" alt=\"Profile Picture\">";
echo "</div>";
echo "<div>";
echo "<input type=\"file\" id=\"profilePictureInput\" accept=\"image/*\" style=\"display:none\">";
echo "<button class=\"upload-button\" id=\"uploadPictureBtn\">Upload Picture</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"form-group\">";
echo "<label for=\"fullName\">Full Name</label>";
echo "<input type=\"text\" id=\"fullName\" placeholder=\"Enter your full name\">";
echo "</div>";
echo "";
echo "<div class=\"form-group\">";
echo "<label for=\"email\">Email Address</label>";
echo "<input type=\"email\" id=\"email\" placeholder=\"Enter your email\">";
echo "</div>";
echo "";
echo "<div class=\"form-group\">";
echo "<label for=\"phone\">Phone Number</label>";
echo "<input type=\"tel\" id=\"phone\" placeholder=\"Enter your phone number\">";
echo "</div>";
echo "";
echo "<button class=\"save-button\" id=\"saveProfileBtn\">Save Changes</button>";
echo "</div>";
echo "</section>";
echo "";
echo "<!-- Help & Support -->";
echo "<section id=\"section-help\" style=\"display:none\">";
echo "<div class=\"content-header\"><h1>Help & Support</h1><p>We are here to help.</p></div>";
echo "<div class=\"empty-state\"><div class=\"empty-icon\"><i class=\"fas fa-question-circle\"></i></div><h2>Need help?</h2><p>Visit our <a href=\"help.php\">Help page</a> for FAQs or contact us.</p></div>";
echo "</section>";
echo "</main>";
echo "</div>";
echo "";
echo "<script>";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "// dark mode";
echo "(function(){";
echo "const saved = localStorage.getItem('theme');";
echo "if(saved === 'dark') document.documentElement.classList.add('dark');";
echo "const btn = document.getElementById('dmBtn');";
echo "btn.addEventListener('click', ()=>{";
echo "document.documentElement.classList.toggle('dark');";
echo "localStorage.setItem('theme', document.documentElement.classList.contains('dark') ? 'dark':'light');";
echo "});";
echo "})();";
echo "";
echo "// Load user profile data";
echo "function loadUserProfile() {";
echo "const savedName = localStorage.getItem('userName') || 'User';";
echo "const savedEmail = localStorage.getItem('userEmail') || 'junaelsamathew@gmail.com';";
echo "const savedPhone = localStorage.getItem('userPhone') || '8078998813';";
echo "const savedProfilePic = localStorage.getItem('userProfilePic');";
echo "";
echo "// Update header and sidebar";
echo "document.querySelector('nav.nav-right a[href=\"my acc.php\"]').textContent = savedName;";
echo "document.getElementById('profileName').textContent = savedName;";
echo "document.getElementById('profileContact').textContent = `${savedPhone} • ${savedEmail}`;";
echo "";
echo "// Update profile initials";
echo "const initials = savedName.split(' ').map(n => n[0]).join('').toUpperCase();";
echo "document.getElementById('avatarInitials').textContent = initials;";
echo "";
echo "// Update profile picture if exists";
echo "if (savedProfilePic) {";
echo "document.getElementById('profilePicture').src = savedProfilePic;";
echo "document.getElementById('avatarInitials').style.display = 'none';";
echo "}";
echo "";
echo "// Update form fields";
echo "document.getElementById('fullName').value = savedName;";
echo "document.getElementById('email').value = savedEmail;";
echo "document.getElementById('phone').value = savedPhone;";
echo "}";
echo "";
echo "// Save user profile data";
echo "function saveUserProfile() {";
echo "const fullName = document.getElementById('fullName').value;";
echo "const email = document.getElementById('email').value;";
echo "const phone = document.getElementById('phone').value;";
echo "";
echo "localStorage.setItem('userName', fullName);";
echo "localStorage.setItem('userEmail', email);";
echo "localStorage.setItem('userPhone', phone);";
echo "";
echo "loadUserProfile();";
echo "alert('Profile updated successfully!');";
echo "}";
echo "";
echo "// Profile picture upload";
echo "document.getElementById('uploadPictureBtn').addEventListener('click', function() {";
echo "document.getElementById('profilePictureInput').click();";
echo "});";
echo "";
echo "document.getElementById('profilePictureInput').addEventListener('change', function(e) {";
echo "const file = e.target.files[0];";
echo "if (file) {";
echo "const reader = new FileReader();";
echo "reader.onload = function(event) {";
echo "const imageData = event.target.result;";
echo "localStorage.setItem('userProfilePic', imageData);";
echo "document.getElementById('profilePicture').src = imageData;";
echo "document.getElementById('avatarInitials').style.display = 'none';";
echo "};";
echo "reader.readAsDataURL(file);";
echo "}";
echo "});";
echo "";
echo "// Save profile button";
echo "document.getElementById('saveProfileBtn').addEventListener('click', saveUserProfile);";
echo "";
echo "// Navigation menu functionality + section switching";
echo "const navItems = document.querySelectorAll('.nav-item');";
echo "const sections = document.querySelectorAll('main section[id^=\"section-\"]');";
echo "";
echo "function showSection(key){";
echo "sections.forEach(s => s.style.display = 'none');";
echo "const el = document.getElementById('section-' + key);";
echo "if (el) el.style.display = '';";
echo "";
echo "// Load section-specific data";
echo "if (key === 'orders') renderOrders();";
echo "if (key === 'track') renderTracking();";
echo "if (key === 'favorites') renderFavorites();";
echo "if (key === 'offers') renderOffers();";
echo "}";
echo "";
echo "navItems.forEach(item => {";
echo "item.addEventListener('click', function() {";
echo "navItems.forEach(i => i.classList.remove('active'));";
echo "this.classList.add('active');";
echo "const key = this.getAttribute('data-section');";
echo "if (key) showSection(key);";
echo "});";
echo "});";
echo "";
echo "// Render orders from localStorage (show only the latest order)";
echo "function renderOrders(){";
echo "const orders = JSON.parse(localStorage.getItem('orders') || '[]');";
echo "const list = document.getElementById('orders-list');";
echo "const empty = document.getElementById('orders-empty');";
echo "";
echo "list.innerHTML = '';";
echo "";
echo "if (!orders.length){";
echo "empty.style.display = '';";
echo "return;";
echo "}";
echo "";
echo "empty.style.display = 'none';";
echo "";
echo "// Sort orders by timestamp (newest first) and take only the latest";
echo "orders.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));";
echo "const latestOrder = orders[0];";
echo "const itemsList = latestOrder.items.map(item => `${item.qty || 1}x ${item.title}`).join(', ');";
echo "const orderDate = new Date(latestOrder.timestamp).toLocaleDateString('en-IN');";
echo "";
echo "const card = document.createElement('div');";
echo "card.className = 'order-card';";
echo "card.innerHTML = `";
echo "<div class=\"order-details\">";
echo "<h3>Order #${latestOrder.id.slice(3)}</h3>";
echo "<div class=\"order-info\">${itemsList}</div>";
echo "<div class=\"order-price\">₹${latestOrder.total}</div>";
echo "<div class=\"order-info\">Ordered on: ${orderDate}</div>";
echo "</div>`;";
echo "list.appendChild(card);";
echo "}";
echo "";
echo "// Render order tracking (show only the latest order)";
echo "function renderTracking(){";
echo "const orders = JSON.parse(localStorage.getItem('orders') || '[]');";
echo "const list = document.getElementById('track-list');";
echo "const empty = document.getElementById('track-empty');";
echo "";
echo "list.innerHTML = '';";
echo "";
echo "if (!orders.length){";
echo "empty.style.display = '';";
echo "return;";
echo "}";
echo "";
echo "empty.style.display = 'none';";
echo "";
echo "// Sort orders by timestamp (newest first) and take only the latest";
echo "orders.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));";
echo "const latestOrder = orders[0];";
echo "";
echo "// Determine tracking status based on time elapsed";
echo "const now = new Date();";
echo "const orderTime = new Date(latestOrder.timestamp);";
echo "const timeElapsed = now - orderTime;";
echo "let statusIndex = 0;";
echo "if (timeElapsed > 10 * 60 * 1000) statusIndex = 1; // preparing";
echo "if (timeElapsed > 25 * 60 * 1000) statusIndex = 2; // on the way";
echo "if (timeElapsed > 45 * 60 * 1000) statusIndex = 3; // delivered";
echo "";
echo "const statuses = ['Order Placed', 'Preparing', 'On the Way', 'Delivered'];";
echo "const itemsList = latestOrder.items.map(item => `${item.qty || 1}x ${item.title}`).join(', ');";
echo "";
echo "const card = document.createElement('div');";
echo "card.className = 'order-card';";
echo "card.innerHTML = `";
echo "<div class=\"order-details\" style=\"width:100%\">";
echo "<h3>Order #${latestOrder.id.slice(3)}</h3>";
echo "<div class=\"order-info\">${itemsList}</div>";
echo "<div class=\"order-price\">₹${latestOrder.total}</div>";
echo "";
echo "<div class=\"tracking-container\">";
echo "<div class=\"tracking-steps\">";
echo "${statuses.map((status, index) => `";
echo "<div class=\"tracking-step ${index <= statusIndex ? 'step-active' : ''}\">";
echo "<div class=\"step-icon\">";
echo "<i class=\"fas fa-${index === 0 ? 'check' : index === 1 ? 'utensils' : index === 2 ? 'motorcycle' : 'home'}\"></i>";
echo "</div>";
echo "<div class=\"step-label\">${status}</div>";
echo "</div>";
echo "`).join('')}";
echo "</div>";
echo "<div class=\"order-info\">Estimated delivery: ${latestOrder.scheduledDateTimeReadable || '25-30 mins'}</div>";
echo "</div>";
echo "</div>`;";
echo "list.appendChild(card);";
echo "}";
echo "";
echo "// Render favorites";
echo "function renderFavorites(){";
echo "const favorites = JSON.parse(localStorage.getItem('favorites') || '[]');";
echo "const list = document.getElementById('favorites-list');";
echo "const empty = document.getElementById('favorites-empty');";
echo "";
echo "list.innerHTML = '';";
echo "";
echo "if (!favorites.length){";
echo "empty.style.display = '';";
echo "return;";
echo "}";
echo "";
echo "empty.style.display = 'none';";
echo "";
echo "favorites.forEach(favorite => {";
echo "const card = document.createElement('div');";
echo "card.className = 'favorite-card';";
echo "card.innerHTML = `";
echo "<img class=\"favorite-image\" src=\"${favorite.image || 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Zm9vZHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80'}\" alt=\"${favorite.name}\">";
echo "<div class=\"favorite-details\">";
echo "<h3>${favorite.name}</h3>";
echo "<p>${favorite.restaurant}</p>";
echo "<div class=\"favorite-price\">₹${favorite.price}</div>";
echo "</div>`;";
echo "list.appendChild(card);";
echo "});";
echo "}";
echo "";
echo "// Render offers";
echo "function renderOffers(){";
echo "const offers = [";
echo "{";
echo "title: \"First Order Special\",";
echo "description: \"Get 50% off up to ₹100 on your first order\",";
echo "code: \"FIRST50\"";
echo "},";
echo "{";
echo "title: \"Weekend Feast\",";
echo "description: \"Flat ₹75 off on orders above ₹299\",";
echo "code: \"WEEKEND75\"";
echo "},";
echo "{";
echo "title: \"Free Delivery\",";
echo "description: \"Free delivery on all orders above ₹199\",";
echo "code: \"FREEDEL\"";
echo "},";
echo "{";
echo "title: \"Combo Deal\",";
echo "description: \"Buy any 2 items and get 1 free\",";
echo "code: \"COMBO123\"";
echo "},";
echo "{";
echo "title: \"Evening Special\",";
echo "description: \"30% off on all orders between 7 PM - 10 PM\",";
echo "code: \"EVENING30\"";
echo "}";
echo "];";
echo "";
echo "const list = document.getElementById('offers-list');";
echo "list.innerHTML = '';";
echo "";
echo "offers.forEach(offer => {";
echo "const card = document.createElement('div');";
echo "card.className = 'offer-card';";
echo "card.innerHTML = `";
echo "<h3>${offer.title}</h3>";
echo "<p>${offer.description}</p>";
echo "<div class=\"offer-code\">${offer.code}</div>`;";
echo "list.appendChild(card);";
echo "});";
echo "}";
echo "";
echo "// Initialize";
echo "loadUserProfile();";
echo "showSection('orders');";
echo "});";
echo "</script>";
echo "</body>";
echo "</html>";
?>