<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
echo "<title>Secure Checkout</title>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">";
echo "<style>";
echo ":root { --bg:#f8fafc; --text:#1a202c; --panel:#ffffff; --ring:#e2e8f0 }";
echo ".dark :root, .dark { --bg:#0f172a; --text:#e5e7eb; --panel:#0b1220; --ring:#1f2937 }";
echo "body { background: var(--bg); color: var(--text); }";
echo "/* Reset and base styles */";
echo "* {";
echo "box-sizing: border-box;";
echo "margin: 0;";
echo "padding: 0;";
echo "}";
echo "";
echo "body {";
echo "font-family: 'Poppins', sans-serif;";
echo "background-color: #f8fafc;";
echo "margin: 0;";
echo "padding: 0;";
echo "color: #1a202c;";
echo "line-height: 1.6;";
echo "}";
echo "";
echo "a {";
echo "text-decoration: none;";
echo "color: #f97316;";
echo "}";
echo "";
echo ".container {";
echo "max-width: 1100px;";
echo "margin: 30px auto;";
echo "background-color: var(--panel);";
echo "padding: 20px 30px;";
echo "border-radius: 12px;";
echo "display: flex;";
echo "gap: 30px;";
echo "box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);";
echo "}";
echo "";
echo "/* Left - Checkout steps */";
echo ".checkout-left {";
echo "flex: 2;";
echo "display: flex;";
echo "flex-direction: column;";
echo "gap: 25px;";
echo "}";
echo "";
echo ".step {";
echo "background: var(--panel);";
echo "padding: 25px;";
echo "border-radius: 10px;";
echo "box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);";
echo "position: relative;";
echo "border-left: 6px solid transparent;";
echo "display: flex;";
echo "flex-direction: column;";
echo "}";
echo "";
echo ".step-icon {";
echo "position: absolute;";
echo "left: -30px;";
echo "top: 25px;";
echo "background-color: #1a202c;";
echo "color: white;";
echo "width: 28px;";
echo "height: 28px;";
echo "border-radius: 50%;";
echo "display: flex;";
echo "justify-content: center;";
echo "align-items: center;";
echo "font-size: 14px;";
echo "font-weight: bold;";
echo "}";
echo "";
echo ".step.completed .step-icon {";
echo "background-color: #10b981;";
echo "}";
echo "";
echo ".step h3 {";
echo "margin: 0 0 12px 0;";
echo "font-weight: 700;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: space-between;";
echo "font-size: 1.25rem;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".step h3 .change {";
echo "color: #f97316;";
echo "font-weight: 600;";
echo "font-size: 0.9rem;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".step p {";
echo "margin: 0 0 8px 0;";
echo "font-weight: 400;";
echo "font-size: 0.95rem;";
echo "color: #4a5568;";
echo "}";
echo "";
echo ".step span.time {";
echo "font-weight: 700;";
echo "font-size: 0.9rem;";
echo "margin-top: 8px;";
echo "color: #10b981;";
echo "background: #ecfdf5;";
echo "padding: 6px 12px;";
echo "border-radius: 20px;";
echo "display: inline-block;";
echo "width: fit-content;";
echo "}";
echo "";
echo "/* Scheduled Delivery Styles */";
echo ".scheduled-delivery {";
echo "display: none;";
echo "margin-top: 20px;";
echo "padding: 20px;";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "background-color: #f8fafc;";
echo "}";
echo "";
echo ".scheduled-delivery.active {";
echo "display: block;";
echo "}";
echo "";
echo ".delivery-option {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "margin-bottom: 15px;";
echo "}";
echo "";
echo ".date-input-container, .time-input-container {";
echo "position: relative;";
echo "margin-top: 15px;";
echo "display: none;";
echo "}";
echo "";
echo ".date-input, .time-input {";
echo "width: 100%;";
echo "padding: 12px 15px 12px 12px;";
echo "border: 1px solid #cbd5e0;";
echo "border-radius: 8px;";
echo "font-size: 1rem;";
echo "transition: border-color 0.3s;";
echo "}";
echo "";
echo ".date-input:focus, .time-input:focus {";
echo "outline: none;";
echo "border-color: #10b981;";
echo "box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.2);";
echo "}";
echo "";
echo ".calendar-icon, .clock-icon {";
echo "position: absolute;";
echo "right: 15px;";
echo "top: 50%;";
echo "transform: translateY(-50%);";
echo "color: #64748b;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".delivery-note {";
echo "margin-top: 15px;";
echo "padding: 10px;";
echo "background-color: #ecfdf5;";
echo "border-radius: 6px;";
echo "font-size: 0.9rem;";
echo "color: #065f46;";
echo "}";
echo "";
echo "/* Payment button */";
echo ".payment-button {";
echo "background-color: #10b981;";
echo "border: none;";
echo "border-radius: 8px;";
echo "color: white;";
echo "text-align: center;";
echo "font-weight: 700;";
echo "font-size: 1.1rem;";
echo "padding: 18px 0;";
echo "cursor: pointer;";
echo "transition: background-color 0.3s ease;";
echo "margin-top: 25px;";
echo "box-shadow: 0 4px 6px rgba(16, 185, 129, 0.3);";
echo "width: 100%;";
echo "}";
echo "";
echo ".payment-button:hover {";
echo "background-color: #059669;";
echo "transform: translateY(-2px);";
echo "box-shadow: 0 6px 8px rgba(16, 185, 129, 0.4);";
echo "}";
echo "";
echo "/* Right - Order Summary */";
echo ".checkout-right {";
echo "flex: 1;";
echo "display: flex;";
echo "flex-direction: column;";
echo "gap: 25px;";
echo "}";
echo "";
echo ".order-summary, .rules {";
echo "background: var(--panel);";
echo "padding: 25px;";
echo "border-radius: 10px;";
echo "box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);";
echo "font-size: 0.95rem;";
echo "color: #1a202c;";
echo "}";
echo "";
echo "/* Food item */";
echo ".food-item {";
echo "display: flex;";
echo "align-items: flex-start;";
echo "gap: 15px;";
echo "margin-bottom: 20px;";
echo "padding-bottom: 20px;";
echo "border-bottom: 1px solid #e2e8f0;";
echo "}";
echo "";
echo ".food-item img {";
echo "width: 80px;";
echo "height: 80px;";
echo "border-radius: 12px;";
echo "object-fit: cover;";
echo "box-shadow: 0 2px 8px rgba(0,0,0,0.12);";
echo "margin-right: 10px;";
echo "background: #f1f5f9;";
echo "}";
echo "";
echo ".food-details {";
echo "flex-grow: 1;";
echo "}";
echo "";
echo ".food-title {";
echo "font-weight: 700;";
echo "margin: 0 0 5px 0;";
echo "font-size: 1.1rem;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".food-location {";
echo "color: #64748b;";
echo "font-size: 0.9rem;";
echo "margin-bottom: 10px;";
echo "}";
echo "";
echo ".choice-container {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 12px;";
echo "font-size: 0.95rem;";
echo "color: #10b981;";
echo "margin-bottom: 12px;";
echo "}";
echo "";
echo ".quantity-picker {";
echo "border: 1px solid #cbd5e0;";
echo "border-radius: 6px;";
echo "display: inline-flex;";
echo "align-items: center;";
echo "user-select: none;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".quantity-picker button {";
echo "border: none;";
echo "background: #f8fafc;";
echo "font-weight: 600;";
echo "font-size: 1.1rem;";
echo "width: 30px;";
echo "height: 30px;";
echo "cursor: pointer;";
echo "color: #10b981;";
echo "outline: none;";
echo "transition: background-color 0.2s;";
echo "}";
echo "";
echo ".quantity-picker button:hover {";
echo "background: #e2e8f0;";
echo "}";
echo "";
echo ".quantity-picker span {";
echo "padding: 0 12px;";
echo "font-weight: 600;";
echo "}";
echo "";
echo ".price {";
echo "margin-left: auto;";
echo "font-weight: 700;";
echo "font-size: 1.1rem;";
echo "color: #1a202c;";
echo "}";
echo "";
echo "/* Suggestions box */";
echo ".suggestions-box {";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "margin-bottom: 15px;";
echo "padding: 12px 15px;";
echo "font-size: 0.9rem;";
echo "color: #64748b;";
echo "font-style: italic;";
echo "background: #f8fafc;";
echo "}";
echo "";
echo ".checkbox-container {";
echo "border: 1px solid var(--ring);";
echo "border-radius: 8px;";
echo "padding: 15px;";
echo "margin-bottom: 15px;";
echo "font-size: 0.9rem;";
echo "color: #1a202c;";
echo "background: #f8fafc;";
echo "}";
echo "";
echo ".checkbox-container label {";
echo "display: flex;";
echo "align-items: flex-start;";
echo "gap: 10px;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".checkbox-container input[type=\"checkbox\"] {";
echo "transform: scale(1.3);";
echo "margin-top: 3px;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".checkbox-label-main {";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "margin-bottom: 5px;";
echo "}";
echo "";
echo ".apply-coupon {";
echo "border: 2px dashed var(--ring);";
echo "padding: 15px;";
echo "font-weight: 700;";
echo "font-size: 1rem;";
echo "cursor: pointer;";
echo "text-align: center;";
echo "user-select: none;";
echo "color: #475569;";
echo "margin-bottom: 20px;";
echo "border-radius: 8px;";
echo "transition: all 0.3s ease;";
echo "}";
echo "";
echo ".apply-coupon:hover {";
echo "background: #f1f5f9;";
echo "border-color: #94a3b8;";
echo "}";
echo "";
echo ".bill-details {";
echo "font-size: 0.95rem;";
echo "margin-bottom: 20px;";
echo "}";
echo "";
echo ".bill-row {";
echo "display: flex;";
echo "justify-content: space-between;";
echo "margin-bottom: 10px;";
echo "color: #475569;";
echo "padding: 5px 0;";
echo "}";
echo "";
echo ".bill-row.total {";
echo "font-weight: 800;";
echo "font-size: 1.2rem;";
echo "color: #1e293b;";
echo "border-top: 2px solid #e2e8f0;";
echo "padding-top: 15px;";
echo "margin-top: 10px;";
echo "}";
echo "";
echo ".rules {";
echo "font-size: 0.9rem;";
echo "color: #475569;";
echo "}";
echo "";
echo ".rules b {";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".rules a {";
echo "color: #f97316;";
echo "font-weight: 600;";
echo "}";
echo "";
echo "header {";
echo "background: var(--panel);";
echo "padding: 15px 30px;";
echo "box-shadow: 0 2px 4px rgba(0, 0, 0, 0.06);";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "font-size: 1rem;";
echo "font-weight: 600;";
echo "letter-spacing: 0.05em;";
echo "}";
echo "";
echo "header .logo {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "font-weight: 800;";
echo "color: #1e293b;";
echo "font-size: 1.3rem;";
echo "user-select: none;";
echo "}";
echo "";
echo "header .logo img {";
echo "height: 36px;";
echo "width: 36px;";
echo "}";
echo "";
echo "header .nav-right {";
echo "display: flex;";
echo "gap: 25px;";
echo "align-items: center;";
echo "font-weight: 500;";
echo "}";
echo "";
echo "header .nav-right a {";
echo "cursor: pointer;";
echo "color: #475569;";
echo "transition: color 0.2s;";
echo "}";
echo "";
echo "header .nav-right a:hover {";
echo "color: #f97316;";
echo "}";
echo "";
echo ".help-btn {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 6px;";
echo "padding: 8px 12px;";
echo "background: #f97316;";
echo "color: white;";
echo "border-radius: 6px;";
echo "text-decoration: none;";
echo "font-weight: 600;";
echo "transition: all 0.3s ease;";
echo "}";
echo "";
echo ".help-btn:hover {";
echo "background: #ea580c;";
echo "color: white;";
echo "transform: translateY(-1px);";
echo "}";
echo "";
echo ".divider {";
echo "height: 1px;";
echo "background: #e2e8f0;";
echo "margin: 20px 0;";
echo "}";
echo "";
echo ".section-heading {";
echo "font-size: 1.1rem;";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "margin-bottom: 15px;";
echo "padding-bottom: 8px;";
echo "border-bottom: 2px solid #f1f5f9;";
echo "}";
echo "";
echo ".payment-methods {";
echo "margin-top: 20px;";
echo "}";
echo "";
echo ".payment-method {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 12px;";
echo "padding: 15px;";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "margin-bottom: 10px;";
echo "cursor: pointer;";
echo "transition: all 0.2s ease;";
echo "}";
echo "";
echo ".payment-method:hover {";
echo "background-color: #f8fafc;";
echo "border-color: #cbd5e0;";
echo "}";
echo "";
echo ".payment-method input[type=\"radio\"] {";
echo "transform: scale(1.2);";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".payment-method label {";
echo "cursor: pointer;";
echo "font-weight: 500;";
echo "flex-grow: 1;";
echo "}";
echo "";
echo ".payment-method img {";
echo "height: 24px;";
echo "}";
echo "";
echo ".address-modal {";
echo "position: fixed;";
echo "inset: 0;";
echo "background: rgba(0,0,0,0.5);";
echo "display: none;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 2000;";
echo "}";
echo "";
echo ".address-modal-content {";
echo "background: white;";
echo "padding: 30px;";
echo "border-radius: 12px;";
echo "max-width: 500px;";
echo "width: 90%;";
echo "max-height: 80vh;";
echo "overflow-y: auto;";
echo "}";
echo "";
echo ".address-form {";
echo "display: flex;";
echo "flex-direction: column;";
echo "gap: 15px;";
echo "}";
echo "";
echo ".form-group {";
echo "display: flex;";
echo "flex-direction: column;";
echo "gap: 5px;";
echo "}";
echo "";
echo ".form-group label {";
echo "font-weight: 600;";
echo "color: #1e293b;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".form-group input, .form-group textarea {";
echo "padding: 12px;";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "font-size: 1rem;";
echo "transition: border-color 0.3s;";
echo "}";
echo "";
echo ".form-group input:focus, .form-group textarea:focus {";
echo "outline: none;";
echo "border-color: #f97316;";
echo "box-shadow: 0 0 0 3px rgba(249, 115, 22, 0.1);";
echo "}";
echo "";
echo ".form-row {";
echo "display: grid;";
echo "grid-template-columns: 1fr 1fr;";
echo "gap: 15px;";
echo "}";
echo "";
echo ".address-buttons {";
echo "display: flex;";
echo "gap: 10px;";
echo "justify-content: flex-end;";
echo "margin-top: 20px;";
echo "}";
echo "";
echo ".btn {";
echo "padding: 12px 24px;";
echo "border: none;";
echo "border-radius: 8px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "transition: all 0.3s;";
echo "}";
echo "";
echo ".btn-primary {";
echo "background: #f97316;";
echo "color: white;";
echo "}";
echo "";
echo ".btn-primary:hover {";
echo "background: #ea580c;";
echo "}";
echo "";
echo ".btn-secondary {";
echo "background: #e2e8f0;";
echo "color: #64748b;";
echo "}";
echo "";
echo ".btn-secondary:hover {";
echo "background: #cbd5e0;";
echo "}";
echo "";
echo ".coupon-modal {";
echo "position: fixed;";
echo "inset: 0;";
echo "background: rgba(0,0,0,0.5);";
echo "display: none;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 2000;";
echo "}";
echo "";
echo ".coupon-modal-content {";
echo "background: white;";
echo "padding: 30px;";
echo "border-radius: 12px;";
echo "max-width: 400px;";
echo "width: 90%;";
echo "}";
echo "";
echo ".coupon-input-group {";
echo "display: flex;";
echo "gap: 10px;";
echo "margin-bottom: 20px;";
echo "}";
echo "";
echo ".coupon-input-group input {";
echo "flex: 1;";
echo "padding: 12px;";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "font-size: 1rem;";
echo "}";
echo "";
echo ".coupon-input-group button {";
echo "padding: 12px 20px;";
echo "background: #f97316;";
echo "color: white;";
echo "border: none;";
echo "border-radius: 8px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".coupon-list {";
echo "max-height: 200px;";
echo "overflow-y: auto;";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "}";
echo "";
echo ".coupon-item {";
echo "padding: 15px;";
echo "border-bottom: 1px solid #f1f5f9;";
echo "cursor: pointer;";
echo "transition: background 0.3s;";
echo "}";
echo "";
echo ".coupon-item:hover {";
echo "background: #f8fafc;";
echo "}";
echo "";
echo ".coupon-item:last-child {";
echo "border-bottom: none;";
echo "}";
echo "";
echo ".coupon-code {";
echo "font-weight: 600;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".coupon-desc {";
echo "font-size: 0.9rem;";
echo "color: #64748b;";
echo "margin-top: 5px;";
echo "}";
echo "";
echo ".confirmation-modal {";
echo "position: fixed;";
echo "inset: 0;";
echo "background: rgba(0,0,0,0.5);";
echo "display: none;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 2000;";
echo "}";
echo "";
echo ".confirmation-content {";
echo "background: white;";
echo "padding: 40px;";
echo "border-radius: 12px;";
echo "text-align: center;";
echo "max-width: 400px;";
echo "width: 90%;";
echo "}";
echo "";
echo ".success-icon {";
echo "width: 80px;";
echo "height: 80px;";
echo "background: #10b981;";
echo "border-radius: 50%;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "margin: 0 auto 20px;";
echo "font-size: 40px;";
echo "color: white;";
echo "}";
echo "";
echo ".confirmation-title {";
echo "font-size: 1.5rem;";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "margin-bottom: 10px;";
echo "}";
echo "";
echo ".confirmation-message {";
echo "color: #64748b;";
echo "margin-bottom: 30px;";
echo "}";
echo "";
echo ".schedule-section {";
echo "background: white;";
echo "border-radius: 12px;";
echo "padding: 20px;";
echo "margin-bottom: 20px;";
echo "box-shadow: 0 1px 3px rgba(0,0,0,0.1);";
echo "}";
echo "";
echo ".schedule-toggle {";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: space-between;";
echo "margin-bottom: 15px;";
echo "}";
echo "";
echo ".schedule-toggle label {";
echo "font-weight: 600;";
echo "color: #1e293b;";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 8px;";
echo "}";
echo "";
echo ".schedule-toggle input[type=\"checkbox\"] {";
echo "width: 18px;";
echo "height: 18px;";
echo "accent-color: #f97316;";
echo "}";
echo "";
echo ".schedule-options {";
echo "display: none;";
echo "margin-top: 15px;";
echo "padding: 15px;";
echo "background: #f8fafc;";
echo "border-radius: 8px;";
echo "border: 1px solid #e2e8f0;";
echo "}";
echo "";
echo ".schedule-options.active {";
echo "display: block;";
echo "}";
echo "";
echo ".schedule-row {";
echo "display: flex;";
echo "gap: 15px;";
echo "margin-bottom: 15px;";
echo "}";
echo "";
echo ".schedule-group {";
echo "flex: 1;";
echo "}";
echo "";
echo ".schedule-group label {";
echo "display: block;";
echo "font-size: 0.9rem;";
echo "font-weight: 500;";
echo "color: #374151;";
echo "margin-bottom: 5px;";
echo "}";
echo "";
echo ".schedule-group input,";
echo ".schedule-group select {";
echo "width: 100%;";
echo "padding: 10px;";
echo "border: 1px solid #d1d5db;";
echo "border-radius: 6px;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".schedule-group input:focus,";
echo ".schedule-group select:focus {";
echo "outline: none;";
echo "border-color: #f97316;";
echo "box-shadow: 0 0 0 3px rgba(249, 115, 22, 0.1);";
echo "}";
echo "";
echo ".schedule-info {";
echo "background: #dbeafe;";
echo "border: 1px solid #93c5fd;";
echo "color: #1e40af;";
echo "padding: 10px;";
echo "border-radius: 6px;";
echo "font-size: 0.85rem;";
echo "margin-top: 10px;";
echo "}";
echo "";
echo ".order-features {";
echo "background: white;";
echo "border-radius: 12px;";
echo "padding: 20px;";
echo "margin-bottom: 20px;";
echo "box-shadow: 0 1px 3px rgba(0,0,0,0.1);";
echo "}";
echo "";
echo ".order-features h3 {";
echo "color: #1e293b;";
echo "margin-bottom: 15px;";
echo "font-size: 1.1rem;";
echo "}";
echo "";
echo ".feature-item {";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: space-between;";
echo "padding: 12px 0;";
echo "border-bottom: 1px solid #f1f5f9;";
echo "}";
echo "";
echo ".feature-item:last-child {";
echo "border-bottom: none;";
echo "}";
echo "";
echo ".feature-info {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 12px;";
echo "}";
echo "";
echo ".feature-icon {";
echo "width: 24px;";
echo "height: 24px;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "color: #64748b;";
echo "}";
echo "";
echo ".feature-details h4 {";
echo "font-size: 0.9rem;";
echo "color: #1e293b;";
echo "margin: 0;";
echo "}";
echo "";
echo ".feature-details p {";
echo "font-size: 0.8rem;";
echo "color: #64748b;";
echo "margin: 2px 0 0 0;";
echo "}";
echo "";
echo ".feature-toggle {";
echo "position: relative;";
echo "width: 44px;";
echo "height: 24px;";
echo "background: #e2e8f0;";
echo "border-radius: 12px;";
echo "cursor: pointer;";
echo "transition: background 0.3s;";
echo "}";
echo "";
echo ".feature-toggle.active {";
echo "background: #f97316;";
echo "}";
echo "";
echo ".feature-toggle::after {";
echo "content: '';";
echo "position: absolute;";
echo "top: 2px;";
echo "left: 2px;";
echo "width: 20px;";
echo "height: 20px;";
echo "background: white;";
echo "border-radius: 50%;";
echo "transition: transform 0.3s;";
echo "}";
echo "";
echo ".feature-toggle.active::after {";
echo "transform: translateX(20px);";
echo "}";
echo "";
echo ".feature-price {";
echo "font-size: 0.9rem;";
echo "font-weight: 600;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".gift-card-modal {";
echo "position: fixed;";
echo "inset: 0;";
echo "background: rgba(0,0,0,0.5);";
echo "display: none;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 2000;";
echo "}";
echo "";
echo ".gift-card-modal-content {";
echo "background: white;";
echo "border-radius: 12px;";
echo "padding: 25px;";
echo "max-width: 450px;";
echo "width: 90%;";
echo "max-height: 80vh;";
echo "overflow-y: auto;";
echo "}";
echo "";
echo ".gift-card-options {";
echo "display: grid;";
echo "grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));";
echo "gap: 15px;";
echo "margin: 20px 0;";
echo "}";
echo "";
echo ".gift-card-option {";
echo "border: 2px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "padding: 15px;";
echo "text-align: center;";
echo "cursor: pointer;";
echo "transition: all 0.3s;";
echo "}";
echo "";
echo ".gift-card-option:hover {";
echo "border-color: #f97316;";
echo "background: #fff7ed;";
echo "}";
echo "";
echo ".gift-card-option.selected {";
echo "border-color: #f97316;";
echo "background: #fff7ed;";
echo "}";
echo "";
echo ".gift-card-option h4 {";
echo "margin: 0 0 5px 0;";
echo "color: #1e293b;";
echo "font-size: 1rem;";
echo "}";
echo "";
echo ".gift-card-option p {";
echo "margin: 0;";
echo "color: #64748b;";
echo "font-size: 0.8rem;";
echo "}";
echo "";
echo ".split-bill-modal {";
echo "position: fixed;";
echo "inset: 0;";
echo "background: rgba(0,0,0,0.5);";
echo "display: none;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 2000;";
echo "}";
echo "";
echo ".split-bill-modal-content {";
echo "background: white;";
echo "border-radius: 12px;";
echo "padding: 25px;";
echo "max-width: 400px;";
echo "width: 90%;";
echo "}";
echo "";
echo ".split-options {";
echo "margin: 20px 0;";
echo "}";
echo "";
echo ".split-option {";
echo "display: flex;";
echo "align-items: center;";
echo "padding: 12px;";
echo "margin: 8px 0;";
echo "border: 2px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "cursor: pointer;";
echo "transition: all 0.3s;";
echo "}";
echo "";
echo ".split-option:hover {";
echo "border-color: #f97316;";
echo "background: #fff7ed;";
echo "}";
echo "";
echo ".split-option.selected {";
echo "border-color: #f97316;";
echo "background: #fff7ed;";
echo "}";
echo "";
echo ".split-option input[type=\"radio\"] {";
echo "margin-right: 12px;";
echo "accent-color: #f97316;";
echo "}";
echo "";
echo ".split-option label {";
echo "flex: 1;";
echo "font-size: 0.9rem;";
echo "color: #1e293b;";
echo "cursor: pointer;";
echo "}";
echo "";
echo ".refund-policy {";
echo "background: #f0f9ff;";
echo "border: 1px solid #0ea5e9;";
echo "color: #0c4a6e;";
echo "padding: 12px;";
echo "border-radius: 8px;";
echo "margin: 15px 0;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".refund-policy i {";
echo "margin-right: 8px;";
echo "color: #0ea5e9;";
echo "}";
echo "";
echo ".applied-coupon {";
echo "background: #ecfdf5;";
echo "border: 1px solid #10b981;";
echo "border-radius: 8px;";
echo "padding: 12px;";
echo "margin-bottom: 15px;";
echo "display: none;";
echo "}";
echo "";
echo ".applied-coupon.show {";
echo "display: block;";
echo "}";
echo "";
echo ".coupon-info {";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "}";
echo "";
echo ".coupon-name {";
echo "font-weight: 600;";
echo "color: #065f46;";
echo "}";
echo "";
echo ".coupon-discount {";
echo "color: #10b981;";
echo "font-weight: 600;";
echo "}";
echo "";
echo ".remove-coupon {";
echo "background: none;";
echo "border: none;";
echo "color: #ef4444;";
echo "cursor: pointer;";
echo "font-size: 1.2rem;";
echo "}";
echo "</style>";
echo "</head>";
echo "<body>";
echo "<button id=\"dmBtn\" style=\"position:fixed;top:12px;right:12px;z-index:50;background:#f97316;color:#fff;border:none;border-radius:9999px;width:40px;height:40px;cursor:pointer\">🌓</button>";
echo "<header>";
echo "<div class=\"logo\">";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/2838/2838912.png\" alt=\"logo\"/>";
echo "<a href=\"swiggyhome.php\" style=\"color:#1e293b; text-decoration:none;\">SECURE CHECKOUT</a>";
echo "</div>";
echo "<nav class=\"nav-right\">";
echo "<a href=\"help.php\" class=\"help-btn\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "Help";
echo "</a>";
echo "<a href=\"my acc.php\">User</a>";
echo "</nav>";
echo "</header>";
echo "";
echo "<main class=\"container\">";
echo "<section class=\"checkout-left\">";
echo "<div class=\"step completed\">";
echo "<div class=\"step-icon\">1</div>";
echo "<h3>";
echo "Delivery address";
echo "<span class=\"change\" id=\"changeAddress\">CHANGE</span>";
echo "</h3>";
echo "<div id=\"addressDisplay\">";
echo "<p><b id=\"addressName\">College</b></p>";
echo "<p id=\"addressDetails\">amal jyothi college of engineering koovappally,kerala, P.O Kanjirapally – Erumely Road, Koovappally, Kerala 686518, India</p>";
echo "<p id=\"addressContact\" style=\"color: #64748b; font-size: 0.9rem;\">Phone: +91 98765 43210</p>";
echo "</div>";
echo "<span class=\"time\" id=\"deliveryTimeDisplay\">43 MINS</span>";
echo "</div>";
echo "";
echo "<div class=\"order-features\">";
echo "<h3>Order Features</h3>";
echo "<div class=\"feature-item\">";
echo "<div class=\"feature-info\">";
echo "<div class=\"feature-icon\">";
echo "<i class=\"fas fa-leaf\"></i>";
echo "</div>";
echo "<div class=\"feature-details\">";
echo "<h4>Eco-friendly Packing</h4>";
echo "<p>Biodegradable packaging materials</p>";
echo "</div>";
echo "</div>";
echo "<div class=\"feature-toggle\" id=\"ecoPackingToggle\"></div>";
echo "<div class=\"feature-price\">+₹5</div>";
echo "</div>";
echo "<div class=\"feature-item\">";
echo "<div class=\"feature-info\">";
echo "<div class=\"feature-icon\">";
echo "<i class=\"fas fa-gift\"></i>";
echo "</div>";
echo "<div class=\"feature-details\">";
echo "<h4>Personalized Gift Card</h4>";
echo "<p>Add a custom message</p>";
echo "</div>";
echo "</div>";
echo "<div class=\"feature-toggle\" id=\"giftCardToggle\"></div>";
echo "<div class=\"feature-price\">+₹25</div>";
echo "</div>";
echo "<div class=\"feature-item\">";
echo "<div class=\"feature-info\">";
echo "<div class=\"feature-icon\">";
echo "<i class=\"fas fa-users\"></i>";
echo "</div>";
echo "<div class=\"feature-details\">";
echo "<h4>Split Bill</h4>";
echo "<p>Share the cost with friends</p>";
echo "</div>";
echo "</div>";
echo "<div class=\"feature-toggle\" id=\"splitBillToggle\"></div>";
echo "<div class=\"feature-price\">Free</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"step\">";
echo "<div class=\"step-icon\">2</div>";
echo "<h3>More Options</h3>";
echo "<div class=\"scheduled-delivery active\">";
echo "<div class=\"delivery-option\">";
echo "<input type=\"radio\" id=\"now\" name=\"delivery-time\" checked>";
echo "<label for=\"now\">Deliver Now</label>";
echo "</div>";
echo "<div class=\"delivery-option\">";
echo "<input type=\"radio\" id=\"schedule\" name=\"delivery-time\">";
echo "<label for=\"schedule\">Schedule for later</label>";
echo "</div>";
echo "<div class=\"date-input-container\">";
echo "<input type=\"date\" class=\"date-input\" id=\"delivery-date\">";
echo "<i class=\"fas fa-calendar-alt calendar-icon\" id=\"calendar-toggle\"></i>";
echo "</div>";
echo "<div class=\"time-input-container\">";
echo "<input type=\"time\" class=\"time-input\" id=\"delivery-time\">";
echo "<i class=\"fas fa-clock clock-icon\"></i>";
echo "</div>";
echo "<div class=\"delivery-note\">";
echo "<i class=\"fas fa-info-circle\"></i> Scheduled orders cannot be cancelled once placed. Additional charges may apply for deliveries outside regular hours.";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"divider\"></div>";
echo "";
echo "<h3>Choose payment method</h3>";
echo "<div class=\"payment-methods\">";
echo "<div class=\"payment-method\">";
echo "<input type=\"radio\" id=\"card\" name=\"payment\" checked>";
echo "<label for=\"card\">Credit/Debit Card</label>";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/179/179431.png\" alt=\"card\">";
echo "</div>";
echo "<div class=\"payment-method\">";
echo "<input type=\"radio\" id=\"upi\" name=\"payment\">";
echo "<label for=\"upi\">UPI</label>";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/888/888871.png\" alt=\"upi\">";
echo "</div>";
echo "<div class=\"payment-method\">";
echo "<input type=\"radio\" id=\"netbanking\" name=\"payment\">";
echo "<label for=\"netbanking\">Net Banking</label>";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/1001/1001280.png\" alt=\"net banking\">";
echo "</div>";
echo "<div class=\"payment-method\">";
echo "<input type=\"radio\" id=\"cod\" name=\"payment\">";
echo "<label for=\"cod\">Cash on Delivery</label>";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/2331/2331966.png\" alt=\"cash\">";
echo "</div>";
echo "</div>";
echo "<button class=\"payment-button\">PROCEED TO PAY</button>";
echo "</div>";
echo "</section>";
echo "";
echo "<aside class=\"checkout-right\">";
echo "<div class=\"order-summary\">";
echo "<div class=\"section-heading\">Order Summary</div>";
echo "<div class=\"applied-coupon\" id=\"appliedCoupon\">";
echo "<div class=\"coupon-info\">";
echo "<div>";
echo "<div class=\"coupon-name\" id=\"appliedCouponName\">SWIGGY50</div>";
echo "<div class=\"coupon-desc\" id=\"appliedCouponDesc\">50% OFF up to ₹100</div>";
echo "</div>";
echo "<div>";
echo "<span class=\"coupon-discount\" id=\"appliedCouponDiscount\">-₹50</span>";
echo "<button class=\"remove-coupon\" id=\"removeCoupon\">×</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class=\"apply-coupon\" role=\"button\" tabindex=\"0\" id=\"applyCouponBtn\">";
echo "⚙ Apply Coupon";
echo "</div>";
echo "<div class=\"bill-details\"></div>";
echo "</div>";
echo "<div class=\"refund-policy\">";
echo "<i class=\"fas fa-shield-alt\"></i>";
echo "<strong>Refund Policy:</strong> Orders can be cancelled and refunded within 2 days of delivery. Scheduled orders can be cancelled up to 2 hours before delivery time.";
echo "<a href=\"#\" style=\"color: #0ea5e9; text-decoration: underline; margin-left: 5px;\">Read full policy</a>";
echo "</div>";
echo "</aside>";
echo "</main>";
echo "";
echo "<div class=\"address-modal\" id=\"addressModal\">";
echo "<div class=\"address-modal-content\">";
echo "<h2 style=\"margin-bottom: 20px; color: #1e293b;\">Change Delivery Address</h2>";
echo "<form class=\"address-form\" id=\"addressForm\">";
echo "<div class=\"form-row\">";
echo "<div class=\"form-group\">";
echo "<label for=\"fullName\">Full Name *</label>";
echo "<input type=\"text\" id=\"fullName\" name=\"fullName\" required>";
echo "</div>";
echo "<div class=\"form-group\">";
echo "<label for=\"phone\">Phone Number *</label>";
echo "<input type=\"tel\" id=\"phone\" name=\"phone\" required>";
echo "</div>";
echo "</div>";
echo "<div class=\"form-group\">";
echo "<label for=\"email\">Email Address</label>";
echo "<input type=\"email\" id=\"email\" name=\"email\">";
echo "</div>";
echo "<div class=\"form-group\">";
echo "<label for=\"streetAddress\">Street Address *</label>";
echo "<textarea id=\"streetAddress\" name=\"streetAddress\" rows=\"3\" required></textarea>";
echo "</div>";
echo "<div class=\"form-row\">";
echo "<div class=\"form-group\">";
echo "<label for=\"landmark\">Landmark</label>";
echo "<input type=\"text\" id=\"landmark\" name=\"landmark\" placeholder=\"e.g., Near Metro Station\">";
echo "</div>";
echo "<div class=\"form-group\">";
echo "<label for=\"pincode\">Pincode *</label>";
echo "<input type=\"text\" id=\"pincode\" name=\"pincode\" required>";
echo "</div>";
echo "</div>";
echo "<div class=\"form-group\">";
echo "<label for=\"city\">City *</label>";
echo "<input type=\"text\" id=\"city\" name=\"city\" required>";
echo "</div>";
echo "<div class=\"address-buttons\">";
echo "<button type=\"button\" class=\"btn btn-secondary\" id=\"cancelAddress\">Cancel</button>";
echo "<button type=\"submit\" class=\"btn btn-primary\">Save Address</button>";
echo "</div>";
echo "</form>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"coupon-modal\" id=\"couponModal\">";
echo "<div class=\"coupon-modal-content\">";
echo "<h2 style=\"margin-bottom: 20px; color: #1e293b;\">Apply Coupon</h2>";
echo "<div class=\"coupon-input-group\">";
echo "<input type=\"text\" id=\"couponCodeInput\" placeholder=\"Enter coupon code\">";
echo "<button id=\"applyCouponCode\">Apply</button>";
echo "</div>";
echo "<h3 style=\"margin-bottom: 15px; color: #1e293b; font-size: 1rem;\">Available Coupons</h3>";
echo "<div class=\"coupon-list\" id=\"couponList\">";
echo "<div class=\"coupon-item\" data-code=\"SWIGGY50\" data-discount=\"50\" data-type=\"percentage\" data-max=\"100\">";
echo "<div class=\"coupon-code\">SWIGGY50</div>";
echo "<div class=\"coupon-desc\">50% OFF up to ₹100</div>";
echo "</div>";
echo "<div class=\"coupon-item\" data-code=\"SAVE100\" data-discount=\"100\" data-type=\"fixed\">";
echo "<div class=\"coupon-code\">SAVE100</div>";
echo "<div class=\"coupon-desc\">₹100 OFF on orders above ₹500</div>";
echo "</div>";
echo "<div class=\"coupon-item\" data-code=\"FIRST30\" data-discount=\"30\" data-type=\"percentage\" data-max=\"200\">";
echo "<div class=\"coupon-code\">FIRST30</div>";
echo "<div class=\"coupon-desc\">30% OFF up to ₹200 for new users</div>";
echo "</div>";
echo "<div class=\"coupon-item\" data-code=\"DELIVERY0\" data-discount=\"0\" data-type=\"delivery\">";
echo "<div class=\"coupon-code\">DELIVERY0</div>";
echo "<div class=\"coupon-desc\">Free delivery on orders above ₹300</div>";
echo "</div>";
echo "<div class=\"coupon-item\" data-code=\"WEEKEND25\" data-discount=\"25\" data-type=\"percentage\" data-max=\"150\">";
echo "<div class=\"coupon-code\">WEEKEND25</div>";
echo "<div class=\"coupon-desc\">25% OFF up to ₹150 on weekends</div>";
echo "</div>";
echo "</div>";
echo "<div class=\"address-buttons\" style=\"margin-top: 20px;\">";
echo "<button type=\"button\" class=\"btn btn-secondary\" id=\"cancelCoupon\">Close</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"confirmation-modal\" id=\"confirmationModal\">";
echo "<div class=\"confirmation-content\">";
echo "<div class=\"success-icon\">✓</div>";
echo "<div class=\"confirmation-title\">Order Confirmed!</div>";
echo "<div class=\"confirmation-message\">";
echo "Your order has been placed successfully. You will receive a confirmation SMS shortly.";
echo "</div>";
echo "<button class=\"btn btn-primary\" id=\"trackOrderBtn\">Track Order</button>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"gift-card-modal\" id=\"giftCardModal\">";
echo "<div class=\"gift-card-modal-content\">";
echo "<h2 style=\"margin-bottom: 20px; color: #1e293b;\">Add Gift Card</h2>";
echo "<p style=\"color: #64748b; margin-bottom: 20px;\">Choose a gift card design and add a personalized message.</p>";
echo "<div class=\"gift-card-options\">";
echo "<div class=\"gift-card-option\" data-design=\"birthday\">";
echo "<h4>🎂 Birthday</h4>";
echo "<p>Perfect for celebrations</p>";
echo "</div>";
echo "<div class=\"gift-card-option\" data-design=\"anniversary\">";
echo "<h4>💕 Anniversary</h4>";
echo "<p>Celebrate special moments</p>";
echo "</div>";
echo "<div class=\"gift-card-option\" data-design=\"thankyou\">";
echo "<h4>🙏 Thank You</h4>";
echo "<p>Show appreciation</p>";
echo "</div>";
echo "<div class=\"gift-card-option\" data-design=\"congratulations\">";
echo "<h4>🎉 Congratulations</h4>";
echo "<p>Celebrate achievements</p>";
echo "</div>";
echo "<div class=\"gift-card-option\" data-design=\"getwell\">";
echo "<h4>🌻 Get Well Soon</h4>";
echo "<p>Wish speedy recovery</p>";
echo "</div>";
echo "<div class=\"gift-card-option\" data-design=\"custom\">";
echo "<h4>✨ Custom</h4>";
echo "<p>Your own message</p>";
echo "</div>";
echo "</div>";
echo "<div class=\"form-group\">";
echo "<label for=\"giftMessage\">Personal Message (Optional)</label>";
echo "<textarea id=\"giftMessage\" placeholder=\"Write a personal message for the recipient...\" rows=\"3\"></textarea>";
echo "</div>";
echo "<div class=\"address-buttons\">";
echo "<button type=\"button\" class=\"btn btn-secondary\" id=\"cancelGiftCard\">Cancel</button>";
echo "<button type=\"button\" class=\"btn btn-primary\" id=\"addGiftCard\">Add Gift Card (+₹25)</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"split-bill-modal\" id=\"splitBillModal\">";
echo "<div class=\"split-bill-modal-content\">";
echo "<h2 style=\"margin-bottom: 20px; color: #1e293b;\">Split Bill</h2>";
echo "<p style=\"color: #64748b; margin-bottom: 20px;\">Choose how you want to split the bill with your friends.</p>";
echo "<div class=\"split-options\">";
echo "<div class=\"split-option\">";
echo "<input type=\"radio\" name=\"splitMethod\" value=\"equal\" id=\"splitEqual\">";
echo "<label for=\"splitEqual\">Split equally among all</label>";
echo "</div>";
echo "<div class=\"split-option\">";
echo "<input type=\"radio\" name=\"splitMethod\" value=\"custom\" id=\"splitCustom\">";
echo "<label for=\"splitCustom\">Custom split amounts</label>";
echo "</div>";
echo "<div class=\"split-option\">";
echo "<input type=\"radio\" name=\"splitMethod\" value=\"items\" id=\"splitItems\">";
echo "<label for=\"splitItems\">Split by items ordered</label>";
echo "</div>";
echo "</div>";
echo "<div class=\"form-group\" id=\"splitDetails\" style=\"display: none;\">";
echo "<label for=\"splitCount\">Number of people</label>";
echo "<input type=\"number\" id=\"splitCount\" min=\"2\" max=\"10\" placeholder=\"2\">";
echo "</div>";
echo "<div class=\"address-buttons\">";
echo "<button type=\"button\" class=\"btn btn-secondary\" id=\"cancelSplitBill\">Cancel</button>";
echo "<button type=\"button\" class=\"btn btn-primary\" id=\"confirmSplitBill\">Enable Split Bill</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<script>";
echo "// Dark mode";
echo "(function(){";
echo "const saved = localStorage.getItem('theme');";
echo "if(saved === 'dark') document.documentElement.classList.add('dark');";
echo "document.getElementById('dmBtn').addEventListener('click', ()=>{";
echo "document.documentElement.classList.toggle('dark');";
echo "localStorage.setItem('theme', document.documentElement.classList.contains('dark') ? 'dark' : 'light');";
echo "});";
echo "})();";
echo "";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "// Set user name in header if available";
echo "(function(){";
echo "const nav = document.querySelector('nav.nav-right a[href=\"my acc.php\"]');";
echo "const savedName = localStorage.getItem('userName');";
echo "if (nav && savedName && savedName.trim()) nav.textContent = savedName;";
echo "})();";
echo "";
echo "// ---- Cart rendering from localStorage ----";
echo "function getCart(){ try { return JSON.parse(localStorage.getItem('cart')||'[]'); } catch { return []; } }";
echo "function saveCart(items){ localStorage.setItem('cart', JSON.stringify(items)); }";
echo "";
echo "const orderSummary = document.querySelector('.order-summary');";
echo "const billDetails = orderSummary.querySelector('.bill-details');";
echo "";
echo "function renderCart(){";
echo "const cart = getCart();";
echo "const listContainer = orderSummary.querySelector('.cart-list') || document.createElement('div');";
echo "listContainer.className = 'cart-list';";
echo "listContainer.innerHTML = '';";
echo "";
echo "let itemTotal = 0;";
echo "";
echo "cart.forEach((item, idx) => {";
echo "const row = document.createElement('div');";
echo "row.className = 'food-item';";
echo "";
echo "const img = document.createElement('img');";
echo "img.src = item.image || 'pay.avif';";
echo "img.alt = item.title || 'Item';";
echo "";
echo "const details = document.createElement('div');";
echo "details.className = 'food-details';";
echo "";
echo "const title = document.createElement('p');";
echo "title.className = 'food-title';";
echo "title.textContent = item.title || 'Item';";
echo "";
echo "const sub = document.createElement('p');";
echo "sub.className = 'food-location';";
echo "sub.textContent = (item.badge ? (item.badge + ' • ') : '') + (item.timeNote || '');";
echo "";
echo "const line = document.createElement('div');";
echo "line.className = 'choice-container';";
echo "";
echo "const qty = document.createElement('div');";
echo "qty.className = 'quantity-picker';";
echo "const dec = document.createElement('button'); dec.textContent = '−';";
echo "const qtyVal = document.createElement('span'); qtyVal.textContent = String(item.qty || 1);";
echo "const inc = document.createElement('button'); inc.textContent = '+';";
echo "qty.appendChild(dec); qty.appendChild(qtyVal); qty.appendChild(inc);";
echo "";
echo "const price = document.createElement('span');";
echo "price.className = 'price';";
echo "price.textContent = '₹' + (item.price * (item.qty || 1));";
echo "";
echo "const removeBtn = document.createElement('button');";
echo "removeBtn.textContent = 'Remove';";
echo "removeBtn.style = 'margin-left:8px; border:1px solid #e2e8f0; background:#fff; padding:6px 10px; border-radius:6px; cursor:pointer; color:#475569;';";
echo "";
echo "line.appendChild(qty);";
echo "line.appendChild(price);";
echo "line.appendChild(removeBtn);";
echo "";
echo "details.appendChild(title);";
echo "details.appendChild(sub);";
echo "details.appendChild(line);";
echo "";
echo "row.appendChild(img);";
echo "row.appendChild(details);";
echo "";
echo "inc.addEventListener('click', () => {";
echo "const c = getCart();";
echo "c[idx].qty = Math.min(20, (c[idx].qty||1)+1);";
echo "saveCart(c);";
echo "renderCart();";
echo "});";
echo "dec.addEventListener('click', () => {";
echo "const c = getCart();";
echo "c[idx].qty = Math.max(1, (c[idx].qty||1)-1);";
echo "saveCart(c);";
echo "renderCart();";
echo "});";
echo "removeBtn.addEventListener('click', () => {";
echo "const c = getCart();";
echo "c.splice(idx,1);";
echo "saveCart(c);";
echo "renderCart();";
echo "});";
echo "";
echo "listContainer.appendChild(row);";
echo "";
echo "itemTotal += item.price * (item.qty || 1);";
echo "});";
echo "";
echo "const firstSummaryChild = orderSummary.firstElementChild?.nextElementSibling;";
echo "if(firstSummaryChild && firstSummaryChild.classList.contains('food-item')){";
echo "const demoItems = orderSummary.querySelectorAll('.food-item');";
echo "demoItems.forEach(n => n.remove());";
echo "}";
echo "orderSummary.insertBefore(listContainer, billDetails);";
echo "";
echo "const deliveryFee = cart.length ? 48 : 0;";
echo "const taxes = Math.round(itemTotal * 0.05);";
echo "const total = itemTotal + deliveryFee + taxes;";
echo "";
echo "billDetails.innerHTML = ''+";
echo "'<div class=\"bill-row\"><span>Item Total</span> <span>₹'+ itemTotal +'</span></div>'+";
echo "'<div class=\"bill-row\"><span>Delivery Fee | 4.5 kms</span> <span>₹'+ deliveryFee +'</span></div>'+";
echo "'<div class=\"bill-row\"><span>GST & Other Charges</span> <span>₹'+ taxes +'</span></div>'+";
echo "'<div class=\"bill-row total\"><span>TO PAY</span> <span>₹'+ total +'</span></div>';";
echo "}";
echo "";
echo "renderCart();";
echo "";
echo "// ---- Scheduled delivery logic ----";
echo "const deliverNow = document.getElementById('now');";
echo "const schedule = document.getElementById('schedule');";
echo "const dateContainer = document.querySelector('.date-input-container');";
echo "const timeContainer = document.querySelector('.time-input-container');";
echo "const dateInput = document.getElementById('delivery-date');";
echo "const timeInput = document.getElementById('delivery-time');";
echo "const deliveryTimeDisplay = document.getElementById('deliveryTimeDisplay');";
echo "const now = new Date();";
echo "const todayStr = now.toISOString().split('T')[0];";
echo "";
echo "// Add a 30-minute buffer for same-day scheduling";
echo "function getMinTimeForToday() {";
echo "const bufferMinutes = 30;";
echo "const minTime = new Date(now.getTime() + bufferMinutes * 60000);";
echo "return minTime.toTimeString().split(' ')[0].slice(0, 5);";
echo "}";
echo "";
echo "dateInput.min = todayStr;";
echo "";
echo "dateInput.addEventListener('change', function() {";
echo "if (this.value === todayStr) {";
echo "timeInput.min = getMinTimeForToday();";
echo "} else {";
echo "timeInput.min = '00:00';";
echo "}";
echo "if (timeInput.value && timeInput.value < timeInput.min && this.value === todayStr) {";
echo "timeInput.value = timeInput.min;";
echo "}";
echo "updateDeliveryTimeDisplay();";
echo "});";
echo "";
echo "deliverNow.addEventListener('change', function() {";
echo "if (this.checked) {";
echo "dateContainer.style.display = 'none';";
echo "timeContainer.style.display = 'none';";
echo "dateInput.disabled = true;";
echo "timeInput.disabled = true;";
echo "deliveryTimeDisplay.textContent = '43 MINS';";
echo "deliveryTimeDisplay.style.color = '#10b981';";
echo "}";
echo "});";
echo "";
echo "schedule.addEventListener('change', function() {";
echo "if (this.checked) {";
echo "dateContainer.style.display = 'block';";
echo "timeContainer.style.display = 'block';";
echo "dateInput.disabled = false;";
echo "timeInput.disabled = false;";
echo "if (!dateInput.value) {";
echo "dateInput.value = todayStr;";
echo "timeInput.min = getMinTimeForToday();";
echo "}";
echo "if (!timeInput.value || (dateInput.value === todayStr && timeInput.value < timeInput.min)) {";
echo "timeInput.value = getMinTimeForToday();";
echo "}";
echo "}";
echo "updateDeliveryTimeDisplay();";
echo "});";
echo "";
echo "function updateDeliveryTimeDisplay() {";
echo "if (deliverNow.checked) {";
echo "deliveryTimeDisplay.textContent = '43 MINS';";
echo "deliveryTimeDisplay.style.color = '#10b981';";
echo "} else if (schedule.checked) {";
echo "const deliveryDate = dateInput.value;";
echo "const deliveryTime = timeInput.value;";
echo "if (deliveryDate && deliveryTime) {";
echo "const scheduledDt = new Date(deliveryDate + 'T' + deliveryTime + ':00');";
echo "const diffMs = scheduledDt - now;";
echo "if (diffMs > 30 * 60000) {";
echo "const hours = Math.floor(diffMs / 3600000);";
echo "const mins = Math.ceil((diffMs % 3600000) / 60000);";
echo "deliveryTimeDisplay.textContent = hours > 0 ? `${hours} HR ${mins} MINS` : `${mins} MINS`;";
echo "deliveryTimeDisplay.style.color = '#10b981';";
echo "} else {";
echo "deliveryTimeDisplay.textContent = 'Please select a future time';";
echo "deliveryTimeDisplay.style.color = '#ef4444';";
echo "}";
echo "} else {";
echo "deliveryTimeDisplay.textContent = 'Select date and time';";
echo "deliveryTimeDisplay.style.color = '#ef4444';";
echo "}";
echo "}";
echo "}";
echo "";
echo "timeInput.addEventListener('change', updateDeliveryTimeDisplay);";
echo "";
echo "if (schedule.checked) {";
echo "dateContainer.style.display = 'block';";
echo "timeContainer.style.display = 'block';";
echo "dateInput.disabled = false;";
echo "timeInput.disabled = false;";
echo "if (!dateInput.value) dateInput.value = todayStr;";
echo "if (!timeInput.value) timeInput.value = getMinTimeForToday();";
echo "}";
echo "updateDeliveryTimeDisplay();";
echo "";
echo "// ---- Address Management ----";
echo "let currentAddress = {";
echo "name: 'College',";
echo "phone: '+91 98765 43210',";
echo "email: '',";
echo "street: 'amal jyothi college of engineering koovappally,kerala, P.O Kanjirapally – Erumely Road, Koovappally, Kerala 686518, India',";
echo "landmark: '',";
echo "pincode: '686518',";
echo "city: 'Kottayam'";
echo "};";
echo "";
echo "function getCurrentAddress() {";
echo "return currentAddress;";
echo "}";
echo "";
echo "function updateAddressDisplay() {";
echo "document.getElementById('addressName').textContent = currentAddress.name;";
echo "document.getElementById('addressDetails').textContent = currentAddress.street;";
echo "document.getElementById('addressContact').textContent = `Phone: ${currentAddress.phone}`;";
echo "}";
echo "";
echo "document.getElementById('changeAddress').addEventListener('click', () => {";
echo "document.getElementById('fullName').value = currentAddress.name;";
echo "document.getElementById('phone').value = currentAddress.phone;";
echo "document.getElementById('email').value = currentAddress.email;";
echo "document.getElementById('streetAddress').value = currentAddress.street;";
echo "document.getElementById('landmark').value = currentAddress.landmark;";
echo "document.getElementById('pincode').value = currentAddress.pincode;";
echo "document.getElementById('city').value = currentAddress.city;";
echo "document.getElementById('addressModal').style.display = 'flex';";
echo "});";
echo "";
echo "document.getElementById('cancelAddress').addEventListener('click', () => {";
echo "document.getElementById('addressModal').style.display = 'none';";
echo "});";
echo "";
echo "document.getElementById('addressForm').addEventListener('submit', (e) => {";
echo "e.preventDefault();";
echo "currentAddress = {";
echo "name: document.getElementById('fullName').value,";
echo "phone: document.getElementById('phone').value,";
echo "email: document.getElementById('email').value,";
echo "street: document.getElementById('streetAddress').value,";
echo "landmark: document.getElementById('landmark').value,";
echo "pincode: document.getElementById('pincode').value,";
echo "city: document.getElementById('city').value";
echo "};";
echo "updateAddressDisplay();";
echo "document.getElementById('addressModal').style.display = 'none';";
echo "});";
echo "";
echo "// ---- Coupon System ----";
echo "let appliedCoupon = null;";
echo "";
echo "function calculateTotal() {";
echo "const cart = getCart();";
echo "let itemTotal = 0;";
echo "cart.forEach(item => {";
echo "itemTotal += item.price * (item.qty || 1);";
echo "});";
echo "";
echo "let featuresCost = 0;";
echo "if (orderFeatures.ecoPacking) featuresCost += 5;";
echo "if (orderFeatures.giftCard) featuresCost += 25;";
echo "";
echo "const subtotal = itemTotal + featuresCost;";
echo "const deliveryFee = cart.length ? 48 : 0;";
echo "let discountAmount = 0;";
echo "";
echo "if (appliedCoupon) {";
echo "if (appliedCoupon.type === 'percentage') {";
echo "discountAmount = Math.min((subtotal * appliedCoupon.discount / 100), appliedCoupon.max || Infinity);";
echo "} else if (appliedCoupon.type === 'fixed') {";
echo "discountAmount = appliedCoupon.discount;";
echo "} else if (appliedCoupon.type === 'delivery') {";
echo "discountAmount = deliveryFee;";
echo "}";
echo "}";
echo "";
echo "const taxableAmount = subtotal - discountAmount;";
echo "const taxes = Math.round(taxableAmount * 0.05);";
echo "const selectedPayment = document.querySelector('input[name=\"payment\"]:checked');";
echo "const codCharge = (selectedPayment && selectedPayment.id === 'cod') ? 10 : 0;";
echo "";
echo "return Math.max(0, taxableAmount + taxes + deliveryFee + codCharge);";
echo "}";
echo "";
echo "function updateBillDetails() {";
echo "const cart = getCart();";
echo "let itemTotal = 0;";
echo "cart.forEach(item => {";
echo "itemTotal += item.price * (item.qty || 1);";
echo "});";
echo "";
echo "let featuresCost = 0;";
echo "if (orderFeatures.ecoPacking) featuresCost += 5;";
echo "if (orderFeatures.giftCard) featuresCost += 25;";
echo "";
echo "const subtotal = itemTotal + featuresCost;";
echo "let deliveryFee = cart.length ? 48 : 0;";
echo "let discountAmount = 0;";
echo "";
echo "if (appliedCoupon) {";
echo "if (appliedCoupon.type === 'percentage') {";
echo "discountAmount = Math.min((subtotal * appliedCoupon.discount / 100), appliedCoupon.max || Infinity);";
echo "} else if (appliedCoupon.type === 'fixed') {";
echo "discountAmount = appliedCoupon.discount;";
echo "} else if (appliedCoupon.type === 'delivery') {";
echo "discountAmount = deliveryFee;";
echo "deliveryFee = 0;";
echo "}";
echo "}";
echo "";
echo "const taxableAmount = subtotal - discountAmount + deliveryFee;";
echo "const gst = Math.round(taxableAmount * 0.18);";
echo "const selectedPayment = document.querySelector('input[name=\"payment\"]:checked');";
echo "const codCharge = (selectedPayment && selectedPayment.id === 'cod') ? 10 : 0;";
echo "";
echo "const total = taxableAmount + gst + codCharge;";
echo "";
echo "const billDetailsEl = document.querySelector('.bill-details');";
echo "let billHTML = `";
echo "<div class=\"bill-row\"><span>Item Total</span> <span>₹${itemTotal}</span></div>";
echo "<div class=\"bill-row\"><span>Delivery Fee | 4.5 kms</span> <span>₹${deliveryFee}</span></div>";
echo "`;";
echo "";
echo "if (discountAmount > 0) {";
echo "billHTML += `<div class=\"bill-row\" style=\"color: #10b981;\"><span>Discount (${appliedCoupon.code})</span> <span>-₹${Math.round(discountAmount)}</span></div>`;";
echo "}";
echo "";
echo "if (featuresCost > 0) {";
echo "billHTML += `<div class=\"bill-row\"><span>Order Features</span> <span>+₹${featuresCost}</span></div>`;";
echo "}";
echo "";
echo "billHTML += `<div class=\"bill-row\"><span>GST (18%)</span> <span>₹${gst}</span></div>`;";
echo "";
echo "if (codCharge > 0) {";
echo "billHTML += `<div class=\"bill-row cod-charge\"><span>Cash on Delivery Charge</span> <span>₹${codCharge}</span></div>`;";
echo "}";
echo "";
echo "billHTML += `<div class=\"bill-row total\"><span>TO PAY</span> <span>₹${total}</span></div>`;";
echo "";
echo "billDetailsEl.innerHTML = billHTML;";
echo "}";
echo "";
echo "document.getElementById('applyCouponBtn').addEventListener('click', () => {";
echo "document.getElementById('couponModal').style.display = 'flex';";
echo "});";
echo "";
echo "document.getElementById('cancelCoupon').addEventListener('click', () => {";
echo "document.getElementById('couponModal').style.display = 'none';";
echo "});";
echo "";
echo "document.getElementById('applyCouponCode').addEventListener('click', () => {";
echo "const code = document.getElementById('couponCodeInput').value.trim().toUpperCase();";
echo "applyCoupon(code);";
echo "});";
echo "";
echo "document.getElementById('couponCodeInput').addEventListener('keypress', (e) => {";
echo "if (e.key === 'Enter') {";
echo "const code = document.getElementById('couponCodeInput').value.trim().toUpperCase();";
echo "applyCoupon(code);";
echo "}";
echo "});";
echo "";
echo "document.querySelectorAll('.coupon-item').forEach(item => {";
echo "item.addEventListener('click', () => {";
echo "const code = item.dataset.code;";
echo "document.getElementById('couponCodeInput').value = code;";
echo "applyCoupon(code);";
echo "});";
echo "});";
echo "";
echo "function applyCoupon(code) {";
echo "const couponItem = document.querySelector(`[data-code=\"${code}\"]`);";
echo "if (!couponItem) {";
echo "alert('Invalid coupon code!');";
echo "return;";
echo "}";
echo "";
echo "const cart = getCart();";
echo "const itemTotal = cart.reduce((sum, item) => sum + (item.price * (item.qty || 1)), 0);";
echo "";
echo "if (code === 'SAVE100' && itemTotal < 500) {";
echo "alert('This coupon requires minimum order value of ₹500');";
echo "return;";
echo "}";
echo "if (code === 'DELIVERY0' && itemTotal < 300) {";
echo "alert('This coupon requires minimum order value of ₹300');";
echo "return;";
echo "}";
echo "";
echo "appliedCoupon = {";
echo "code: code,";
echo "discount: parseInt(couponItem.dataset.discount),";
echo "type: couponItem.dataset.type,";
echo "max: couponItem.dataset.max ? parseInt(couponItem.dataset.max) : null";
echo "};";
echo "";
echo "document.getElementById('appliedCouponName').textContent = code;";
echo "document.getElementById('appliedCouponDesc').textContent = couponItem.querySelector('.coupon-desc').textContent;";
echo "";
echo "let discountText = '';";
echo "if (appliedCoupon.type === 'percentage') {";
echo "discountText = `-₹${Math.min((itemTotal * appliedCoupon.discount / 100), appliedCoupon.max || Infinity)}`;";
echo "} else if (appliedCoupon.type === 'fixed') {";
echo "discountText = `-₹${appliedCoupon.discount}`;";
echo "} else if (appliedCoupon.type === 'delivery') {";
echo "discountText = 'Free Delivery';";
echo "}";
echo "document.getElementById('appliedCouponDiscount').textContent = discountText;";
echo "";
echo "document.getElementById('appliedCoupon').classList.add('show');";
echo "document.getElementById('applyCouponBtn').style.display = 'none';";
echo "document.getElementById('couponModal').style.display = 'none';";
echo "";
echo "updateBillDetails();";
echo "}";
echo "";
echo "document.getElementById('removeCoupon').addEventListener('click', () => {";
echo "appliedCoupon = null;";
echo "document.getElementById('appliedCoupon').classList.remove('show');";
echo "document.getElementById('applyCouponBtn').style.display = 'block';";
echo "updateBillDetails();";
echo "});";
echo "";
echo "// ---- Order Confirmation and Tracking ----";
echo "const payBtn = document.querySelector('.payment-button');";
echo "payBtn.addEventListener('click', function() {";
echo "const cart = getCart();";
echo "if (!cart.length) {";
echo "alert('Your cart is empty.');";
echo "return;";
echo "}";
echo "";
echo "if (schedule.checked) {";
echo "const deliveryDate = dateInput.value;";
echo "const deliveryTime = timeInput.value;";
echo "if (!deliveryDate || !deliveryTime) {";
echo "alert('Please select delivery date and time.');";
echo "return;";
echo "}";
echo "const scheduledDateTime = new Date(deliveryDate + 'T' + deliveryTime + ':00');";
echo "const minTime = new Date(now.getTime() + 30 * 60000);";
echo "if (scheduledDateTime <= minTime) {";
echo "alert('Please select a delivery time at least 30 minutes from now.');";
echo "return;";
echo "}";
echo "}";
echo "";
echo "let estimatedDelivery;";
echo "let scheduledDateTimeReadable = null;";
echo "if (schedule.checked) {";
echo "const deliveryDate = dateInput.value;";
echo "const deliveryTime = timeInput.value;";
echo "estimatedDelivery = new Date(deliveryDate + 'T' + deliveryTime + ':00').toISOString();";
echo "scheduledDateTimeReadable = new Date(deliveryDate + 'T' + deliveryTime + ':00').toLocaleString('en-IN', {";
echo "weekday: 'short',";
echo "month: 'short',";
echo "day: 'numeric',";
echo "hour: 'numeric',";
echo "minute: 'numeric',";
echo "hour12: true";
echo "});";
echo "} else {";
echo "estimatedDelivery = new Date(now.getTime() + 43 * 60000).toISOString();";
echo "scheduledDateTimeReadable = new Date(now.getTime() + 43 * 60000).toLocaleString('en-IN', {";
echo "weekday: 'short',";
echo "month: 'short',";
echo "day: 'numeric',";
echo "hour: 'numeric',";
echo "minute: 'numeric',";
echo "hour12: true";
echo "});";
echo "}";
echo "";
echo "const orderData = {";
echo "id: 'ORD' + Date.now(),";
echo "items: cart,";
echo "address: getCurrentAddress(),";
echo "paymentMethod: document.querySelector('input[name=\"payment\"]:checked').id,";
echo "total: calculateTotal(),";
echo "status: 'confirmed',";
echo "timestamp: new Date().toISOString(),";
echo "estimatedDelivery: estimatedDelivery,";
echo "isScheduled: schedule.checked,";
echo "scheduledDateTimeReadable: scheduledDateTimeReadable,";
echo "orderFeatures: orderFeatures,";
echo "appliedCoupon: appliedCoupon";
echo "};";
echo "";
echo "const orders = JSON.parse(localStorage.getItem('orders') || '[]');";
echo "orders.unshift(orderData);";
echo "localStorage.setItem('orders', JSON.stringify(orders));";
echo "localStorage.removeItem('cart');";
echo "";
echo "document.getElementById('confirmationModal').style.display = 'flex';";
echo "});";
echo "";
echo "document.getElementById('trackOrderBtn').addEventListener('click', () => {";
echo "document.getElementById('confirmationModal').style.display = 'none';";
echo "window.location.href = 'tracking.php';";
echo "});";
echo "";
echo "// ---- Order Features Functionality ----";
echo "const ecoPackingToggle = document.getElementById('ecoPackingToggle');";
echo "const giftCardToggle = document.getElementById('giftCardToggle');";
echo "const splitBillToggle = document.getElementById('splitBillToggle');";
echo "const giftCardModal = document.getElementById('giftCardModal');";
echo "const splitBillModal = document.getElementById('splitBillModal');";
echo "";
echo "let orderFeatures = {";
echo "ecoPacking: false,";
echo "giftCard: false,";
echo "splitBill: false,";
echo "giftCardDesign: '',";
echo "giftCardMessage: '',";
echo "splitBillMethod: '',";
echo "splitBillCount: 2";
echo "};";
echo "";
echo "ecoPackingToggle.addEventListener('click', () => {";
echo "orderFeatures.ecoPacking = !orderFeatures.ecoPacking;";
echo "ecoPackingToggle.classList.toggle('active', orderFeatures.ecoPacking);";
echo "updateBillDetails();";
echo "});";
echo "";
echo "giftCardToggle.addEventListener('click', () => {";
echo "if (!orderFeatures.giftCard) {";
echo "giftCardModal.style.display = 'flex';";
echo "} else {";
echo "orderFeatures.giftCard = false;";
echo "giftCardToggle.classList.remove('active');";
echo "updateBillDetails();";
echo "}";
echo "});";
echo "";
echo "splitBillToggle.addEventListener('click', () => {";
echo "if (!orderFeatures.splitBill) {";
echo "splitBillModal.style.display = 'flex';";
echo "} else {";
echo "orderFeatures.splitBill = false;";
echo "splitBillToggle.classList.remove('active');";
echo "updateBillDetails();";
echo "}";
echo "});";
echo "";
echo "const giftCardOptions = document.querySelectorAll('.gift-card-option');";
echo "let selectedGiftDesign = '';";
echo "";
echo "giftCardOptions.forEach(option => {";
echo "option.addEventListener('click', () => {";
echo "giftCardOptions.forEach(opt => opt.classList.remove('selected'));";
echo "option.classList.add('selected');";
echo "selectedGiftDesign = option.dataset.design;";
echo "});";
echo "});";
echo "";
echo "document.getElementById('addGiftCard').addEventListener('click', () => {";
echo "if (selectedGiftDesign) {";
echo "orderFeatures.giftCard = true;";
echo "orderFeatures.giftCardDesign = selectedGiftDesign;";
echo "orderFeatures.giftCardMessage = document.getElementById('giftMessage').value;";
echo "giftCardToggle.classList.add('active');";
echo "giftCardModal.style.display = 'none';";
echo "updateBillDetails();";
echo "} else {";
echo "alert('Please select a gift card design.');";
echo "}";
echo "});";
echo "";
echo "document.getElementById('cancelGiftCard').addEventListener('click', () => {";
echo "giftCardModal.style.display = 'none';";
echo "});";
echo "";
echo "const splitOptions = document.querySelectorAll('.split-option');";
echo "const splitDetails = document.getElementById('splitDetails');";
echo "let selectedSplitMethod = '';";
echo "";
echo "splitOptions.forEach(option => {";
echo "option.addEventListener('click', () => {";
echo "splitOptions.forEach(opt => opt.classList.remove('selected'));";
echo "option.classList.add('selected');";
echo "selectedSplitMethod = option.querySelector('input').value;";
echo "if (selectedSplitMethod === 'equal' || selectedSplitMethod === 'custom') {";
echo "splitDetails.style.display = 'block';";
echo "} else {";
echo "splitDetails.style.display = 'none';";
echo "}";
echo "});";
echo "});";
echo "";
echo "document.getElementById('confirmSplitBill').addEventListener('click', () => {";
echo "if (selectedSplitMethod) {";
echo "orderFeatures.splitBill = true;";
echo "orderFeatures.splitBillMethod = selectedSplitMethod;";
echo "const splitCount = document.getElementById('splitCount').value;";
echo "orderFeatures.splitBillCount = splitCount ? parseInt(splitCount) : 2;";
echo "splitBillToggle.classList.add('active');";
echo "splitBillModal.style.display = 'none';";
echo "updateBillDetails();";
echo "} else {";
echo "alert('Please select a split method.');";
echo "}";
echo "});";
echo "";
echo "document.getElementById('cancelSplitBill').addEventListener('click', () => {";
echo "splitBillModal.style.display = 'none';";
echo "});";
echo "";
echo "document.querySelectorAll('input[name=\"payment\"]').forEach(radio => {";
echo "radio.addEventListener('change', updateBillDetails);";
echo "});";
echo "";
echo "document.addEventListener('click', (e) => {";
echo "if (e.target.classList.contains('address-modal')) {";
echo "document.getElementById('addressModal').style.display = 'none';";
echo "}";
echo "if (e.target.classList.contains('coupon-modal')) {";
echo "document.getElementById('couponModal').style.display = 'none';";
echo "}";
echo "if (e.target.classList.contains('confirmation-modal')) {";
echo "document.getElementById('confirmationModal').style.display = 'none';";
echo "}";
echo "if (e.target.classList.contains('gift-card-modal')) {";
echo "document.getElementById('giftCardModal').style.display = 'none';";
echo "}";
echo "if (e.target.classList.contains('split-bill-modal')) {";
echo "document.getElementById('splitBillModal').style.display = 'none';";
echo "}";
echo "});";
echo "});";
echo "</script>";
echo "</body>";
echo "</html>";
?>