<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"utf-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
echo "<title>Restaurant Details</title>";
echo "<script src=\"https://cdn.tailwindcss.com\"></script>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />";
echo "</head>";
echo "<body class=\"bg-gray-50\">";
echo "<header class=\"bg-white shadow-sm\">";
echo "<div class=\"container mx-auto px-4 py-4 flex justify-between items-center\">";
echo "<h1 id=\"restName\" class=\"text-2xl font-bold text-orange-600\">Restaurant Name</h1>";
echo "<div class=\"flex items-center gap-4\">";
echo "<a href=\"help.php\" class=\"flex items-center gap-2 px-3 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition text-sm\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "<span class=\"hidden sm:inline\">Help</span>";
echo "</a>";
echo "<div class=\"relative\">";
echo "<button id=\"cartBtn\" class=\"flex items-center\">";
echo "<i class=\"fas fa-shopping-cart text-xl\"></i>";
echo "<span id=\"cartCount\" class=\"ml-2 bg-orange-600 text-white rounded-full px-2 py-1\">0</span>";
echo "</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</header>";
echo "";
echo "<main class=\"container mx-auto px-4 py-8\">";
echo "<div class=\"mb-6\">";
echo "<img id=\"restHero\" src=\"\" alt=\"\" class=\"w-full rounded-xl shadow max-h-72 object-cover\"/>";
echo "</div>";
echo "<div id=\"aboutBox\" class=\"bg-white rounded-xl shadow p-4 mb-6\">";
echo "<div class=\"flex flex-col md:flex-row md:items-center md:justify-between gap-3\">";
echo "<div>";
echo "<div id=\"restCuisines\" class=\"text-gray-600\"></div>";
echo "<div id=\"restLocation\" class=\"text-gray-500 text-sm\"></div>";
echo "</div>";
echo "<div class=\"flex gap-4 text-sm\">";
echo "<div class=\"text-center\"><div class=\"font-bold\" id=\"restRating\">⭐ 4.4</div><div class=\"text-gray-500\">Rating</div></div>";
echo "<div class=\"text-center\"><div class=\"font-bold\" id=\"restEta\">--</div><div class=\"text-gray-500\">ETA</div></div>";
echo "<div class=\"text-center\"><div class=\"font-bold\" id=\"restCost\">--</div><div class=\"text-gray-500\">Cost for two</div></div>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div id=\"categoryChips\" class=\"flex flex-wrap gap-2 mb-4\"></div>";
echo "<div id=\"menuItems\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6\">";
echo "<!-- 20 KFC Items with image upload -->";
echo "<script>";
echo "const kfcItems = [";
echo "{ id: 'zinger', name: 'Zinger Burger', price: 149, description: 'Crispy chicken burger with spicy coating', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop&crop=center', category: 'Burgers' },";
echo "{ id: 'chicken_bucket', name: 'Chicken Bucket (8 pcs)', price: 399, description: '8 pieces of original recipe chicken', image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=300&fit=crop&crop=center', category: 'Chicken' },";
echo "{ id: 'popcorn', name: 'Popcorn Chicken', price: 129, description: 'Signature bite-sized chicken pieces', image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop&crop=center', category: 'Snacks' },";
echo "{ id: 'chicken_wings', name: 'Hot Wings (6 pcs)', price: 199, description: 'Spicy chicken wings', image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center', category: 'Chicken' },";
echo "{ id: 'chicken_strips', name: 'Chicken Strips (4 pcs)', price: 179, description: 'Tender chicken strips', image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=300&fit=crop&crop=center', category: 'Chicken' },";
echo "{ id: 'chicken_burger', name: 'Chicken Burger', price: 119, description: 'Classic chicken burger', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop&crop=center', category: 'Burgers' },";
echo "{ id: 'chicken_roll', name: 'Chicken Roll', price: 89, description: 'Spicy chicken wrapped in paratha', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop&crop=center', category: 'Rolls' },";
echo "{ id: 'chicken_wrap', name: 'Chicken Wrap', price: 139, description: 'Chicken wrapped in tortilla', image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop&crop=center', category: 'Wraps' },";
echo "{ id: 'fries', name: 'French Fries', price: 79, description: 'Golden crispy fries', image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=400&h=300&fit=crop&crop=center', category: 'Sides' },";
echo "{ id: 'chicken_nuggets', name: 'Chicken Nuggets (6 pcs)', price: 149, description: 'Bite-sized chicken nuggets', image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop&crop=center', category: 'Snacks' },";
echo "{ id: 'chicken_sandwich', name: 'Chicken Sandwich', price: 159, description: 'Grilled chicken sandwich', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop&crop=center', category: 'Sandwiches' },";
echo "{ id: 'chicken_curry', name: 'Chicken Curry Rice', price: 199, description: 'Spicy chicken curry with rice', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center', category: 'Rice Meals' },";
echo "{ id: 'chicken_biryani', name: 'Chicken Biryani', price: 229, description: 'Aromatic chicken biryani', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center', category: 'Rice Meals' },";
echo "{ id: 'chicken_lollipop', name: 'Chicken Lollipop (6 pcs)', price: 189, description: 'Spicy chicken lollipops', image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center', category: 'Starters' },";
echo "{ id: 'chicken_65', name: 'Chicken 65', price: 169, description: 'Spicy fried chicken pieces', image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop&crop=center', category: 'Starters' },";
echo "{ id: 'chicken_manchurian', name: 'Chicken Manchurian', price: 179, description: 'Indo-Chinese chicken dish', image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=300&fit=crop&crop=center', category: 'Starters' },";
echo "{ id: 'chicken_fried_rice', name: 'Chicken Fried Rice', price: 189, description: 'Chicken fried rice with vegetables', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center', category: 'Rice Meals' },";
echo "{ id: 'chicken_noodles', name: 'Chicken Noodles', price: 179, description: 'Spicy chicken noodles', image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=300&fit=crop&crop=center', category: 'Noodles' },";
echo "{ id: 'chicken_soup', name: 'Chicken Soup', price: 99, description: 'Hot and spicy chicken soup', image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop&crop=center', category: 'Soups' },";
echo "{ id: 'chicken_salad', name: 'Chicken Salad', price: 109, description: 'Fresh chicken salad', image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop&crop=center', category: 'Salads' }";
echo "];";
echo "function handleKfcImageUpload(event, idx) {";
echo "const file = event.target.files[0];";
echo "if (file) {";
echo "const reader = new FileReader();";
echo "reader.onload = function(e) {";
echo "document.getElementById('kfc-img-' + idx).src = e.target.result;";
echo "};";
echo "reader.readAsDataURL(file);";
echo "}";
echo "}";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "const menuItems = document.getElementById('menuItems');";
echo "menuItems.innerHTML = kfcItems.map((item, idx) => `";
echo "<div class='bg-white rounded-xl shadow p-4 flex flex-col items-center'>";
echo "<img id='kfc-img-${idx}' src='${item.image}' alt='${item.name}' class='w-32 h-32 object-cover rounded-lg mb-3 border' />";
echo "<label class='mb-2 text-sm text-gray-600 font-bold'>${item.name}</label>";
echo "<div class='text-xs text-gray-500 mb-2'>${item.description}</div>";
echo "<div class='mb-2 text-orange-600 font-semibold'>₹${item.price}</div>";
echo "<input type='file' accept='image/*' class='mb-2' onchange='handleKfcImageUpload(event, ${idx})' />";
echo "<button class='bg-orange-500 text-white px-4 py-1 rounded mt-2'>Add to Cart</button>";
echo "</div>";
echo "`).join('');";
echo "});";
echo "</script>";
echo "<!-- 20 Porch Grill Items -->";
echo "<script>";
echo "const porchGrillItems = [";
echo "{ id: 'alfaham', name: 'Al Faham', price: 249, description: 'Juicy charcoal grilled chicken', image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&h=300&fit=crop&crop=center', category: 'Grill' },";
echo "{ id: 'shawarma', name: 'Chicken Shawarma', price: 99, description: 'Arabian classic roll', image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop&crop=center', category: 'Shawarma' },";
echo "{ id: 'mutton_biryani', name: 'Mutton Biryani', price: 299, description: 'Aromatic mutton biryani', image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&h=300&fit=crop&crop=center', category: 'Biryani' },";
echo "{ id: 'chicken_biryani', name: 'Chicken Biryani', price: 229, description: 'Spicy chicken biryani', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center', category: 'Biryani' },";
echo "{ id: 'beef_biryani', name: 'Beef Biryani', price: 279, description: 'Tender beef biryani', image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop&crop=center', category: 'Biryani' },";
echo "{ id: 'grilled_chicken', name: 'Grilled Chicken', price: 199, description: 'Marinated grilled chicken', image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=300&fit=crop&crop=center', category: 'Grill' },";
echo "{ id: 'chicken_tikka', name: 'Chicken Tikka', price: 189, description: 'Tandoori chicken tikka', image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop&crop=center', category: 'Tandoor' },";
echo "{ id: 'mutton_tikka', name: 'Mutton Tikka', price: 239, description: 'Spicy mutton tikka', image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop&crop=center', category: 'Tandoor' },";
echo "{ id: 'fish_tikka', name: 'Fish Tikka', price: 219, description: 'Marinated fish tikka', image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop&crop=center', category: 'Seafood' },";
echo "{ id: 'prawn_tikka', name: 'Prawn Tikka', price: 259, description: 'Spicy prawn tikka', image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&h=300&fit=crop&crop=center', category: 'Seafood' },";
echo "{ id: 'chicken_kebab', name: 'Chicken Kebab', price: 179, description: 'Minced chicken kebab', image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop&crop=center', category: 'Kebabs' },";
echo "{ id: 'mutton_kebab', name: 'Mutton Kebab', price: 229, description: 'Spicy mutton kebab', image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop&crop=center', category: 'Kebabs' },";
echo "{ id: 'chicken_roll', name: 'Chicken Roll', price: 89, description: 'Spicy chicken roll', image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop&crop=center', category: 'Rolls' },";
echo "{ id: 'mutton_roll', name: 'Mutton Roll', price: 119, description: 'Tender mutton roll', image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop&crop=center', category: 'Rolls' },";
echo "{ id: 'chicken_mandi', name: 'Chicken Mandi', price: 299, description: 'Traditional chicken mandi', image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&h=300&fit=crop&crop=center', category: 'Mandi' },";
echo "{ id: 'mutton_mandi', name: 'Mutton Mandi', price: 349, description: 'Aromatic mutton mandi', image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop&crop=center', category: 'Mandi' },";
echo "{ id: 'chicken_majboos', name: 'Chicken Majboos', price: 279, description: 'Spiced chicken majboos', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center', category: 'Rice' },";
echo "{ id: 'mutton_majboos', name: 'Mutton Majboos', price: 329, description: 'Rich mutton majboos', image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop&crop=center', category: 'Rice' },";
echo "{ id: 'chicken_curry', name: 'Chicken Curry', price: 199, description: 'Spicy chicken curry', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop&crop=center', category: 'Curries' },";
echo "{ id: 'mutton_curry', name: 'Mutton Curry', price: 249, description: 'Tender mutton curry', image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&h=300&fit=crop&crop=center', category: 'Curries' }";
echo "];";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "const menuItems = document.getElementById('menuItems');";
echo "menuItems.innerHTML = porchGrillItems.map((item, idx) => `";
echo "<div class='bg-white rounded-xl shadow p-4 flex flex-col items-center'>";
echo "<img src='${item.image}' alt='${item.name}' class='w-32 h-32 object-cover rounded-lg mb-3 border' />";
echo "<label class='mb-2 text-sm text-gray-600 font-bold'>${item.name}</label>";
echo "<div class='text-xs text-gray-500 mb-2'>${item.description}</div>";
echo "<div class='mb-2 text-orange-600 font-semibold'>₹${item.price}</div>";
echo "<button class='bg-orange-500 text-white px-4 py-1 rounded mt-2'>Add to Cart</button>";
echo "</div>";
echo "`).join('');";
echo "});";
echo "</script>";
echo "</div>";
echo "</main>";
echo "";
echo "<!-- Cart Sidebar -->";
echo "<div id=\"cartSidebar\" class=\"fixed right-0 top-0 h-full w-80 bg-white shadow-lg transform translate-x-full transition-transform duration-300 ease-in-out\">";
echo "<div class=\"p-4\">";
echo "<div class=\"flex justify-between items-center mb-4\">";
echo "<h2 class=\"text-xl font-bold\">Your Cart</h2>";
echo "<button id=\"closeCart\" class=\"text-gray-500\"><i class=\"fas fa-times\"></i></button>";
echo "</div>";
echo "<div id=\"cartItems\" class=\"space-y-4\">";
echo "<!-- Cart items will be added here -->";
echo "</div>";
echo "<div class=\"mt-6 border-t pt-4\">";
echo "<div class=\"flex justify-between mb-2\">";
echo "<span>Subtotal:</span>";
echo "<span id=\"cartTotal\">₹0</span>";
echo "</div>";
echo "<button id=\"checkoutBtn\" class=\"w-full bg-orange-600 text-white py-2 rounded-md\">Checkout</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<!-- Floating MENU button and panel -->";
echo "<button id=\"menuFab\" class=\"fixed bottom-6 right-6 bg-black text-white w-16 h-16 rounded-full shadow-lg flex items-center justify-center text-sm\">MENU</button>";
echo "<div id=\"menuPanel\" class=\"fixed bottom-24 right-6 bg-white shadow-lg rounded-lg p-3 hidden max-h-80 overflow-auto\">";
echo "<div id=\"menuPanelList\" class=\"space-y-2\"></div>";
echo "</div>";
echo "";
echo "<script>";
echo "// Restaurant meta (about) and menus";
echo "const restaurantsMeta = {";
echo "'kfc': { cuisines: 'Burgers, Fast Food, Rolls & Wraps', location: 'Kanjirappally', rating: 4.3, eta: '25-30 mins', costForTwo: '₹400 for two' },";
echo "'porch_grill': { cuisines: 'Arabian, Grill, Biryani, Barbecue', location: 'Cheppumpara', rating: 4.6, eta: '35-40 mins', costForTwo: '₹500 for two' },";
echo "'cutiepie_cakes': { cuisines: 'Desserts, Bakery, Cafe', location: 'Kanjirappally', rating: 4.6, eta: '25-30 mins', costForTwo: '₹250 for two' },";
echo "'lazza_ice_cream': { cuisines: 'Ice Cream, Desserts', location: 'Kanjirappally', rating: 4.7, eta: '25-30 mins', costForTwo: '₹200 for two' },";
echo "'apple_bee': { cuisines: 'Chinese, Tandoor, Arabian', location: 'Kottayam Kumily Road', rating: 4.3, eta: '45-55 mins', costForTwo: '₹450 for two' },";
echo "'kottaram': { cuisines: 'Kerala, Biryani, Arabian', location: 'Kollam Theni Highway', rating: 4.3, eta: '35-40 mins', costForTwo: '₹500 for two' },";
echo "'cafe_cocoon': { cuisines: 'Continental, Arabian, Kebabs', location: 'Cheppumpara', rating: 4.4, eta: '50-60 mins', costForTwo: '₹350 for two' },";
echo "'funfee': { cuisines: 'Burgers, Desserts', location: 'Town Center', rating: 4.3, eta: '60-70 mins', costForTwo: '₹300 for two' },";
echo "'cafe_fargozi': { cuisines: 'Shawarma, Lebanese', location: 'Downtown', rating: 4.7, eta: '35-40 mins', costForTwo: '₹350 for two' },";
echo "'nanuha': { cuisines: 'South Indian, Dosa', location: 'City Center', rating: 4.5, eta: '40-50 mins', costForTwo: '₹200 for two' },";
echo "'tass_bakery': { cuisines: 'Cakes, Bakery', location: 'Kanjirapally', rating: 4.5, eta: '40-50 mins', costForTwo: '₹250 for two' },";
echo "'spice_haven': { cuisines: 'North Indian, Tandoor', location: 'City Center', rating: 4.4, eta: '30-35 mins', costForTwo: '₹500 for two' }";
echo "};";
echo "";
echo "function handleMenuImageUpload(event, idx) {";
echo "const file = event.target.files[0];";
echo "if (file) {";
echo "const reader = new FileReader();";
echo "reader.onload = function(e) {";
echo "document.getElementById('menu-img-' + idx).src = e.target.result;";
echo "};";
echo "reader.readAsDataURL(file);";
echo "}";
echo "}";
echo "";
echo "function renderMenuForRestaurant(restaurantKey) {";
echo "const menuItems = document.getElementById('menuItems');";
echo "const menu = menusByRestaurant[restaurantKey] || [];";
echo "menuItems.innerHTML = menu.map((item, idx) => `";
echo "<div class='bg-white rounded-xl shadow p-4 flex flex-col items-center'>";
echo "<img id='menu-img-${idx}' src='${item.image}' alt='${item.name}' class='w-32 h-32 object-cover rounded-lg mb-3 border' />";
echo "<label class='mb-2 text-sm text-gray-600 font-bold'>${item.name}</label>";
echo "<div class='text-xs text-gray-500 mb-2'>${item.description}</div>";
echo "<div class='mb-2 text-orange-600 font-semibold'>₹${item.price}</div>";
echo "<input type='file' accept='image/*' class='mb-2' onchange='handleMenuImageUpload(event, ${idx})' />";
echo "<button class='bg-orange-500 text-white px-4 py-1 rounded mt-2'>Add to Cart</button>";
echo "</div>";
echo "`).join('');";
echo "}";
echo "";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "// Get selected restaurant key from localStorage or default to 'kfc'";
echo "let selectedRestaurant = localStorage.getItem('selectedRestaurantKey') || 'kfc';";
echo "renderMenuForRestaurant(selectedRestaurant);";
echo "});";
echo "const cart = { items: [], total: 0 };";
echo "";
echo "// Render menu items, about, and categories";
echo "function renderMenu() {";
echo "const menuContainer = document.getElementById('menuItems');";
echo "const selected = JSON.parse(localStorage.getItem('selectedRestaurant') || '{}');";
echo "const list = menusByRestaurant[selected.id] || [];";
echo "// header";
echo "document.getElementById('restName').textContent = selected.name || 'Restaurant';";
echo "const hero = document.getElementById('restHero');";
echo "if (selected.image) { hero.src = selected.image; hero.alt = selected.name; }";
echo "// about";
echo "const meta = restaurantsMeta[selected.id] || {};";
echo "document.getElementById('restCuisines').textContent = meta.cuisines || '';";
echo "document.getElementById('restLocation').textContent = meta.location || '';";
echo "document.getElementById('restRating').textContent = '⭐ ' + (meta.rating || '4.4');";
echo "document.getElementById('restEta').textContent = meta.eta || '--';";
echo "document.getElementById('restCost').textContent = meta.costForTwo || '--';";
echo "// group by category";
echo "const byCategory = {};";
echo "list.forEach(i => { const c = i.category || 'Recommended'; (byCategory[c] ||= []).push(i); });";
echo "";
echo "// build chips and menu panel";
echo "const chips = document.getElementById('categoryChips');";
echo "const panelList = document.getElementById('menuPanelList');";
echo "chips.innerHTML = '';";
echo "panelList.innerHTML = '';";
echo "";
echo "Object.keys(byCategory).forEach(cat => {";
echo "const chip = document.createElement('button');";
echo "chip.className = 'px-3 py-1 rounded-full border text-sm hover:bg-gray-50';";
echo "chip.textContent = cat;";
echo "chip.addEventListener('click', () => {";
echo "const el = document.getElementById('sec-'+cat);";
echo "if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });";
echo "});";
echo "chips.appendChild(chip);";
echo "";
echo "const item = document.createElement('div');";
echo "item.className = 'text-sm cursor-pointer hover:underline';";
echo "item.textContent = cat;";
echo "item.addEventListener('click', () => {";
echo "const el = document.getElementById('sec-'+cat);";
echo "if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });";
echo "document.getElementById('menuPanel').classList.add('hidden');";
echo "});";
echo "panelList.appendChild(item);";
echo "});";
echo "";
echo "// render sections";
echo "menuContainer.innerHTML = '';";
echo "Object.entries(byCategory).forEach(([cat, items]) => {";
echo "const header = document.createElement('h2');";
echo "header.id = 'sec-'+cat;";
echo "header.className = 'col-span-full text-lg font-semibold text-gray-800 mt-6';";
echo "header.textContent = cat;";
echo "menuContainer.appendChild(header);";
echo "";
echo "items.forEach(item => {";
echo "const itemElement = document.createElement('div');";
echo "itemElement.className = 'bg-white p-4 rounded-lg shadow';";
echo "itemElement.innerHTML = `";
echo "<img src=\"${item.image || selected.image || ''}\" alt=\"${item.name}\" class=\"w-full h-40 object-cover rounded mb-3\" />";
echo "<h3 class=\"text-lg font-semibold\">${item.name}</h3>";
echo "<p class=\"text-gray-600\">${item.description}</p>";
echo "<div class=\"flex justify-between items-center mt-4\">";
echo "<span class=\"text-lg\">₹${item.price}</span>";
echo "<button onclick=\"addToCart('${item.id}')\" class=\"bg-orange-600 text-white px-4 py-2 rounded\">Add</button>";
echo "</div>";
echo "`;";
echo "menuContainer.appendChild(itemElement);";
echo "});";
echo "});";
echo "}";
echo "";
echo "// Add item to cart";
echo "function addToCart(itemId) {";
echo "const selected = JSON.parse(localStorage.getItem('selectedRestaurant') || '{}');";
echo "const list = menusByRestaurant[selected.id] || [];";
echo "const item = list.find(i => i.id === itemId);";
echo "if (item) {";
echo "cart.items.push(item);";
echo "cart.total += item.price;";
echo "updateCartUI();";
echo "// persist to site-wide cart used by checkout";
echo "const globalCart = JSON.parse(localStorage.getItem('cart')||'[]');";
echo "const existing = globalCart.find(x => x.id === (selected.name + ' - ' + item.name));";
echo "const mapped = { id: selected.name + ' - ' + item.name, title: item.name, price: item.price, qty: 1, image: item.image || selected.image, badge: selected.name };";
echo "if(existing){ existing.qty += 1; } else { globalCart.push(mapped); }";
echo "localStorage.setItem('cart', JSON.stringify(globalCart));";
echo "}";
echo "}";
echo "";
echo "// Update cart UI";
echo "function updateCartUI() {";
echo "const cartItems = document.getElementById('cartItems');";
echo "const cartCount = document.getElementById('cartCount');";
echo "const cartTotal = document.getElementById('cartTotal');";
echo "";
echo "cartCount.textContent = cart.items.length;";
echo "cartTotal.textContent = `₹${cart.total}`;";
echo "";
echo "cartItems.innerHTML = cart.items.map(item => `";
echo "<div class=\"flex justify-between items-center\">";
echo "<span>${item.name}</span>";
echo "<span>₹${item.price}</span>";
echo "</div>";
echo "`).join('');";
echo "}";
echo "";
echo "// Toggle cart sidebar";
echo "document.getElementById('cartBtn').addEventListener('click', () => {";
echo "document.getElementById('cartSidebar').classList.toggle('translate-x-full');";
echo "});";
echo "";
echo "document.getElementById('closeCart').addEventListener('click', () => {";
echo "document.getElementById('cartSidebar').classList.add('translate-x-full');";
echo "});";
echo "";
echo "document.getElementById('checkoutBtn').addEventListener('click', () => {";
echo "if (!cart.items.length) { alert('Add items to cart first'); return; }";
echo "window.location.href = 'payment.php';";
echo "});";
echo "";
echo "// Floating menu interactions";
echo "const menuFab = document.getElementById('menuFab');";
echo "const menuPanel = document.getElementById('menuPanel');";
echo "menuFab.addEventListener('click', () => { menuPanel.classList.toggle('hidden'); });";
echo "document.addEventListener('click', (e) => {";
echo "const t = e.target;";
echo "if (!menuPanel.contains(t) && t !== menuFab) menuPanel.classList.add('hidden');";
echo "});";
echo "";
echo "// Initialize";
echo "renderMenu();";
echo "</script>";
echo "</body>";
echo "</html>";
?>