<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "<meta charset=\"UTF-8\" />";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />";
echo "<title>Order Tracking</title>";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">";
echo "<style>";
echo ":root { --bg:#f8fafc; --text:#1a202c; --panel:#ffffff; --ring:#e2e8f0 }";
echo ".dark :root, .dark { --bg:#0f172a; --text:#e5e7eb; --panel:#0b1220; --ring:#1f2937 }";
echo "body { background: var(--bg); color: var(--text); }";
echo "/* Reset and base styles */";
echo "* {";
echo "box-sizing: border-box;";
echo "margin: 0;";
echo "padding: 0;";
echo "}";
echo "";
echo "body {";
echo "font-family: 'Poppins', sans-serif;";
echo "background-color: #f8fafc;";
echo "margin: 0;";
echo "padding: 0;";
echo "color: #1a202c;";
echo "line-height: 1.6;";
echo "}";
echo "";
echo "a {";
echo "text-decoration: none;";
echo "color: #f97316;";
echo "}";
echo "";
echo ".container {";
echo "max-width: 1100px;";
echo "margin: 30px auto;";
echo "background-color: var(--panel);";
echo "padding: 20px 30px;";
echo "border-radius: 12px;";
echo "box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);";
echo "}";
echo "";
echo "header {";
echo "background: var(--panel);";
echo "padding: 15px 30px;";
echo "box-shadow: 0 2px 4px rgba(0, 0, 0, 0.06);";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "font-size: 1rem;";
echo "font-weight: 600;";
echo "letter-spacing: 0.05em;";
echo "margin: -20px -30px 30px -30px;";
echo "border-radius: 12px 12px 0 0;";
echo "}";
echo "";
echo "header .logo {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 10px;";
echo "font-weight: 800;";
echo "color: #1e293b;";
echo "font-size: 1.3rem;";
echo "user-select: none;";
echo "}";
echo "";
echo "header .logo img {";
echo "height: 36px;";
echo "width: 36px;";
echo "}";
echo "";
echo "header .nav-right {";
echo "display: flex;";
echo "gap: 25px;";
echo "align-items: center;";
echo "font-weight: 500;";
echo "}";
echo "";
echo "header .nav-right a {";
echo "cursor: pointer;";
echo "color: #475569;";
echo "transition: color 0.2s;";
echo "}";
echo "";
echo "header .nav-right a:hover {";
echo "color: #f97316;";
echo "}";
echo "";
echo ".help-btn {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 6px;";
echo "padding: 8px 12px;";
echo "background: #f97316;";
echo "color: white;";
echo "border-radius: 6px;";
echo "text-decoration: none;";
echo "font-weight: 600;";
echo "transition: all 0.3s ease;";
echo "}";
echo "";
echo ".help-btn:hover {";
echo "background: #ea580c;";
echo "color: white;";
echo "transform: translateY(-1px);";
echo "}";
echo "";
echo ".order-header {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 15px;";
echo "margin-bottom: 20px;";
echo "padding-bottom: 15px;";
echo "border-bottom: 2px solid #f1f5f9;";
echo "}";
echo "";
echo ".order-id {";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "font-size: 1.2rem;";
echo "}";
echo "";
echo ".status-badge {";
echo "padding: 6px 12px;";
echo "border-radius: 20px;";
echo "font-weight: 600;";
echo "font-size: 0.85rem;";
echo "}";
echo "";
echo ".status-confirmed { background: #ecfdf5; color: #065f46; }";
echo ".status-preparing { background: #fef3c7; color: #92400e; }";
echo ".status-out-for-delivery { background: #dbeafe; color: #1e40af; }";
echo ".status-delivered { background: #d1fae5; color: #065f46; }";
echo ".status-received { background: #d1fae5; color: #065f46; }";
echo ".status-cancelled { background: #fee2e2; color: #991b1b; }";
echo "";
echo ".tracking-steps {";
echo "display: flex;";
echo "flex-direction: column;";
echo "gap: 20px;";
echo "margin-bottom: 30px;";
echo "}";
echo "";
echo ".step-tracker {";
echo "display: flex;";
echo "align-items: center;";
echo "position: relative;";
echo "}";
echo "";
echo ".step-tracker:not(:last-child)::after {";
echo "content: '';";
echo "position: absolute;";
echo "left: 14px;";
echo "top: 30px;";
echo "right: 14px;";
echo "height: 2px;";
echo "background: #e2e8f0;";
echo "z-index: 1;";
echo "}";
echo "";
echo ".step-circle {";
echo "width: 28px;";
echo "height: 28px;";
echo "border-radius: 50%;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "font-weight: bold;";
echo "font-size: 12px;";
echo "position: relative;";
echo "z-index: 2;";
echo "background: #e2e8f0;";
echo "color: #64748b;";
echo "}";
echo "";
echo ".step-circle.completed {";
echo "background: #10b981;";
echo "color: white;";
echo "}";
echo "";
echo ".step-circle.current {";
echo "background: #f97316;";
echo "color: white;";
echo "}";
echo "";
echo ".step-circle.cancelled {";
echo "background: #ef4444;";
echo "color: white;";
echo "}";
echo "";
echo ".step-content {";
echo "flex: 1;";
echo "margin-left: 20px;";
echo "padding: 10px 0;";
echo "}";
echo "";
echo ".step-title {";
echo "font-weight: 600;";
echo "color: #1e293b;";
echo "margin-bottom: 5px;";
echo "}";
echo "";
echo ".step-time {";
echo "color: #64748b;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".order-summary {";
echo "background: var(--panel);";
echo "padding: 25px;";
echo "border-radius: 10px;";
echo "box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);";
echo "margin-bottom: 20px;";
echo "}";
echo "";
echo ".section-heading {";
echo "font-size: 1.1rem;";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "margin-bottom: 15px;";
echo "padding-bottom: 8px;";
echo "border-bottom: 2px solid #f1f5f9;";
echo "}";
echo "";
echo ".food-item {";
echo "display: flex;";
echo "align-items: flex-start;";
echo "gap: 15px;";
echo "margin-bottom: 20px;";
echo "padding-bottom: 20px;";
echo "border-bottom: 1px solid #e2e8f0;";
echo "}";
echo "";
echo ".food-item img {";
echo "width: 80px;";
echo "height: 80px;";
echo "border-radius: 12px;";
echo "object-fit: cover;";
echo "box-shadow: 0 2px 8px rgba(0,0,0,0.12);";
echo "background: #f1f5f9;";
echo "}";
echo "";
echo ".food-details {";
echo "flex-grow: 1;";
echo "}";
echo "";
echo ".food-title {";
echo "font-weight: 700;";
echo "margin: 0 0 5px 0;";
echo "font-size: 1.1rem;";
echo "color: #1e293b;";
echo "}";
echo "";
echo ".food-location {";
echo "color: #64748b;";
echo "font-size: 0.9rem;";
echo "margin-bottom: 10px;";
echo "}";
echo "";
echo ".quantity {";
echo "color: #10b981;";
echo "font-weight: 600;";
echo "}";
echo "";
echo ".price {";
echo "margin-left: auto;";
echo "font-weight: 700;";
echo "font-size: 1.1rem;";
echo "color: #1a202c;";
echo "}";
echo "";
echo ".bill-details {";
echo "font-size: 0.95rem;";
echo "margin-top: 15px;";
echo "}";
echo "";
echo ".bill-row {";
echo "display: flex;";
echo "justify-content: space-between;";
echo "margin-bottom: 10px;";
echo "color: #475569;";
echo "padding: 5px 0;";
echo "}";
echo "";
echo ".bill-row.total {";
echo "font-weight: 800;";
echo "font-size: 1.2rem;";
echo "color: #1e293b;";
echo "border-top: 2px solid #e2e8f0;";
echo "padding-top: 15px;";
echo "margin-top: 10px;";
echo "}";
echo "";
echo ".address-section {";
echo "background: #f8fafc;";
echo "padding: 20px;";
echo "border-radius: 8px;";
echo "margin-bottom: 20px;";
echo "}";
echo "";
echo ".address-details {";
echo "display: flex;";
echo "align-items: flex-start;";
echo "gap: 10px;";
echo "}";
echo "";
echo ".address-icon {";
echo "color: #f97316;";
echo "font-size: 1.2rem;";
echo "margin-top: 2px;";
echo "}";
echo "";
echo ".address-text {";
echo "flex: 1;";
echo "}";
echo "";
echo ".address-name {";
echo "font-weight: 700;";
echo "color: #1e293b;";
echo "margin-bottom: 5px;";
echo "}";
echo "";
echo ".address-line {";
echo "color: #64748b;";
echo "font-size: 0.9rem;";
echo "margin-bottom: 3px;";
echo "}";
echo "";
echo ".delivery-info {";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "padding: 15px;";
echo "background: #f8fafc;";
echo "border-radius: 8px;";
echo "margin-bottom: 20px;";
echo "}";
echo "";
echo ".delivery-time {";
echo "font-weight: 600;";
echo "color: #10b981;";
echo "}";
echo "";
echo ".action-buttons {";
echo "display: flex;";
echo "gap: 10px;";
echo "justify-content: center;";
echo "margin-top: 20px;";
echo "}";
echo "";
echo ".btn {";
echo "padding: 12px 24px;";
echo "border: none;";
echo "border-radius: 8px;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "transition: all 0.3s;";
echo "text-decoration: none;";
echo "display: inline-block;";
echo "}";
echo "";
echo ".btn-primary {";
echo "background: #f97316;";
echo "color: white;";
echo "}";
echo "";
echo ".btn-primary:hover {";
echo "background: #ea580c;";
echo "}";
echo "";
echo ".btn-secondary {";
echo "background: #e2e8f0;";
echo "color: #64748b;";
echo "}";
echo "";
echo ".btn-secondary:hover {";
echo "background: #cbd5e0;";
echo "}";
echo "";
echo ".btn-danger {";
echo "background: #ef4444;";
echo "color: white;";
echo "}";
echo "";
echo ".btn-danger:hover {";
echo "background: #dc2626;";
echo "}";
echo "";
echo ".btn-success {";
echo "background: #10b981;";
echo "color: white;";
echo "}";
echo "";
echo ".btn-success:hover {";
echo "background: #059669;";
echo "}";
echo "";
echo ".cancel-modal {";
echo "position: fixed;";
echo "inset: 0;";
echo "background: rgba(0,0,0,0.5);";
echo "display: none;";
echo "align-items: center;";
echo "justify-content: center;";
echo "z-index: 2000;";
echo "}";
echo "";
echo ".cancel-modal-content {";
echo "background: white;";
echo "padding: 30px;";
echo "border-radius: 12px;";
echo "max-width: 400px;";
echo "width: 90%;";
echo "text-align: center;";
echo "}";
echo "";
echo ".cancel-reason {";
echo "display: none;";
echo "margin-top: 20px;";
echo "text-align: left;";
echo "}";
echo "";
echo ".cancel-reason.active {";
echo "display: block;";
echo "}";
echo "";
echo ".reason-option {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 12px;";
echo "padding: 12px;";
echo "margin: 8px 0;";
echo "border: 1px solid #e2e8f0;";
echo "border-radius: 8px;";
echo "cursor: pointer;";
echo "transition: all 0.3s;";
echo "}";
echo "";
echo ".reason-option:hover {";
echo "border-color: #f97316;";
echo "background: #fff7ed;";
echo "}";
echo "";
echo ".reason-option.selected {";
echo "border-color: #f97316;";
echo "background: #fff7ed;";
echo "}";
echo "";
echo ".reason-option input[type=\"radio\"] {";
echo "margin: 0;";
echo "accent-color: #f97316;";
echo "}";
echo "";
echo ".reason-option label {";
echo "cursor: pointer;";
echo "flex: 1;";
echo "font-size: 0.95rem;";
echo "}";
echo "";
echo ".cancel-buttons {";
echo "display: flex;";
echo "gap: 10px;";
echo "justify-content: center;";
echo "margin-top: 20px;";
echo "}";
echo "";
echo ".confirmation-message {";
echo "margin: 20px 0;";
echo "padding: 15px;";
echo "background: #ecfdf5;";
echo "border-radius: 8px;";
echo "color: #065f46;";
echo "border-left: 4px solid #10b981;";
echo "}";
echo "";
echo ".cancelled-message {";
echo "margin: 20px 0;";
echo "padding: 15px;";
echo "background: #fee2e2;";
echo "border-radius: 8px;";
echo "color: #991b1b;";
echo "border-left: 4px solid #ef4444;";
echo "text-align: center;";
echo "}";
echo "";
echo ".empty-state {";
echo "text-align: center;";
echo "padding: 60px 20px;";
echo "color: #64748b;";
echo "}";
echo "";
echo ".empty-state i {";
echo "font-size: 4rem;";
echo "margin-bottom: 20px;";
echo "opacity: 0.5;";
echo "}";
echo "";
echo ".feature-badges {";
echo "display: flex;";
echo "flex-wrap: wrap;";
echo "gap: 8px;";
echo "margin-top: 10px;";
echo "}";
echo "";
echo ".feature-badge {";
echo "background: #dbeafe;";
echo "color: #1e40af;";
echo "padding: 4px 8px;";
echo "border-radius: 12px;";
echo "font-size: 0.8rem;";
echo "font-weight: 500;";
echo "}";
echo "";
echo ".coupon-badge {";
echo "background: #ecfdf5;";
echo "color: #065f46;";
echo "padding: 4px 8px;";
echo "border-radius: 12px;";
echo "font-size: 0.8rem;";
echo "font-weight: 500;";
echo "}";
echo "</style>";
echo "</head>";
echo "<body>";
echo "<button id=\"dmBtn\" style=\"position:fixed;top:12px;right:12px;z-index:50;background:#f97316;color:#fff;border:none;border-radius:9999px;width:40px;height:40px;cursor:pointer\">🌓</button>";
echo "<header>";
echo "<div class=\"logo\">";
echo "<img src=\"https://cdn-icons-png.flaticon.com/512/2838/2838912.png\" alt=\"logo\"/>";
echo "<a href=\"swiggyhome.php\" style=\"color:#1e293b; text-decoration:none;\">ORDER TRACKING</a>";
echo "</div>";
echo "<nav class=\"nav-right\">";
echo "<a href=\"help.php\" class=\"help-btn\">";
echo "<i class=\"fas fa-question-circle\"></i>";
echo "Help";
echo "</a>";
echo "<a href=\"my acc.php\">User</a>";
echo "</nav>";
echo "</header>";
echo "";
echo "<main class=\"container\">";
echo "<div id=\"emptyState\" class=\"empty-state\" style=\"display: none;\">";
echo "<i class=\"fas fa-inbox\"></i>";
echo "<h3>No Orders Yet</h3>";
echo "<p>Track your recent orders here. Start by placing an order!</p>";
echo "<a href=\"swiggyhome.php\" class=\"btn btn-primary\">Browse Restaurants</a>";
echo "</div>";
echo "";
echo "<div id=\"orderContent\" style=\"display: none;\">";
echo "<div class=\"order-header\">";
echo "<div class=\"order-id\">";
echo "<i class=\"fas fa-hashtag\"></i> Order #<span id=\"orderId\"></span>";
echo "</div>";
echo "<div class=\"status-badge\" id=\"orderStatusBadge\">Confirmed</div>";
echo "</div>";
echo "";
echo "<div class=\"delivery-info\">";
echo "<div>";
echo "<div style=\"color: #64748b; font-size: 0.9rem;\">Estimated Delivery</div>";
echo "<div class=\"delivery-time\" id=\"estimatedDelivery\"></div>";
echo "</div>";
echo "<div id=\"deliveryIcon\" style=\"font-size: 2rem; color: #10b981;\">";
echo "<i class=\"fas fa-bicycle\"></i>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"tracking-steps\">";
echo "<div class=\"step-tracker\">";
echo "<div class=\"step-circle completed\">";
echo "<i class=\"fas fa-check\"></i>";
echo "</div>";
echo "<div class=\"step-content\">";
echo "<div class=\"step-title\">Order Confirmed</div>";
echo "<div class=\"step-time\" id=\"confirmedTime\"></div>";
echo "</div>";
echo "</div>";
echo "<div class=\"step-tracker\">";
echo "<div class=\"step-circle\" id=\"preparingCircle\">";
echo "<i class=\"fas fa-utensils\"></i>";
echo "</div>";
echo "<div class=\"step-content\">";
echo "<div class=\"step-title\">Preparing Food</div>";
echo "<div class=\"step-time\" id=\"preparingTime\"></div>";
echo "</div>";
echo "</div>";
echo "<div class=\"step-tracker\">";
echo "<div class=\"step-circle\" id=\"outCircle\">";
echo "<i class=\"fas fa-shipping-fast\"></i>";
echo "</div>";
echo "<div class=\"step-content\">";
echo "<div class=\"step-title\">Out for Delivery</div>";
echo "<div class=\"step-time\" id=\"outTime\"></div>";
echo "</div>";
echo "</div>";
echo "<div class=\"step-tracker\">";
echo "<div class=\"step-circle\" id=\"deliveredCircle\">";
echo "<i class=\"fas fa-home\"></i>";
echo "</div>";
echo "<div class=\"step-content\">";
echo "<div class=\"step-title\">Delivered</div>";
echo "<div class=\"step-time\" id=\"deliveredTime\"></div>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"address-section\">";
echo "<div class=\"address-details\">";
echo "<div class=\"address-icon\">";
echo "<i class=\"fas fa-map-marker-alt\"></i>";
echo "</div>";
echo "<div class=\"address-text\">";
echo "<div class=\"address-name\" id=\"addressName\"></div>";
echo "<div class=\"address-line\" id=\"addressStreet\"></div>";
echo "<div class=\"address-line\" id=\"addressCity\"></div>";
echo "<div class=\"address-line\" id=\"addressPhone\"></div>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<div class=\"order-summary\">";
echo "<div class=\"section-heading\">Order Summary</div>";
echo "<div id=\"orderItems\"></div>";
echo "<div class=\"feature-badges\" id=\"orderFeatures\"></div>";
echo "<div class=\"coupon-badge\" id=\"orderCoupon\" style=\"display: none;\"></div>";
echo "<div class=\"bill-details\" id=\"orderBill\"></div>";
echo "</div>";
echo "";
echo "<div class=\"action-buttons\">";
echo "<button id=\"markReceived\" class=\"btn btn-success\" style=\"display: none;\">Mark as Received</button>";
echo "<button id=\"cancelOrderBtn\" class=\"btn btn-danger\" style=\"display: none;\">Cancel Order</button>";
echo "<a href=\"swiggyhome.php\" class=\"btn btn-secondary\">Order More</a>";
echo "</div>";
echo "<div id=\"cancelledMessage\" class=\"cancelled-message\" style=\"display: none;\">";
echo "<i class=\"fas fa-times-circle\"></i> Order Cancelled Successfully! Reason: <span id=\"cancelReason\"></span><br>Refund will be processed within 2-3 days. Redirecting to home...";
echo "</div>";
echo "</div>";
echo "</main>";
echo "";
echo "<div class=\"cancel-modal\" id=\"cancelModal\">";
echo "<div class=\"cancel-modal-content\">";
echo "<h2 style=\"color: #1e293b; margin-bottom: 15px;\">Cancel Order?</h2>";
echo "<p style=\"color: #64748b; margin-bottom: 20px;\">Are you sure you want to cancel this order? You may be eligible for a refund.</p>";
echo "<div id=\"cancelReasons\" class=\"cancel-reason\">";
echo "<h3 style=\"color: #1e293b; margin-bottom: 15px;\">Select a reason</h3>";
echo "<div class=\"reason-option\">";
echo "<input type=\"radio\" name=\"cancelReason\" value=\"changed mind\" id=\"changedMind\">";
echo "<label for=\"changedMind\">Changed my mind</label>";
echo "</div>";
echo "<div class=\"reason-option\">";
echo "<input type=\"radio\" name=\"cancelReason\" value=\"wrong address\" id=\"wrongAddress\">";
echo "<label for=\"wrongAddress\">Wrong address entered</label>";
echo "</div>";
echo "<div class=\"reason-option\">";
echo "<input type=\"radio\" name=\"cancelReason\" value=\"long wait\" id=\"longWait\">";
echo "<label for=\"longWait\">Too long wait time</label>";
echo "</div>";
echo "<div class=\"reason-option\">";
echo "<input type=\"radio\" name=\"cancelReason\" value=\"other\" id=\"other\">";
echo "<label for=\"other\">Other</label>";
echo "</div>";
echo "</div>";
echo "<div class=\"cancel-buttons\">";
echo "<button type=\"button\" class=\"btn btn-secondary\" id=\"confirmCancel\">Yes, Cancel</button>";
echo "<button type=\"button\" class=\"btn btn-primary\" id=\"closeCancel\">No, Keep Order</button>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "";
echo "<script>";
echo "// Dark mode";
echo "(function(){";
echo "const saved = localStorage.getItem('theme');";
echo "if(saved === 'dark') document.documentElement.classList.add('dark');";
echo "document.getElementById('dmBtn').addEventListener('click', ()=>{";
echo "document.documentElement.classList.toggle('dark');";
echo "localStorage.setItem('theme', document.documentElement.classList.contains('dark') ? 'dark' : 'light');";
echo "});";
echo "})();";
echo "";
echo "document.addEventListener('DOMContentLoaded', function() {";
echo "// Set user name in header if available";
echo "(function(){";
echo "const nav = document.querySelector('nav.nav-right a[href=\"my acc.php\"]');";
echo "const savedName = localStorage.getItem('userName');";
echo "if (nav && savedName && savedName.trim()) nav.textContent = savedName;";
echo "})();";
echo "";
echo "function getOrders() { try { return JSON.parse(localStorage.getItem('orders') || '[]'); } catch { return []; } }";
echo "";
echo "const orders = getOrders();";
echo "if (orders.length === 0) {";
echo "document.getElementById('emptyState').style.display = 'block';";
echo "return;";
echo "}";
echo "";
echo "// Get the latest order (first in array as per unshift in checkout)";
echo "const latestOrder = orders[0];";
echo "";
echo "// Simulate status progression based on time (for demo; in real app, use server updates)";
echo "const now = new Date();";
echo "const orderTime = new Date(latestOrder.timestamp);";
echo "const estimatedDelivery = new Date(latestOrder.estimatedDelivery);";
echo "const timeElapsed = now - orderTime;";
echo "";
echo "let status = latestOrder.status || 'confirmed';";
echo "let preparingTime = '';";
echo "let outTime = '';";
echo "let deliveredTime = '';";
echo "let received = false;";
echo "";
echo "if (status === 'cancelled') {";
echo "// Handle cancelled status";
echo "} else if (timeElapsed > 10 * 60000) { // 10 min after order: preparing";
echo "status = 'preparing';";
echo "preparingTime = new Date(orderTime.getTime() + 10 * 60000).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });";
echo "}";
echo "if (timeElapsed > 25 * 60000) { // 25 min: out for delivery";
echo "status = 'out-for-delivery';";
echo "outTime = new Date(orderTime.getTime() + 25 * 60000).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });";
echo "}";
echo "if (now > estimatedDelivery) { // After estimated: delivered";
echo "status = 'delivered';";
echo "deliveredTime = estimatedDelivery.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });";
echo "if (latestOrder.isReceived !== true) { // Assume received if past delivery + 5 min";
echo "if (now > new Date(estimatedDelivery.getTime() + 5 * 60000)) {";
echo "received = true;";
echo "latestOrder.isReceived = true;";
echo "localStorage.setItem('orders', JSON.stringify(orders)); // Persist received status";
echo "}";
echo "} else {";
echo "received = true;";
echo "}";
echo "if (received) status = 'received';";
echo "}";
echo "";
echo "// Update status in order";
echo "latestOrder.status = status;";
echo "localStorage.setItem('orders', JSON.stringify(orders));";
echo "";
echo "// Display order info";
echo "document.getElementById('orderId').textContent = latestOrder.id.slice(3);";
echo "document.getElementById('estimatedDelivery').textContent = latestOrder.scheduledDateTimeReadable || '43 mins';";
echo "document.getElementById('confirmedTime').textContent = orderTime.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });";
echo "document.getElementById('preparingTime').textContent = preparingTime || '--:--';";
echo "document.getElementById('outTime').textContent = outTime || '--:--';";
echo "document.getElementById('deliveredTime').textContent = deliveredTime || '--:--';";
echo "";
echo "// Address";
echo "const addr = latestOrder.address;";
echo "document.getElementById('addressName').textContent = addr.name;";
echo "document.getElementById('addressStreet').textContent = addr.street + (addr.landmark ? `, ${addr.landmark}` : '');";
echo "document.getElementById('addressCity').textContent = `${addr.city}, ${addr.pincode}`;";
echo "document.getElementById('addressPhone').textContent = `Phone: ${addr.phone}`;";
echo "";
echo "// Status badge and steps";
echo "const badge = document.getElementById('orderStatusBadge');";
echo "const preparingCircle = document.getElementById('preparingCircle');";
echo "const outCircle = document.getElementById('outCircle');";
echo "const deliveredCircle = document.getElementById('deliveredCircle');";
echo "badge.textContent = status.charAt(0).toUpperCase() + status.slice(1).replace('-', ' ');";
echo "badge.className = `status-badge status-${status}`;";
echo "";
echo "if (status === 'cancelled') {";
echo "// Special handling for cancelled";
echo "preparingCircle.classList.remove('completed', 'current');";
echo "outCircle.classList.remove('completed', 'current');";
echo "deliveredCircle.classList.remove('completed', 'current');";
echo "document.getElementById('deliveryIcon').innerHTML = '<i class=\"fas fa-times-circle\" style=\"color: #ef4444;\"></i>';";
echo "document.getElementById('cancelledMessage').style.display = 'block';";
echo "document.getElementById('cancelReason').textContent = latestOrder.cancelReason || 'Not specified';";
echo "// Hide actions";
echo "document.getElementById('cancelOrderBtn').style.display = 'none';";
echo "document.getElementById('markReceived').style.display = 'none';";
echo "// Redirect after 3 seconds";
echo "setTimeout(() => { window.location.href = 'swiggyhome.php'; }, 3000);";
echo "} else if (status === 'confirmed') {";
echo "preparingCircle.classList.add('current');";
echo "} else if (status === 'preparing') {";
echo "preparingCircle.classList.add('completed');";
echo "outCircle.classList.add('current');";
echo "} else if (status === 'out-for-delivery') {";
echo "preparingCircle.classList.add('completed');";
echo "outCircle.classList.add('completed');";
echo "deliveredCircle.classList.add('current');";
echo "} else if (status === 'delivered' || status === 'received') {";
echo "preparingCircle.classList.add('completed');";
echo "outCircle.classList.add('completed');";
echo "deliveredCircle.classList.add('completed');";
echo "if (status === 'received') {";
echo "document.getElementById('deliveryIcon').innerHTML = '<i class=\"fas fa-check-circle\"></i>';";
echo "}";
echo "}";
echo "";
echo "// Render items";
echo "const itemsContainer = document.getElementById('orderItems');";
echo "let itemTotal = 0;";
echo "latestOrder.items.forEach(item => {";
echo "const row = document.createElement('div');";
echo "row.className = 'food-item';";
echo "row.innerHTML = `";
echo "<img src=\"${item.image || 'pay.avif'}\" alt=\"${item.title}\">";
echo "<div class=\"food-details\">";
echo "<div class=\"food-title\">${item.title}</div>";
echo "<div class=\"food-location\">${item.badge || ''} • ${item.timeNote || ''}</div>";
echo "<div style=\"color: #10b981; font-weight: 600;\">Qty: ${item.qty || 1}</div>";
echo "<div class=\"price\">₹${item.price * (item.qty || 1)}</div>";
echo "</div>";
echo "`;";
echo "itemsContainer.appendChild(row);";
echo "itemTotal += item.price * (item.qty || 1);";
echo "});";
echo "";
echo "// Features";
echo "const featuresContainer = document.getElementById('orderFeatures');";
echo "if (latestOrder.orderFeatures.ecoPacking) {";
echo "const badge = document.createElement('div');";
echo "badge.className = 'feature-badge';";
echo "badge.textContent = 'Eco Packing';";
echo "featuresContainer.appendChild(badge);";
echo "}";
echo "if (latestOrder.orderFeatures.giftCard) {";
echo "const badge = document.createElement('div');";
echo "badge.className = 'feature-badge';";
echo "badge.textContent = `Gift Card: ${latestOrder.orderFeatures.giftCardDesign}`;";
echo "featuresContainer.appendChild(badge);";
echo "}";
echo "if (latestOrder.orderFeatures.splitBill) {";
echo "const badge = document.createElement('div');";
echo "badge.className = 'feature-badge';";
echo "badge.textContent = `Split Bill (${latestOrder.orderFeatures.splitBillCount} people)`;";
echo "featuresContainer.appendChild(badge);";
echo "}";
echo "";
echo "// Coupon";
echo "if (latestOrder.appliedCoupon) {";
echo "const couponEl = document.getElementById('orderCoupon');";
echo "couponEl.textContent = `${latestOrder.appliedCoupon.code} Applied`;";
echo "couponEl.style.display = 'block';";
echo "}";
echo "";
echo "// Bill details (reconstruct from stored data)";
echo "let featuresCost = 0;";
echo "if (latestOrder.orderFeatures.ecoPacking) featuresCost += 5;";
echo "if (latestOrder.orderFeatures.giftCard) featuresCost += 25;";
echo "const subtotal = itemTotal + featuresCost;";
echo "let deliveryFee = latestOrder.items.length ? 48 : 0;";
echo "let discountAmount = 0;";
echo "if (latestOrder.appliedCoupon) {";
echo "if (latestOrder.appliedCoupon.type === 'percentage') {";
echo "discountAmount = Math.min((subtotal * latestOrder.appliedCoupon.discount / 100), latestOrder.appliedCoupon.max || Infinity);";
echo "} else if (latestOrder.appliedCoupon.type === 'fixed') {";
echo "discountAmount = latestOrder.appliedCoupon.discount;";
echo "} else if (latestOrder.appliedCoupon.type === 'delivery') {";
echo "discountAmount = deliveryFee;";
echo "deliveryFee = 0;";
echo "}";
echo "}";
echo "const taxableAmount = subtotal - discountAmount + deliveryFee;";
echo "const gst = Math.round(taxableAmount * 0.18);";
echo "const codCharge = (latestOrder.paymentMethod === 'cod') ? 10 : 0;";
echo "const total = taxableAmount + gst + codCharge;";
echo "";
echo "document.getElementById('orderBill').innerHTML = `";
echo "<div class=\"bill-row\"><span>Item Total</span> <span>₹${itemTotal}</span></div>";
echo "<div class=\"bill-row\"><span>Delivery Fee</span> <span>₹${deliveryFee}</span></div>";
echo "${discountAmount > 0 ? `<div class=\"bill-row\" style=\"color: #10b981;\"><span>Discount</span> <span>-₹${Math.round(discountAmount)}</span></div>` : ''}";
echo "${featuresCost > 0 ? `<div class=\"bill-row\"><span>Order Features</span> <span>+₹${featuresCost}</span></div>` : ''}";
echo "<div class=\"bill-row\"><span>GST (18%)</span> <span>₹${gst}</span></div>";
echo "${codCharge > 0 ? `<div class=\"bill-row\"><span>COD Charge</span> <span>₹${codCharge}</span></div>` : ''}";
echo "<div class=\"bill-row total\"><span>Total Paid</span> <span>₹${total}</span></div>";
echo "`;";
echo "";
echo "// Actions";
echo "const cancelBtn = document.getElementById('cancelOrderBtn');";
echo "const markReceivedBtn = document.getElementById('markReceived');";
echo "const cancelModal = document.getElementById('cancelModal');";
echo "";
echo "if (status === 'confirmed' || status === 'preparing') {";
echo "cancelBtn.style.display = 'inline-block';";
echo "}";
echo "if (status === 'delivered' && !received) {";
echo "markReceivedBtn.style.display = 'inline-block';";
echo "}";
echo "";
echo "cancelBtn.addEventListener('click', () => {";
echo "cancelModal.style.display = 'flex';";
echo "document.getElementById('cancelReasons').classList.add('active');";
echo "document.querySelectorAll('.reason-option').forEach(opt => opt.classList.remove('selected'));";
echo "});";
echo "";
echo "document.getElementById('closeCancel').addEventListener('click', () => {";
echo "cancelModal.style.display = 'none';";
echo "document.getElementById('cancelReasons').classList.remove('active');";
echo "document.querySelectorAll('.reason-option').forEach(opt => opt.classList.remove('selected'));";
echo "});";
echo "";
echo "document.querySelectorAll('.reason-option').forEach(option => {";
echo "option.addEventListener('click', () => {";
echo "document.querySelectorAll('.reason-option').forEach(opt => opt.classList.remove('selected'));";
echo "option.classList.add('selected');";
echo "});";
echo "});";
echo "";
echo "document.getElementById('confirmCancel').addEventListener('click', () => {";
echo "const selectedReason = document.querySelector('input[name=\"cancelReason\"]:checked');";
echo "if (!selectedReason) {";
echo "alert('Please select a reason for cancellation.');";
echo "return;";
echo "}";
echo "latestOrder.status = 'cancelled';";
echo "latestOrder.cancelReason = selectedReason.value;";
echo "localStorage.setItem('orders', JSON.stringify(orders));";
echo "";
echo "// Update UI in place for cancelled";
echo "status = 'cancelled';";
echo "badge.textContent = 'Cancelled';";
echo "badge.className = `status-badge status-cancelled`;";
echo "preparingCircle.classList.remove('completed', 'current');";
echo "outCircle.classList.remove('completed', 'current');";
echo "deliveredCircle.classList.remove('completed', 'current');";
echo "deliveredCircle.classList.add('cancelled');";
echo "document.getElementById('deliveryIcon').innerHTML = '<i class=\"fas fa-times-circle\" style=\"color: #ef4444;\"></i>';";
echo "document.getElementById('cancelledMessage').style.display = 'block';";
echo "document.getElementById('cancelReason').textContent = selectedReason.value;";
echo "cancelBtn.style.display = 'none';";
echo "markReceivedBtn.style.display = 'none';";
echo "cancelModal.style.display = 'none';";
echo "";
echo "// Redirect to home after 3 seconds";
echo "setTimeout(() => { window.location.href = 'swiggyhome.php'; }, 3000);";
echo "});";
echo "";
echo "markReceivedBtn.addEventListener('click', () => {";
echo "latestOrder.isReceived = true;";
echo "latestOrder.status = 'received';";
echo "localStorage.setItem('orders', JSON.stringify(orders));";
echo "alert('Order marked as received. Enjoy your meal!');";
echo "location.reload();";
echo "});";
echo "";
echo "document.getElementById('orderContent').style.display = 'block';";
echo "});";
echo "</script>";
echo "</body>";
echo "</html>";
?>